version: "3.3"

services:
  ubuntu1:
    container_name: ubuntu1
    image: maximofn/ubuntu_ssh:1.0.0
    build: .
    command: tail -f /dev/null
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    network_mode: "bridge"