# Introdução ao terminal

## Formato de postagem

Este caderno foi traduzido automaticamente para torná-lo acessível a mais pessoas, por favor me avise se você vir algum erro de digitação..

Para não ter que colocar imagens do console em cada ação que faço, criei a seguinte função que recebe o comando do terminal que queremos executar e retorna a saída que o terminal nos daria.

Às vezes, usarei essa função e, às vezes, usarei `!` antes de cada comando, o que, nos notebooks, significa que você executará um comando de terminal.

In [1]:
import subprocess
import os

last_directory = ''

def terminal(command, max_lines_output=None):
    global last_directory
    debug = False
    str = command.split()

    # Check if there are " or ' characters
    for i in range(len(str)):
        if debug:   print(f"i = {i}, str[i] = {str[i]}")
        if len(str[i]) > 0:
            if str[i][0] == '"' or str[i][0] == "'":
                for j in range(i+1,len(str)):
                    if debug:   print(f"\t j = {j}, str[j] = {str[j]}")
                    if str[j][-1] == '"' or str[j][-1] == "'":
                        for k in range(i+1,j+1):
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                            str[i] = str[i] + " " + str[k]
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                        str[j:] = [""]
                        str[i] = str[i].replace('"','')
    
    # Remove empty strings
    str = [x for x in str if x != ""]
    if debug:
        print(str)
        return
    if str[0] == "cd":
        last_dir = os.getcwd()
        if len(str) == 1:
            os.chdir('/home/wallabot')
        else:
            if str[1] == "-":
                os.chdir(last_directory)
            else:
                os.chdir(str[1])
        last_directory = last_dir
    else:
        result = subprocess.run(str, stdout=subprocess.PIPE).stdout.decode('utf-8')
        if max_lines_output is not None:
            result_split = result.split('\n')
            print('\n'.join(result_split[:max_lines_output]))
            print("\t ...")
            print('\n'.join(result_split[-5:]))
        else:
            print(result)

## Primeiros comandos para navegar no terminal

### `ls` (listar diretório)

O primeiro comando que vamos examinar é o `ls` (list directory), que é usado para listar todos os arquivos da pasta em que estamos.

In [2]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



Normalmente, os comandos podem receber opções (`flags`), que são introduzidas com o caractere `-`, por exemplo, `ls -l` que retorna a lista de arquivos no diretório em que você está, mas com mais informações.

In [3]:
terminal('ls -l')

total 4512
-rw-rw-r-- 1 wallabot wallabot 285898 nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  78450 nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 484213 nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 320810 dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 320594 dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 119471 oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot   2660 sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 699225 nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 509125 sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 156193 nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  53094 oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot   4096 nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  1

Como podemos ver, temos a quantidade de bytes que cada arquivo ocupa, mas quando temos arquivos que ocupam muito espaço, isso não é muito fácil de ler, então podemos adicionar a opção `h` (`human`) que nos dá informações mais fáceis de ler.

In [4]:
terminal('ls -lh')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipy

Se quisermos ver os arquivos ocultos, podemos usar a opção `a`, que nos mostrará todos os arquivos em um diretório.

In [5]:
terminal('ls -lha')

total 4,5M
drwxrwxr-x 6 wallabot wallabot 4,0K dic  6 00:04 .
drwxrwxr-x 5 wallabot wallabot 4,0K oct  2 03:10 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 w

Se quisermos classificá-los por tamanho, podemos usar a opção `S`.

In [6]:
terminal('ls -lhS')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:11 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 314K dic  6 00:04 2022-09-12 Introduccion a la terminal.txt
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 w

Se quisermos exibir os arquivos em ordem alfabética, mas em ordem inversa, devemos usar a opção `r`.

In [7]:
terminal('ls -lhr')

total 4,5M
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
-rw-rw-r-- 1 wallabot wallabot  586 dic  4 02:31 ssh.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K ago 27 03:25 __pycache__
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 notebooks_translated
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
drwxrwxr-x 3 wallabot wallabot 4,0K nov 12 01:51 introduccion_python
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 117K 

### `cd` (mudar de diretório)

O segundo comando será `cd` (change directory), que nos permite alterar o diretório

In [8]:
terminal('cd /home/wallabot/Documentos/')

Se agora voltarmos a usar o `ls` para ver os arquivos que temos, veremos as seguintes alterações

In [9]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
gstreamer
gstreamer_old
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Se dermos o caractere `-` a `cd` em vez do diretório para o qual queremos nos mover, ele retornará ao diretório anterior em que estava.

In [10]:
terminal('cd -')

In [11]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



Se quisermos ir para o `home`, basta digitar `cd` no terminal para irmos para o `home`.

In [12]:
terminal('cd')

### `pwd` (imprimir diretório de trabalho)

Para obter o diretório em que você está, podemos usar `pwd` (imprimir diretório de trabalho)

In [15]:
terminal('pwd')

/home/wallabot



Podemos nos mover usando o comando `cd` por caminhos relativos e por caminhos absolutos. Por exemplo, vamos nos mover para um diretório usando um caminho absoluto

In [16]:
terminal('cd /home/wallabot/Documentos/')

In [17]:
terminal('pwd')

/home/wallabot/Documentos



In [18]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
gstreamer
gstreamer_old
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Podemos nos mover por rotas relativas se colocarmos apenas o endereço do ponto em que estamos.

In [19]:
terminal('cd web')

In [20]:
terminal('pwd')

/home/wallabot/Documentos/web



Também podemos usar caminhos relativos para subir um diretório usando `...`.

In [21]:
terminal('cd ..')

In [22]:
terminal('pwd')

/home/wallabot/Documentos



Se, em vez de `..`, colocarmos `.`, estaremos nos referindo ao diretório em que estamos no momento, ou seja, se colocarmos `cd .`, não nos moveremos, pois estaremos dizendo ao terminal para ir ao diretório em que estamos.

In [23]:
terminal('cd .')

In [24]:
terminal('pwd')

/home/wallabot/Documentos



Vamos para um caminho onde você tem arquivos para mostrar o seguinte comando

In [25]:
terminal('cd web/portafolio/posts/')

In [26]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
ssh.ipynb
test.html
test.ipynb



### Informações do arquivo com `file`

Se eu não souber que tipo de arquivo é um determinado, usando o comando `file`, posso obter uma descrição dele

In [27]:
terminal('file 2021-02-11-Introduccion-a-Python.ipynb')

2021-02-11-Introduccion-a-Python.ipynb: UTF-8 Unicode text, with very long lines



## Manipulação de arquivos e diretórios

Vamos primeiro para a página inicial

In [28]:
terminal('cd /home/wallabot/Documentos/')

### Endereçar a árvore com 'tree

Podemos ver toda a estrutura da pasta em que estamos usando o comando `tree`.

In [29]:
terminal('tree', max_lines_output=20)

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   │   ├── config.cpython-38.pyc
│   │   └── config.cpython-39.pyc
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── gstreamer
│   ├── basic_tutorial_c
│   │   ├── basic_tutorial_1_hello_world
│   │   │   ├── basic-tutorial-1
	 ...
        ├── upload_page.py
        └── utils.py

873 directories, 119679 files



Mas, na saída, temos muitas linhas, e isso ocorre porque o `tree` é um comando que mostra todos os arquivos do caminho em que estamos, portanto, é um pouco difícil de ler. No entanto, com a opção `L`, podemos dizer a ele quantos níveis queremos que sejam detalhados.

In [30]:
terminal('tree -L 2')

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── gstreamer
│   ├── basic_tutorial_c
│   └── README.md
├── gstreamer_old
│   ├── basic_tutorial_c
│   └── basic_tutorial_python
├── jetsonNano
│   ├── apuntes-Jetson-Nano
│   ├── deepstream_apps
│   ├── deepstream_nano
│   └── Digital zoom
├── kaggle
│   └── hubmap
├── Libros
│   └── aprendiendo-git.pdf
├── nerf
│   └── instant-ngp
├── prueba.txt
├── pytorch
│   └── Curso_Pytorch
├── wallabot
│   ├── Microfono - Blue Yeti X
│   ├── placa base - Asus prime x570-p
│   └── Silla - Corsair T3 Rush
└── web
    ├── jupyter-to-html
    ├── jupyter-translator
    ├── portafolio
    └── wordpress_api_rest

30 directories, 12 files



Podemos ver que ele mostra que há 30 diretórios e 12 arquivos, enquanto antes indicava 873 diretórios, 119679 arquivos e 119679 arquivos.

### Criar pastas com `mkdir` (criar diretório)

Se quisermos criar um novo diretório, podemos usar o comando `mkdir` (criar diretório) e um nome

In [31]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/")

In [32]:
terminal('mkdir prueba')

In [33]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Se quisermos criar um diretório com espaços no nome, teremos que colocar o nome entre aspas

In [34]:
terminal('mkdir "directorio prueba"')

In [35]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Vamos entrar na pasta `test` que criamos para continuar visualizando o terminal lá.

In [36]:
terminal("cd prueba")

### Criar arquivos com `touch`.

Se quisermos criar um arquivo, o comando a ser usado é `touch`.

In [37]:
terminal("touch prueba.txt")

In [38]:
terminal("ls")

prueba.txt



### Copiar arquivos com `cp` (copiar)

Se quisermos copiar um arquivo, faremos isso com o comando `cp` (copy).

In [39]:
terminal("cp prueba.txt prueba_copy.txt")

In [40]:
terminal("ls")

prueba_copy.txt
prueba.txt



### Mover arquivos com `mv` (mover)

Se quisermos movê-lo, usaremos o comando `mv` (mover).

In [41]:
terminal("mv prueba.txt ../prueba.txt")

In [42]:
terminal("ls")

prueba_copy.txt



In [43]:
terminal("ls ../")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
ssh.ipynb
test.html
test.ipynb



### Renomear arquivos com `mv` (mover)

O comando `mv` também é útil para renomear arquivos, pois se movermos o arquivo para o mesmo diretório, mas dermos a ele um nome diferente, estaremos renomeando o arquivo.

In [44]:
terminal("mv prueba_copy.txt prueba_move.txt")

In [45]:
terminal("ls")

prueba_move.txt



### Excluir arquivos com `rm` (remover)

Para excluir arquivos ou diretórios, usamos o comando `rm` (remover).

In [46]:
terminal("rm prueba_move.txt")

In [47]:
terminal("ls")

### Remover diretórios com `rm -r` (remover recursivo)

Se quiser excluir um diretório com arquivos, você deverá usar o sinalizador `-r`.

In [48]:
terminal("cd ..")

In [49]:
terminal('rm -r "directorio prueba"')

In [50]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
ssh.ipynb
test.html
test.ipynb



Como você pode ver, ele nunca pergunta se temos certeza; para que ele pergunte, é necessário adicionar o sinalizador `-i` (`iteractive`).

In [66]:
terminal("rm -i prueba.txt")

rm: ¿borrar el fichero regular vacío 'prueba.txt'? (s/n) s



### Sincronize arquivos usando o `rsync`.

Até agora, vimos como copiar, mover e excluir arquivos, mas suponhamos que tenhamos uma pasta e copiemos esses arquivos para outra pasta. Agora, suponha que modificamos um arquivo na primeira pasta e queremos que a segunda pasta tenha as alterações. Temos duas opções: copiar todos os arquivos novamente ou fazer uma sincronização usando o `rsync`.

Primeiro, vamos criar uma nova pasta na qual criaremos vários arquivos

In [1]:
!mkdir sourcefolder
!touch sourcefolder/file1 sourcefolder/file2 sourcefolder/file3

Agora, criamos uma segunda pasta que será sincronizada com a primeira.

In [2]:
!mkdir syncfolder

In [10]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3
ls syncfolder:


Sincronizamos as duas pastas com o `rsync`; na primeira vez, ele copiará apenas os arquivos da primeira pasta para a segunda. Para fazer isso, também devemos adicionar o sinalizador `-r` (recursivo).

In [11]:
!rsync -r sourcefolder/ syncfolder/

In [12]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3
ls syncfolder:
file1  file2  file3


Se eu agora criar um novo arquivo em `sourcefolder` e sincronizar novamente, somente esse arquivo será copiado para `syncfolder`. Para ver que apenas um arquivo é copiado, podemos usar o sinalizador `-v` (verbose).

In [14]:
!touch sourcefolder/file4

In [15]:
!rsync -r -v sourcefolder/ syncfolder/

sending incremental file list
file1
file2
file3
file4

sent 269 bytes  received 92 bytes  722.00 bytes/sec
total size is 0  speedup is 0.00


Mas parece que ele copiou todos os arquivos, portanto, para impedir que isso aconteça e copiar apenas os que foram modificados, use o sinalizador `-u`.

In [16]:
!touch sourcefolder/file5

In [17]:
!rsync -r -v -u sourcefolder/ syncfolder/

sending incremental file list
file5

sent 165 bytes  received 35 bytes  400.00 bytes/sec
total size is 0  speedup is 0.00


In [18]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3  file4  file5
ls syncfolder:
file1  file2  file3  file4  file5


E se eu criar um novo arquivo em `syncfolder`?

In [19]:
!touch syncfolder/file6

In [20]:
!rsync -r -v -u sourcefolder/ syncfolder/

sending incremental file list

sent 122 bytes  received 12 bytes  268.00 bytes/sec
total size is 0  speedup is 0.00


In [21]:
!echo "ls sourcefolder:" && ls sourcefolder && echo "ls syncfolder:" && ls syncfolder

ls sourcefolder:
file1  file2  file3  file4  file5
ls syncfolder:
file1  file2  file3  file4  file5  file6


Ele não o sincroniza, portanto, é importante ter isso em mente.

Alguns sinalizadores importantes que você deve ter em mente são:

 * `-a`: esse sinalizador é um atalho para várias opções, incluindo `-r` (recursivo), `-l` (copiar links simbólicos), `-p` (manter permissões), `-t` (manter tempo de modificação) e `-g` (manter grupo). Essa opção é útil para fazer uma cópia exata de um diretório, incluindo todas as suas subpastas e arquivos.
 * `-v`: esse sinalizador ativa a saída detalhada, que mostra os arquivos que estão sendo copiados e o progresso da operação.
 * `-r`: esse sinalizador é usado para cópia recursiva, o que significa que ele copia todas as subpastas e arquivos em um diretório.
 * `-u`: esse sinalizador é usado para copiar somente arquivos novos ou alterados. Se um arquivo já existir no destino e for mais recente que o arquivo de origem, ele não será copiado.
 * `-n`: esse sinalizador é usado para fazer um teste de cópia, o que significa que nenhuma alteração é feita no destino.
 * `--exclude`: esse sinalizador é usado para excluir arquivos ou pastas específicos da operação de cópia. Você pode especificar vários arquivos ou pastas a serem excluídos usando essa opção várias vezes.
 * `-z`: esse sinalizador é usado para compactar os dados durante a transferência, o que reduz a largura de banda usada e acelera a taxa de transferência.
 * `-h`: esse sinalizador é usado para exibir informações em um formato mais legível, especialmente ao trabalhar com grandes quantidades de dados ou arquivos grandes.

Exclua as duas pastas criadas

In [22]:
!rm -r sourcefolder syncfolder


## Explorando o conteúdo dos arquivos

Para evitar a necessidade de abrir um arquivo em uma interface gráfica, temos várias maneiras. Primeiro, vou copiar um arquivo de texto para essa pasta

In [51]:
terminal("cd prueba")

In [52]:
terminal("cp ../2021-02-11-Introduccion-a-Python.ipynb .")

In [53]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb



### Cabeçalhos de arquivo com `head`.

O primeiro comando para ver dentro de um arquivo de texto é `head`, que permite ver as primeiras 10 linhas de um arquivo, mas com o sinalizador `-n` você pode especificar o número de linhas.

In [54]:
terminal("head 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]



In [55]:
terminal("head -n 5 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {



### Fila de um arquivo com `tail`.

Se quisermos ver as últimas linhas, usaremos `tail`.

In [56]:
terminal("tail 2021-02-11-Introduccion-a-Python.ipynb")

    },
    "vscode": {
      "interpreter": {
        "hash": "d5745ab6aba164e1152437c779991855725055592b9f2bdb41a4825db7168d26"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



In [57]:
terminal("tail -n 5 2021-02-11-Introduccion-a-Python.ipynb")

    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Se quisermos ver continuamente as últimas linhas de um arquivo, por exemplo, se quisermos monitorar continuamente um arquivo LOG para ver eventos, adicionaremos o sinalizador `-f`, o que fará com que o terminal verifique continuamente o arquivo e, sempre que uma nova linha aparecer no arquivo, ele a mostrará.

Por exemplo, se eu monitorar o registro de login em minha máquina

In [57]:
!tail -f /var/log/auth.log

Dec  1 16:27:22 wallabot gcr-prompter[1457]: Gcr: calling the PromptDone method on /org/gnome/keyring/Prompt/p2@:1.26, and ignoring reply
Dec  1 16:27:22 wallabot gnome-keyring-daemon[1178]: asked to register item /org/freedesktop/secrets/collection/login/10, but it's already registered
Dec  1 16:27:26 wallabot systemd-logind[835]: Watching system buttons on /dev/input/event28 (Logitech Wireless Mouse MX Master 3)
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: 10 second inactivity timeout, quitting
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: unregistering prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: disposing prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: finalizing prompter
Dec  1 16:27:34 wallabot polkitd(authority=local): Operator of unix-session:1 successfully authenticated as unix-user:wallabot to gain TEMPORARY authorization for action org.debian.apt.install-or-remove-packages for system-bus-name::1.96 [/usr/bin/python3 /usr/bin/update-manager -

As duas últimas linhas mostram meu login quando liguei o computador hoje.

Agora me conecto via ssh à minha própria máquina

In [57]:
!ssh localhost

wallabot@localhost's password: 
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-53-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.


Se pueden aplicar 0 actualizaciones de forma inmediata.

Your Hardware Enablement Stack (HWE) is supported until April 2025.
*** System restart required ***
Last login: Sun May  8 02:18:09 2022 from 192.168.1.147


No console em que eu estava monitorando o login, apareceram duas novas linhas

Dec  1 16:32:23 wallabot sshd[25647]: Accepted password for wallabot from 127.0.0.1 port 54668 ssh2
Dec  1 16:32:23 wallabot sshd[25647]: pam_unix(sshd:session): session opened for user wallabot by (uid=0)
Dec  1 16:32:23 wallabot systemd-logind[835]: New session 4 of user wallabot.


E quando fecho a sessão ssh, aparecem mais duas novas linhas

Dec  1 16:33:52 wallabot sshd[25647]: pam_unix(sshd:session): session closed for user wallabot
Dec  1 16:33:52 wallabot systemd-logind[835]: Session 4 logged out. Waiting for processes to exit.
Dec  1 16:33:52 wallabot systemd-logind[835]: Removed session 4.


### O visualizador de arquivos mais avançado: `less`.

Um dos comandos mais poderosos para examinar arquivos internos é o `less`.

In [58]:
terminal("less 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ho_8zgIiI0We"
      },
      "source": [
        "## 1. Resumen"
      ]
    },
	 ...
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Como estamos dentro de um bloco de notas, não podemos ver o que realmente está acontecendo quando usamos o `less`, mas quando o usamos, entramos no documento e podemos nos mover por ele usando as teclas ou o mouse.

Se quisermos pesquisar algo dentro do documento, digitamos o caractere `/` e o que quisermos pesquisar. Para alternar entre as diferentes instâncias encontradas, pressionamos a tecla `n` e, se quisermos retroceder nas pesquisas, pressionamos `shift+n`.

Para sair, basta pressionar `q`.

### O visualizador `cat

O cat` não é um visualizador tão poderoso quanto o `less`, mas é útil para visualizar arquivos. Ele não permite que você navegue ou pesquise o arquivo. Exibe todo o conteúdo do arquivo

In [64]:
terminal("cat 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ho_8zgIiI0We"
      },
      "source": [
        "## 1. Resumen"
      ]
    },
	 ...
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



### Editor padrão do sistema `xdg-open`.

Se quisermos abri-lo com o editor padrão do arquivo, teremos que usar o `xdg-open`.

In [59]:
terminal("xdg-open 2021-02-11-Introducción-a-Python.ipynb")

### Navegador de arquivos `nautilus`

Se quisermos abrir a pasta em que estamos, usaremos o `nautilus`.

In [60]:
terminal("nautilus")

E se quisermos que ele seja aberto em uma rota específica, incluiremos a rota

In [62]:
terminal("nautilus ~/")

### Contagem de palavras de um arquivo com `wc` (contagem de palavras)

Por fim, um comando muito útil é o `wc` (contagem de palavras), que mostra quantas linhas, palavras e bits um arquivo tem.

In [63]:
terminal("wc 2021-02-11-Introduccion-a-Python.ipynb")

 11678  25703 285898 2021-02-11-Introduccion-a-Python.ipynb



Como podemos ver, o arquivo tem 11678 linhas, 25703 palavras e ocupa 285898 bytes.

## O que é um comando

Um comando pode ser 4 coisas
 * Um programa executável, que normalmente é armazenado no caminho `/usr/bin`.
 * Um comando do shell
 * Uma função do shell
 * Um alias

Para ver a que classe um comando pertence, usamos `type`.

In [65]:
!type cd

cd is a shell builtin


In [66]:
!type mkdir

mkdir is /usr/bin/mkdir


In [67]:
!type ls

ls is /usr/bin/ls


## O que é um alias?

Um alias é um comando que nós mesmos definimos, definido pelo comando `alias`. Por exemplo, vamos criar o alias `l` que executa `ls -h`.

In [68]:
!alias l='ls -l'

Quando executamos `l`, ele nos mostra o resultado de `ls -h`.

In [67]:
!l

2021-02-11-Introducción-a-Python.ipynb


Mas isso tem o problema de que, quando fechamos o terminal, o `alias` desaparece. Mais tarde, aprenderemos a criar `aliases` permanentes.

## Ajuda do comando

### Ajuda com `help`.

Com muitos comandos do shell, podemos obter ajuda com o comando `help`.

In [67]:
!help cd

cd: cd [-L|[-P [-e]]] [dir]
    Modifica el directorio de trabajo del shell.
    
    Modifica el directorio actual a DIR.  DIR por defecto es el valor de la
    variable de shell HOME.
    
    La variable CDPATH define la ruta de búsqueda para el directorio que
    contiene DIR.  Los nombres alternativos de directorio en CDPATH se
    separan con dos puntos (:).  Un nombre de directorio nulo es igual que
    el directorio actual.  Si DIR comienza con una barra inclinada (/),
    entonces no se usa CDPATH.
    
    Si no se encuentra el directorio, y la opción del shell "cdable_vars"
    está activa, entonces se trata la palabra como un nombre de variable.
    Si esa variable tiene un valor, se utiliza su valor para DIR.
    
    Opciones:
      -L	fuerza a seguir los enlaces simbólicos: resuelve los enlaces
    		simbólicos en DIR después de procesar las instancias de ".."
      -P	usa la estructura física de directorios sin seguir los enlaces
    		simbólicos: resuelve los enlaces s

### Manual com `man`

Outro comando é `man`, que se refere ao manual do usuário.

In [70]:
terminal("man ls", max_lines_output=20)

LS(1)                            User Commands                           LS(1)

NAME
       ls - list directory contents

SYNOPSIS
       ls [OPTION]... [FILE]...

DESCRIPTION
       List  information  about  the FILEs (the current directory by default).
       Sort entries alphabetically if none of -cftuvSUX nor --sort  is  speci‐
       fied.

       Mandatory  arguments  to  long  options are mandatory for short options
       too.

       -a, --all
              do not ignore entries starting with .

       -A, --almost-all
	 ...
       Full documentation at: <https://www.gnu.org/software/coreutils/ls>
       or available locally via: info '(coreutils) ls invocation'

GNU coreutils 8.30              September 2019                           LS(1)



Para sair, pressione `q`, pois o `man` usa o `less` como visualizador manual.

### Informações com `info`

Outro comando é o `info`.

In [71]:
terminal("info ls", max_lines_output=20)

File: coreutils.info,  Node: ls invocation,  Next: dir invocation,  Up: Directory listing

10.1 ‘ls’: List directory contents

The ‘ls’ program lists information about files (of any type, including
directories).  Options and file arguments can be intermixed arbitrarily,
as usual.

   For non-option command-line arguments that are directories, by
default ‘ls’ lists the contents of directories, not recursively, and
omitting files with names beginning with ‘.’.  For other non-option
arguments, by default ‘ls’ lists just the file name.  If no non-option
argument is specified, ‘ls’ operates on the current directory, acting as
if it had been invoked with a single argument of ‘.’.

   By default, the output is sorted alphabetically, according to the
locale settings in effect.(1)  If standard output is a terminal, the
output is in columns (sorted vertically) and control characters are
output as question marks; otherwise, the output is listed one per line
	 ...
‘--show-control-chars’
     Print

Para sair, pressione `q`, pois o `info` usa o `less` como exibição de informações

### Informações de um comando com `whatis`.

Outro comando é o `whatis`.

In [72]:
terminal("whatis ls")

ls (1)               - list directory contents



## Curingas

Os curingas são caracteres especiais usados para realizar pesquisas especiais. Por exemplo, se eu quiser pesquisar todos os arquivos que terminam em `.txt`. Vamos criar alguns arquivos para procurá-los

In [73]:
terminal("touch file.txt dot.txt dot2.txt index.html datos1 datos123 Abc")

In [74]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html



### Todos os caracteres `*`

Agora, procuraremos todos os arquivos `.txt`.

In [75]:
!ls *.txt

dot2.txt  dot.txt  file.txt


Agora, procuraremos por todos aqueles que começam com a palavra `data`.

In [76]:
!ls datos*

datos1	datos123


### Números `?`

Mas e se realmente quisermos que ele nos mostre todos os arquivos que começam com a palavra `data`, mas seguidos apenas por um número, teremos que colocar um ponto de interrogação `?`?

In [76]:
!ls datos?

datos1


Se quisermos que ele tenha três números, precisaremos colocar três pontos de interrogação `?????`.

In [76]:
!ls datos???

datos123


### Letras maiúsculas `[[[:upper:]]`.

Se quisermos que ele pesquise arquivos que comecem com letras maiúsculas

In [76]:
!ls [[:upper:]]*

Abc


### Letras minúsculas `[[[:lower:]]`.

Para arquivos que começam com letras minúsculas

In [76]:
!ls [[:lower:]]*

datos1  datos123  dot2.txt  dot.txt  file.txt  index.html


### Classes

Usando colchetes, podemos criar classes, portanto, se quisermos pesquisar arquivos que comecem com as letras `d` ou `f` seguidas de qualquer caractere

In [76]:
!ls [df]*

datos1  datos123  dot2.txt  dot.txt  file.txt


## Redirecionamentos: como o shell funciona

Um comando funciona da seguinte forma

![comando do pipeline](https://ptgmedia.pearsoncmg.com/images/chap5_9780133927313/elementLinks/05fig02_alt.jpg)

Ele tem uma `entrada padrão`, que, por padrão, é o texto que inserimos pelo teclado, uma `saída padrão`, que, por padrão, é a saída de texto pelo console e um `erro padrão`, que, por padrão, também é uma saída de texto pelo console, mas tem outro formato

### Redirecionamento de "saída padrão

Mas, com o caractere `>`, podemos modificar a `saída padrão` de um comando. Por exemplo, se quisermos listar com o `ls` os arquivos na pasta em que estamos, mas não quisermos que o resultado seja impresso na tela, faríamos o seguinte `ls > list.txt`, isso escreve a lista em `list.txt` e, se `list.txt` não existir, ele a cria

In [77]:
!ls > lista.txt

Vemos que ele criou o arquivo e vemos o que está dentro dele.

In [78]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



In [79]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Vemos que dentro de `list.txt` aparece `list.txt`, isso porque ele primeiro cria o arquivo e, em seguida, executa o comando

Fazemos o mesmo, mas com a pasta dos pais

In [80]:
!ls ../ > lista.txt

Se olharmos novamente para `list.txt`

In [81]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Vemos que o conteúdo foi sobrescrito

Se quisermos que o conteúdo seja concatenado, devemos usar `>>`.

In [82]:
!ls > lista.txt

In [83]:
!ls ../ >> lista.txt

In [84]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt
2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
2022-09-12 Introduccion a la terminal.txt
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
ssh.ipynb
test.html
test.ipynb



Agora, se as informações tiverem sido concatenadas

Isso é muito útil para criar arquivos de registro.

### Redirecionamento de erro padrão

Se executarmos uma operação incorreta, receberemos um erro. Vamos ver o que acontece ao redirecionar um comando que dá erro.

In [85]:
!ls fjhdsalkfs > lista.txt

ls: no se puede acceder a 'fjhdsalkfs': No existe el archivo o el directorio


Como podemos ver, ele deu um erro, mas se agora virmos dentro de `list.txt`

In [86]:
terminal("cat lista.txt")

Vemos que o arquivo está vazio, isso porque não redirecionamos o `erro padrão` para `list.txt`, mas para a `saída padrão`. Como vimos na imagem, há dois padrões de saída em um comando, o primeiro é a `saída padrão` e o segundo é o `erro padrão`, portanto, para redirecionar o erro padrão, devemos indicá-lo com `2>`. Vamos fazer assim

In [87]:
!ls kjhsfskjd 2> lista.txt

In [88]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Como podemos ver, agora ele foi redirecionado.

### Saída padrão e redirecionamento de erro padrão

Se quisermos redirecionar os dois, usaremos o seguinte

In [89]:
!ls kjhsfskjd > lista.txt 2>&1

Vamos dar uma olhada em `list.txt`.

In [90]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Se agora executarmos um comando sem erros

In [91]:
!ls . >> lista.txt 2>&1

Vamos dar uma olhada em `list.txt` (**olho**, agora concatenamos)

In [92]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio
2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Como você pode ver, tanto o "erro padrão" quanto a "saída padrão" foram redirecionados para o mesmo arquivo.

## Pipelines

Podemos criar pipelines fazendo com que a `saída padrão` de um comando se torne a `entrada padrão` de outro. Por exemplo, vamos fazer com que a saída do `ls -lha` seja a entrada do `grep`, que veremos mais tarde, mas é um comando a ser pesquisado.

In [93]:
!ls -lha |  grep -i "txt"

-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt


Como podemos ver, o que fizemos foi levar a saída do `ls` para o `grep`, com o qual procuramos um arquivo com `txt` em seu nome.

## Operadores de controle - encadeamento de comandos

### Comandos em sequência

Uma maneira de encadear comandos sequencialmente é separá-los usando `;`. Isso cria threads separados para cada tarefa

In [94]:
!ls; echo 'Hola'; cal

2021-02-11-Introduccion-a-Python.ipynb	datos123  file.txt
Abc					dot2.txt  index.html
datos1					dot.txt   lista.txt
Hola
   Diciembre 2022     
do lu ma mi ju vi sá  
             1  2  3  
 4  5  6  7  8  9 10  
11 12 13 14 15 16 17  
18 19 20 21 22 23 24  
25 26 27 28 29 30 31  
                      


Como podemos ver, primeiro o comando `ls` foi executado, em seguida, o comando `echo "Hello"` imprimiu o Hello e, finalmente, o calendário foi impresso graças ao comando `cal`.

Vamos agora fazer outro exemplo para ver que eles são executados sequencialmente.

In [95]:
!echo "Before touch;"; ls -lha; touch secuential.txt; echo "After touch:"; ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:04 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:07 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-

Como você pode ver, no primeiro `ls` não há `secuential.txt`, enquanto no segundo há. Isso significa que os comandos foram executados em ordem, um após o outro.

### Comandos paralelos

Se você quiser que os comandos sejam executados em paralelo, use o operador `&`, que criará um novo processo para cada comando.

Vamos dar uma olhada no exemplo anterior

In [96]:
!rm secuential.txt

In [97]:
!echo "Before touch;" & ls -lha & touch secuential.txt & echo "After touch:" & ls -lha

Before touch;
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


Agora você pode ver que eles não foram executados sequencialmente, pois os `echo`s foram executados primeiro, o que levará menos tempo, e depois o restante.

### Comandos de maneira condicional

#### e

Usando o operador `&&`, um comando será executado quando o comando anterior tiver sido executado com êxito.

In [98]:
!rm secuential.txt

In [99]:
!echo "Before touch;" && ls -lha && touch secuential.txt && echo "After touch:" && ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-

Aqui podemos ver como eles foram executados um após o outro, ou seja, um comando não começa até que o anterior termine.

Mas então, qual é a diferença entre `;` e `&&`?

No primeiro deles, o sequencial `;`, primeiro um comando é executado e depois outro, mas para que um comando seja executado, não importa se o anterior foi executado com êxito.

In [100]:
!rm prueba ; ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


Como você pode ver, primeiro você executa `rm test`, obtém um erro e ainda executa `ls -lha test`.

Na forma condicional `&&`, se um comando não for executado com êxito, o próximo comando não será executado.

In [101]:
!rm prueba && ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio


Como você pode ver, o `ls -lha test` não é executado porque o `rm test` apresentou um erro.

#### Ou

Ao contrário do `&&`, o or executará todos os processos, independentemente do resultado. O operador `||` deve ser usado.

In [102]:
!rm prueba || ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:08 .
drwxrwxr-x 7 wallabot wallabot 4,0K dic  6 00:24 ..
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt


A diferença entre isso e `;` é que o `||` (ou) não cria um novo thread para cada comando.

## Como as permissões são tratadas

Ao listar arquivos em um diretório com o sinalizador `-l` (longo), os símbolos aparecem ao lado de cada arquivo.

In [103]:
!mkdir subdirectorio

In [104]:
!ls -l

total 288
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:10 subdirectorio


Isso nos fornece informações sobre cada arquivo

Primeiro, vamos dar uma olhada nos tipos de arquivos que existem
 * -: Arquivo normal
 * d: Diretório
 * l: Link simbólico
 * b: arquivo de bloco especial. São arquivos que lidam com informações de blocos de dados, como, por exemplo, um USB

Em seguida, examinaremos os tipos de modo:

<table border="1">
	<cabeçalho>
		<tr>
			<th scope="col" colspan="3">Proprietário</th>
			<th scope="col" colspan="3">Grupo</th>
			<th scope="col" colspan="3">Mundo</th>
		</tr>
	</header>
	<body>
		<tr>
			<th scope="row" colspan="3">rwx</th>
			<th scope="row" colspan="3">r-x</th>
			<th scope="row" colspan="3">r-x</th>
		</tr>
		<tr>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
		</tr>
		<tr>
			<th scope="row" colspan="3">7</th>
			<th scope="row" colspan="3">5</th>
			<th scope="row" colspan="3">5</th>
		</tr>
	<body>
</table>

 * r: ler
 * w: escrever
 * x: executar

Modo simbólico:
 * u: Somente usuário
 * g: Somente para o grupo
 * ou: Somente para outros (mundo)
 * a: Para todos os

## Modificação das permissões no terminal

Criamos um novo arquivo

In [105]:
terminal("cd subdirectorio")

In [106]:
!echo "hola mundo" > mitexto.txt

In [107]:
!cat mitexto.txt

hola mundo


Vamos dar uma olhada nas permissões que você tem

In [108]:
!ls -l

total 4
-rw-rw-r-- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Como podemos ver, ele tem permissões de leitura e gravação para o meu usuário e o grupo, e apenas permissões de leitura para o resto (mundo).

### Altere as permissões com `chmod` (modo de alteração)

Para alterar as permissões de um arquivo, usamos o comando `chmod` (change mode), no qual temos que colocar em octal as permissões de usuário, depois as permissões de grupo e, por fim, as demais.

In [109]:
!chmod 755 mitexto.txt

In [110]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Vemos que agora meu usuário tem permissões de leitura, gravação e execução, enquanto o grupo e o resto do mundo têm permissões de leitura e execução.

Vamos remover as permissões de leitura somente para o meu usuário. Para alterar apenas as permissões de um usuário, usamos o identificador simbólico, um `+` se quisermos adicionar permissões ou um `-` se quisermos removê-las ou um `=` se quisermos redefini-las e seguido pelo tipo de permissão

In [111]:
!chmod u-r mitexto.txt

In [112]:
!ls -l

total 4
--wxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


In [113]:
!cat mitexto.txt

cat: mitexto.txt: Permiso denegado


Como podemos ver, ao remover as permissões de leitura do meu usuário, não podemos ler o arquivo.

Restabelecemos a permissão de leitura

In [114]:
!chmod u+r mitexto.txt

In [115]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


In [116]:
!cat mitexto.txt

hola mundo


Se quisermos adicionar ou remover permissões para mais de um usuário, faremos isso separando cada permissão por um `,`.

In [117]:
!chmod u-x,go=w mitexto.txt

In [118]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt


Como você pode ver, a permissão de execução do usuário foi removida e a permissão somente de gravação foi definida para o grupo e o resto do mundo.

### Identificação do usuário com `whoami`.

Para descobrir quem somos, podemos usar o comando `whoami` (quem sou eu).

In [119]:
!whoami

wallabot


### Informações do usuário com `id`

Outra maneira, que também fornece mais informações, é o comando `id`.

In [120]:
!id

uid=1000(wallabot) gid=1000(wallabot) grupos=1000(wallabot),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),998(docker)


Esse comando nos informa que nosso ID de usuário é 1000, nosso ID de grupo é 1000 e que pertencemos aos grupos wallabot, adm, cdrom, sudo, dip, plugdev, lpadmin, lxd, sambashare e docker.

### Trocar de usuário com o comando `su` (switch user)

Se quisermos trocar de usuário, usamos o comando `su` (switch user). Dependendo do usuário, use `sudo` (superusuário do).

In [120]:
!sudo su root

root@wallabot:/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio#


Como podemos ver, o `propt` muda e agora indica que somos o usuário `root`.

Vamos para a pasta inicial

In [120]:
!cd

root@wallabot:~#


Mas no Linux há uma pasta pessoal para cada usuário, que pode ser vista executando o comando `pwd`.

In [120]:
!pwd

/root


Criarei um arquivo na pasta em que criei o arquivo *text.txt* anteriormente.

In [120]:
!touch /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt

Volto para o meu usuário

In [120]:
!su wallabot

wallabot@wallabot:


E vou para o diretório onde estão localizados os arquivos que criei.

In [121]:
!cd /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio

Vemos os arquivos que estão lá e suas permissões

In [123]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt
-rw-r--r-- 1 root     root      0 dic  6 01:22 rootfile.txt


Como podemos ver, o usuário e o grupo do arquivo *rootfile.txt* é o usuário `root`.

Se eu for agora o usuário *wallabot* e tentar excluir o arquivo `rootfile.txt`, poderei excluir o arquivo `rootfile.txt`.

In [124]:
!rm rootfile.txt

rm: ¿borrar el fichero regular vacío 'rootfile.txt'  protegido contra escritura? (s/n)


Como podemos ver, ele nos pergunta se queremos excluí-lo, pois ele pertence a outro usuário.

## Alterar a senha de um usuário

Se eu quiser alterar a senha do usuário ativo no momento, usarei o comando `passwd` (senha).

Primeiro, verifico qual é o meu usuário

In [125]:
!whoami

wallabot


E agora tentamos alterar a senha

In [125]:
!passwd

$ passwd
Cambiando la contraseña de wallabot.
Contraseña actual de : 
Nueva contraseña: 
Vuelva a escribir la nueva contraseña


Como podemos ver, ele solicita a senha atual para alterá-la.

## Links simbólicos

Podemos criar links simbólicos para um determinado caminho usando o comando `ln` (link) seguido pelo sinalizador `-s` (simbólico), o diretório e o nome do link.

In [126]:
!ln -s /home/wallabot/Documentos/web web

Se agora listarmos os arquivos

In [127]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 dic  6 01:10 mitexto.txt
-rw-r--r-- 1 root     root      0 dic  6 01:22 rootfile.txt
lrwxrwxrwx 1 wallabot wallabot 29 dic  6 01:28 web -> /home/wallabot/Documentos/web


Vemos o link simbólico `web` apontando para `/home/wallabot/Documents/web:`.

Agora posso acessar a `web`.

In [128]:
terminal("cd web")

In [129]:
!pwd

/home/wallabot/Documentos/web


## Definir variáveis de ambiente

### Exibir variáveis de ambiente com `printenv`.

Com o comando `printenv`, podemos ver todas as variáveis de ambiente

In [130]:
!printenv

GJS_DEBUG_TOPICS=JS ERROR;JS LOG
VSCODE_CWD=/home/wallabot
LESSOPEN=| /usr/bin/lesspipe %s
CONDA_PROMPT_MODIFIER=(base) 
PYTHONIOENCODING=utf-8
USER=wallabot
VSCODE_NLS_CONFIG={"locale":"es","availableLanguages":{"*":"es"},"_languagePackId":"b07c40c9acb9e1d7b3ca14b06f814803.es","_translationsConfigFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/tcf.json","_cacheRoot":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es","_resolvedLanguagePackCoreLocation":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/6261075646f055b99068d3688932416f2346dd3b","_corruptedFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/corrupted.info","_languagePackSupport":true}
VSCODE_HANDLES_UNCAUGHT_ERRORS=true
MPLBACKEND=module://ipykernel.pylab.backend_inline
SSH_AGENT_PID=1373
XDG_SESSION_TYPE=x11
SHLVL=0
HOME=/home/wallabot
CHROME_DESKTOP=code-url-handler.desktop
CONDA_SHLVL=1
DESKTOP_SESSION=ubuntu
GIO_LAUNCHED_DESKTOP_FI

### Exibir uma variável de ambiente com o comando `echo

Para visualizar uma determinada variável de ambiente, podemos fazer isso usando o comando `echo` seguido do símbolo `$` e do nome da variável.

In [131]:
!echo $HOME

/home/wallabot


### Modificando uma variável de ambiente para uma sessão de terminal

Podemos modificar uma variável de ambiente para a sessão ativa do terminal, por exemplo, vamos adicionar um novo caminho à variável `PATH`. Primeiro, veremos o que há nela

In [131]:
!echo $PATH

/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


Agora vamos adicionar um novo endereço

In [131]:
!PATH=$PATH:"subdirectorio

Vamos dar uma olhada novamente no que está dentro do `PATH`.

In [131]:
!echo $PATH

/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:subdirectorio


Vemos que o diretório `subdirectory` foi adicionado.

O problema com esse método é que, quando abrirmos um novo terminal, ele não manterá essa alteração no `PATH`.

### Modificando uma variável de ambiente para todas as sessões de terminal

Vamos para a pasta inicial

In [132]:
terminal("cd /home/wallabot")

Aqui na página inicial, listamos todos os arquivos com o sinalizador `-a` (all)

In [133]:
!ls -a

.		.eclipse		       .pki
..		Escritorio		       Plantillas
.afirma		.gitconfig		       .platformio
anaconda3	.gnupg			       .profile
.audacity-data	Imágenes		       .psensor
.bash_history	.ipython		       Público
.bash_logout	.java			       .python_history
.bashrc		.jupyter		       snap
.cache		.lesshst		       .ssh
.conda		Lightworks		       .sudo_as_admin_successful
.config		.Lightworks.thereCanBeOnlyOne  .thunderbird
.cortex-debug	.local			       Vídeos
.cyberghost	logiops			       .vnc
.dbus		.MCTranscodingSDK	       .vscode
Descargas	.mozilla		       .wget-hsts
.docker		Música
Documentos	.nv


Vemos que há um arquivo chamado `.bashrc`, que é o arquivo que contém nossa configuração do bash.

In [134]:
terminal("cat .bashrc", max_lines_output=3)

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
	 ...
fi
unset __conda_setup
# <<< conda initialize <<<




Esse arquivo é o que configura o terminal toda vez que um novo terminal é aberto, portanto, se editarmos a variável `PATH` nele, essa alteração será mantida em todas as novas janelas de terminal que abrirmos.

Para modificar a variável `PATH` no arquivo de configuração, é necessário adicionar a seguinte linha ao arquivo

```
PATH=$PATH: "subdiretório".
```

### Criar aliases para todas as sessões

Já vimos como criar aliases de comando, mas também aconteceu de eles serem perdidos sempre que fechávamos uma sessão de terminal, então os adicionamos ao arquivo de configuração `.bashrc`. Por exemplo, no meu caso, adicionei as seguintes linhas

```
alias ll='ls -l'
alias la='ls -a'
alias lh='ls -h' alias lh='ls -h' alias lh='ls -h' alias ls -h
alias lha='ls -lha'
```

## Comandos de pesquisa

### Pesquisa binária com `which`.

O primeiro comando de pesquisa que vamos examinar é o `which`, que nos permite encontrar o caminho para os binários.

In [135]:
!which python

/home/wallabot/anaconda3/bin/python


No entanto, se procurarmos por algo que não esteja em um dos caminhos PATH, o `which` não poderá nos informar o caminho.

In [136]:
!which cd

### Procure arquivos com `find`.

Para localizar um arquivo com o find, precisamos informar o caminho a partir do qual queremos localizar o arquivo, seguido do sinalizador `-name` e do nome do arquivo que queremos localizar.

In [137]:
!find ~ -name "2021-02-11-Introduccion-a-Python.ipynb"

/home/wallabot/Documentos/web/portafolio/posts/prueba/2021-02-11-Introduccion-a-Python.ipynb
/home/wallabot/Documentos/web/portafolio/posts/2021-02-11-Introduccion-a-Python.ipynb


Como podemos ver, ele está em seu diretório, além da cópia que criei neste notebook e salvei na pasta `test`.

Um recurso muito poderoso do `find` é o fato de podermos usar `wildcards`, por exemplo, se eu quiser encontrar todos os arquivos de texto na minha pasta `web`.

In [139]:
!find ~/Documentos/web/ -name *.txt

/home/wallabot/Documentos/web/portafolio/posts/2022-09-12 Introduccion a la terminal.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/lista.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot2.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/secuential.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/mitexto.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/file.txt
/home/wallabot/Documentos/web/wordpress_api_rest/page.txt


Se não quisermos que ele diferencie maiúsculas de minúsculas, devemos usar o sinalizador `-iname`. Por exemplo, se pesquisarmos todos os arquivos que contenham a tag `FILE`, mas usando o sinalizador `-iname`

In [140]:
!find ~/Documentos/web/ -iname *FILE*

/home/wallabot/Documentos/web/portafolio/posts/html_files
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/file.txt


Vemos que todos os resultados contêm `file` e não `FILE`, ou seja, não há distinção entre maiúsculas e minúsculas.

Podemos especificar o tipo de arquivo com o sinalizador `-type`. Ele suporta apenas dois tipos: `f` para arquivos e `d` para diretórios.

In [141]:
!find ~/Documentos/nerf -name image*

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [142]:
!find ~/Documentos/nerf -name image* -type d

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [143]:
!find ~/Documentos/nerf -name image* -type f

/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less


Se quisermos filtrar por tamanho de arquivo, podemos usar o sinalizador `-size`, por exemplo, se quisermos pesquisar todos os arquivos com mais de 200 MB

In [144]:
!find ~/Documentos/ -type f -size +200M

/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/efficientnet-b7-dcc49843.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_best_model.pth


Se quisermos executar operações após a pesquisa, usaremos o sinalizador `-exec`.

Por exemplo, procurarei todas as pastas com o nome `subdiretório`.

In [145]:
!find ~/ -name subdirectorio -type d

/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio


Posso excluí-los com o sinalizador `-exec`.

In [164]:
!find ~/ -name subdirectorio -type d -exec rm -r {} \;

rm: ¿borrar el fichero regular vacío '/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt'  protegido contra escritura? (s/n) s
find: ‘/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio’: No existe el archivo o el directorio


In [146]:
!find ~/ -name subdirectorio -type d

Por fim, se usarmos o caractere `!`, estaremos dizendo a ele para encontrar tudo que não corresponda ao que especificamos.

In [147]:
!find ~/Documentos/web/portafolio/posts/prueba ! -name *.txt

/home/wallabot/Documentos/web/portafolio/posts/prueba
/home/wallabot/Documentos/web/portafolio/posts/prueba/index.html
/home/wallabot/Documentos/web/portafolio/posts/prueba/Abc
/home/wallabot/Documentos/web/portafolio/posts/prueba/datos1
/home/wallabot/Documentos/web/portafolio/posts/prueba/2021-02-11-Introduccion-a-Python.ipynb
/home/wallabot/Documentos/web/portafolio/posts/prueba/datos123


Como podemos ver, ele encontrou tudo o que não é um `.txt`.

## comando de pesquisa `grep

grep` é um comando de pesquisa muito poderoso, por isso dedicamos uma seção somente a ele. O comando `grep` usa expressões regulares, portanto, se você quiser aprender sobre elas, deixo um link para uma [postagem] (https://maximofn.com/expresiones-regulares) em que eu as explico.

Vamos começar a ver o poder desse comando, vamos procurar todas as vezes que o texto `MaximoFN` aparece dentro do arquivo `2021-02-11-Introduction-to-Python.ipynb`.

In [148]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/prueba")

In [150]:
terminal("grep MaximoFN 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
	 ...
        "funcion2_del_modulo('MaximoFN')"
            "MaximoFN\n",
        "  print('MaximoFN')\n",
        "  variable = 'MaximoF

No entanto, se fizermos a mesma pesquisa para o texto `maximofn`, encontraremos o texto `maximofn`.

In [151]:
!grep maximofn 2021-02-11-Introduccion-a-Python.ipynb

Nenhum resultado é exibido, pois o `grep` é "sensível a maiúsculas e minúsculas", ou seja, ele procura o texto como você o digitou, sensível a maiúsculas e minúsculas. Se não quisermos que isso ocorra, devemos inserir o sinalizador `-i`.

In [152]:
terminal("grep -i MaximoFN 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
	 ...
        "funcion2_del_modulo('MaximoFN')"
            "MaximoFN\n",
        "  print('MaximoFN')\n",
        "  variable = 'MaximoF

Se quisermos retornar o número de vezes que ela aparece, introduzimos o sinalizador `-c`.

In [153]:
!grep -c MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Se não nos importarmos se ele aparece com letras maiúsculas ou minúsculas, podemos adicionar o sinalizador `-i` novamente, mas não é necessário colocá-lo separadamente do sinalizador `-c`, eles podem ser introduzidos juntos.

In [154]:
!grep -ci MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Se quisermos agora todas as vezes em que **não** aparece a palavra `MaximumFN`, introduziremos o sinalizador `-v`.

In [155]:
!grep -cv MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

11573


## Utilitários de rede

### Informações sobre interfaces de rede com o `ifconfig`.

O primeiro comando será o `ifconfig`, que exibe informações sobre nossas interfaces de rede.

In [156]:
!ifconfig

br-470e52ae2708: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:ac:d0:b9:eb  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:5d:15:1c:e9  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5

Como podemos ver, temos as informações de todas as interfaces de rede do meu computador, mas se eu quiser saber as informações de apenas uma delas, eu a especifico adicionando seu número.

In [157]:
!ifconfig enp6s0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5c:f6:59  txqueuelen 1000  (Ethernet)
        RX packets 144467  bytes 123842258 (123.8 MB)
        RX errors 0  dropped 2060  overruns 0  frame 0
        TX packets 100786  bytes 55749109 (55.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



### Informações sobre interfaces de rede com `ip`.

Outra maneira de obter as informações de nossas interfaces de rede é usar o comando `ip`, acrescentando `a` para obter as informações de todas as interfaces.

In [158]:
!ip a

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 24:4b:fe:5c:f6:59 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.144/24 brd 192.168.1.255 scope global dynamic noprefixroute enp6s0
       valid_lft 80218sec preferred_lft 80218sec
    inet6 fe80::7dc2:6944:3fbe:c18e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp5s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 4c:77:cb:1d:66:cc brd ff:ff:ff:ff:ff:ff
4: br-470e52ae2708: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:a

### Teste as comunicações com `ping`.

Outro comando útil é o `ping`, que pode ser usado para verificar se temos uma conexão com um determinado `IP`. Por exemplo, o `IP` do Google é `142.250.200.78`, portanto, fazemos `ping` para ver se ele responde. O comando `ping` no Linux faz `ping`s sem parar, de modo que nunca termina até que o interrompamos. Para evitar isso, adicionamos o sinalizador `-c` e o número de tentativas.

In [161]:
!ping 142.250.200.132 -c 4

PING 142.250.200.132 (142.250.200.132) 56(84) bytes of data.
64 bytes from 142.250.200.132: icmp_seq=1 ttl=117 time=3.46 ms
64 bytes from 142.250.200.132: icmp_seq=2 ttl=117 time=3.77 ms
64 bytes from 142.250.200.132: icmp_seq=3 ttl=117 time=2.81 ms
64 bytes from 142.250.200.132: icmp_seq=4 ttl=117 time=2.86 ms

--- 142.250.200.132 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.812/3.227/3.773/0.405 ms


O mesmo teria acontecido se tivéssemos feito isso diretamente no `google.com`.

In [160]:
!ping www.google.com -c 4

PING www.google.com (142.250.200.132) 56(84) bytes of data.
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=1 ttl=117 time=2.74 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=2 ttl=117 time=3.96 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=3 ttl=117 time=3.56 ms
64 bytes from mad41s14-in-f4.1e100.net (142.250.200.132): icmp_seq=4 ttl=117 time=2.87 ms

--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 2.741/3.283/3.962/0.499 ms


### Faça o download dos arquivos de origem com `curl`.

Podemos obter um arquivo de texto de um determinado endereço usando o comando `curl`, por exemplo, podemos fazer o download do html do Google

In [162]:
!curl https://www.google.com

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="zXcc4tMJWBRoE7q_o_Z2fQ">(function(){window.google={kEI:'M5GOY6PeLr-jkdUP1pir0AE',kEXPI:'0,1359409,6059,206,4804,2316,383,246,5,5367,1123753,1197713,688,380089,16115,28684,22430,1362,12312,17587,4998,13228,3847,10622,22741,5081,1593,1279,2742,149,1103,840,1983,214,4100,3514,606,2023,2297,14670,3227,2845,7,4773,28997,1850,15757,3,346,230,6459,149,13975,4,1528,2304,7039,27731,7357,13658,4437,16786,5815,2542,4094,4052,3,3541,1,14262,27892,2,14022,6248,19490,5680,1021,2380,28741,4569,6255,23421,1252,5835,14967,4333,7484,11406,15676,8155,7381,

Também podemos criar um pipeline para salvá-lo em um arquivo.

In [163]:
!curl https://www.google.com > google.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15168    0 15168    0     0   135k      0 --:--:-- --:--:-- --:--:--  137k


Agora podemos ver se ele foi salvo corretamente

In [165]:
!cat google.html

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="Jo7WFU6XWWwu6NrdwaRyIw">(function(){window.google={kEI:'R5GOY-LZHLegkdUP_IqzoAE',kEXPI:'0,1359409,6059,206,4804,2316,383,246,5,5367,1123753,1197777,380713,16115,28684,22430,1362,283,12036,17580,4998,13228,516,3331,10622,22741,5081,1593,1279,2742,149,1103,840,1983,4,210,4100,3514,606,2023,2299,14668,3229,2843,7,4773,826,23475,4696,1851,15756,3,346,230,6459,149,13975,4,1528,2304,7039,20309,7422,7357,13658,4437,16786,5812,2545,4094,4052,3,3541,1,11943,30211,2,8984,1,5037,6249,19490,5679,1020,2378,28745,4568,6258,23418,1252,5835,14967,4333,4

### Faça o download de arquivos com o `wget`

Outro comando semelhante é o `wget`, porém, ao contrário do `curl`, o wget baixa o arquivo diretamente.

In [166]:
!wget https://www.google.com

--2022-12-06 01:49:19--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 142.250.200.68, 2a00:1450:4003:80c::2004
Conectando con www.google.com (www.google.com)[142.250.200.68]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “index.html.1”

index.html.1            [ <=>                ]  14,76K  --.-KB/s    en 0,002s  

2022-12-06 01:49:19 (7,17 MB/s) - “index.html.1” guardado [15117]



In [167]:
!ls -l

total 316
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


Vemos que ele o salvou como `index.html`, que é como o Google o nomeou.

Se quisermos que ele seja salvo com um nome específico, podemos usar o sinalizador `-O`.

In [168]:
!wget https://www.google.com -O google2.html

--2022-12-06 01:49:37--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 142.250.200.68, 2a00:1450:4003:80c::2004
Conectando con www.google.com (www.google.com)[142.250.200.68]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “google2.html”

google2.html            [ <=>                ]  14,78K  --.-KB/s    en 0,003s  

2022-12-06 01:49:37 (5,27 MB/s) - “google2.html” guardado [15131]



In [169]:
!ls -l

total 332
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


### Depuração da rota com o `traceroute`.

Um comando muito útil é ver a rota para um destino, para isso usamos o `traceroute`, por exemplo, vamos ver todos os lugares pelos quais tenho que passar para me conectar ao Google.

In [170]:
!traceroute www.google.com

traceroute to www.google.com (142.250.200.68), 64 hops max
  1   192.168.1.1  0,435ms  0,154ms  0,133ms 
  2   188.127.176.1  3,979ms  2,914ms  3,397ms 
  3   10.15.0.77  3,600ms  3,914ms  2,669ms 
  4   10.15.246.6  3,567ms  3,713ms  2,926ms 
  5   *  *  * 
  6   72.14.209.84  3,981ms  2,914ms  2,993ms 
  7   *  *  * 
  8   142.251.54.148  3,856ms  2,916ms  2,905ms 
  9   142.250.200.68  2,908ms  2,949ms  3,037ms 


### Depuração de rota com `mtr`

Outra ferramenta de depuração é o `mtr`, que é uma versão aprimorada do `traceroute`. Ele fornece informações sobre cada salto, como tempo de resposta, porcentagem de pacotes descartados etc.

In [9]:
!mtr -n maximofn.com

wallabot (192.168.178.144)
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                              Packets               Pings
 Host                                                                       Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.178.1                                                            0.0%   345    0.3   0.3   0.3   0.3   0.0
 2. 192.168.0.1                                                              0.0%   344    0.8   1.1   1.1   1.1   0.0
 3. (waiting for reply)
 4. 10.183.52.41                                                             0.0%   344    2.8   2.5   2.5   2.5   0.0
 5. 172.29.0.161                                                            47.7%   344    2.3   3.1   3.1  23.1   0.0
 6. (waiting for reply)
 7. 193.149.1.97                                                             0.0%   344    3.6   3.6   3.6  38.6   0.0
 8. (waiting for reply)
 9. 185.

Como você pode ver no salto 5, quase 50% dos pacotes são perdidos, então eu poderia ligar para a minha companhia telefônica e pedir que tentassem me encaminhar para outro lugar.

### Nome da nossa máquina com `hostname`.

Se quisermos saber o nome da nossa máquina, podemos usar `hostname`, que é útil se quisermos nos conectar à nossa máquina a partir de outra máquina.

In [171]:
!hostname

wallabot


### Informações sobre o gateway padrão com `route -n`.

Se quisermos saber qual é o nosso gateway padrão, usamos o comando `route -n`.

In [172]:
!route -n

Tabla de rutas IP del núcleo
Destino         Pasarela        Genmask         Indic Métric Ref    Uso Interfaz
0.0.0.0         192.168.1.1     0.0.0.0         UG    100    0        0 enp6s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp6s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-470e52ae2708
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp6s0


### Informações de IP de um domínio com `nslookup`.

Se quisermos saber o IP de um domínio, podemos descobri-lo usando o comando `nslookup`.

In [173]:
!nslookup google.com

Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.185.14
Name:	google.com
Address: 2a00:1450:4003:808::200e



Isso nos diz que o IP v4 do Google é 172.217.168.174 e seu IP v6 é 2a00:1450:4003:803::200e.

### Informações da nossa rede com o `netstats`.

O último comando utilitário é o `netstats`, que nos fornece o status da nossa rede e, com o sinalizador `-i`, retorna nossas interfaces de rede.

In [174]:
!netstat -i

Tabla de la interfaz del núcleo
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
br-470e5  1500        0      0      0 0             0      0      0      0 BMU
docker0   1500        0      0      0 0             0      0      0      0 BMU
enp6s0    1500   148385      0   2182 0        106135      0      0      0 BMRU
lo       65536    11674      0      0 0         11674      0      0      0 LRU
wlp5s0    1500        0      0      0 0             0      0      0      0 BMU


### Consultas de DNS com `dig`

Com o comando `dig <domain>`, podemos fazer consultas ao DNS, por exemplo, vamos fazer uma consulta ao Google

In [3]:
!dig google.com


; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20527
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		283	IN	A	142.250.184.14

;; Query time: 8 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: dom sep 24 01:32:07 CEST 2023
;; MSG SIZE  rcvd: 55



Você pode ver

``` bash
;; SEÇÃO DE RESPOSTAS:
google.com. 283 IN A 142.250.184.14
```

Portanto, a consulta nos forneceu o IP do Google

Podemos consultar um servidor DNS específico com `dig @<Servidor DNS> <domínio>`.

In [4]:
!dig @1.1.1.1 google.com


; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15633
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		190	IN	A	142.250.184.14

;; Query time: 8 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: dom sep 24 01:33:40 CEST 2023
;; MSG SIZE  rcvd: 44



Fizemos a mesma consulta, mas chegamos ao DNS da Cloudflare.

## Compactação de arquivos

Antes de compactar e descompactar, vamos ver o que vamos compactar. Primeiro, imprimimos nosso caminho e listamos os arquivos

In [175]:
!pwd; ls -l

/home/wallabot/Documentos/web/portafolio/posts/prueba
total 332
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt


Vamos criar uma nova pasta e copiar tudo o que está dentro da pasta atual para ela.

In [176]:
!mkdir tocompress; cp * tocompress; ls -l

cp: -r not specified; omitting directory 'tocompress'
total 336
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:52 tocompress


Como podemos ver, tudo foi compactado, exceto a própria pasta `tocompress` porque não definimos o sinalizador `-r` no comando `cp`. Mas o que aconteceu é o que queríamos que acontecesse

### Comrpimir com `tar`.

O primeiro comando que usaremos para compactar é o `tar`, ao qual adicionaremos o sinalizador `-c` para compress, `-v` para verbose, para que ele nos informe o que está fazendo, e o sinalizador `-f` para file e, em seguida, o nome que queremos que o arquivo compactado tenha e o nome do arquivo que queremos compactar.

In [177]:
!tar -cvf tocompress.tar tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [178]:
!ls -l

total 676
-rw-rw-r-- 1 wallabot wallabot 285898 dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15131 dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15168 dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15117 dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 348160 dic  6 01:53 tocompress.tar


Vemos que você criou o arquivo `tocompress.tar`.

Agora vamos repetir o processo, mas adicionando o sinalizador `-z`, isso comprime no formato `gzip`, que é um algoritmo de compactação mais eficiente.

In [179]:
!tar -cvzf tocompress.tar.gz tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [180]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


Como você pode ver, o arquivo `tocompress.tar` ocupa `340 kB`, enquanto o arquivo `tocompress.tar.gz` ocupa apenas `52 kB`.

Agora, vamos descompactar os arquivos. Para descompactar, usamos o mesmo comando, apenas trocando o sinalizador `-c` pelo sinalizador `-x`.

Primeiro, excluímos a pasta original

In [181]:
!rm -r tocompress

Descompactar

In [182]:
!tar -xvf tocompress.tar

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [183]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


Fazemos o mesmo com o `gzip`.

In [184]:
!rm -r tocompress

In [185]:
!tar -xvzf tocompress.tar.gz

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [186]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz


### Comprimir com `zip`.

Outro comando para compactar é o `zip`, para compactar basta adicionar o sinalizador `-r` (recursivo), o nome que queremos que o arquivo compactado tenha e o arquivo que queremos compactar.

In [187]:
!zip -r tocompress.zip tocompress

  adding: tocompress/ (stored 0%)
  adding: tocompress/lista.txt (deflated 23%)
  adding: tocompress/dot.txt (stored 0%)
  adding: tocompress/google.html (deflated 56%)
  adding: tocompress/index.html (stored 0%)
  adding: tocompress/Abc (stored 0%)
  adding: tocompress/google2.html (deflated 56%)
  adding: tocompress/dot2.txt (stored 0%)
  adding: tocompress/secuential.txt (stored 0%)
  adding: tocompress/index.html.1 (deflated 56%)
  adding: tocompress/file.txt (stored 0%)
  adding: tocompress/datos1 (stored 0%)
  adding: tocompress/2021-02-11-Introduccion-a-Python.ipynb (deflated 85%)
  adding: tocompress/datos123 (stored 0%)


In [188]:
!ls -lh

total 792K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz
-r

Para descompactar, usamos o comando `unzip` seguido do nome do arquivo que queremos descompactar. Primeiro, excluímos a pasta `tocompress`.

In [189]:
!rm -r tocompress

In [190]:
!unzip tocompress.zip

Archive:  tocompress.zip
   creating: tocompress/
  inflating: tocompress/lista.txt    
 extracting: tocompress/dot.txt      
  inflating: tocompress/google.html  
 extracting: tocompress/index.html   
 extracting: tocompress/Abc          
  inflating: tocompress/google2.html  
 extracting: tocompress/dot2.txt     
 extracting: tocompress/secuential.txt  
  inflating: tocompress/index.html.1  
 extracting: tocompress/file.txt     
 extracting: tocompress/datos1       
  inflating: tocompress/2021-02-11-Introduccion-a-Python.ipynb  
 extracting: tocompress/datos123     


In [191]:
!ls -lh

total 792K
-rw-rw-r-- 1 wallabot wallabot 280K dic  6 00:28 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 Abc
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos1
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 datos123
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 file.txt
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 google2.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:48 google.html
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 00:56 index.html
-rw-rw-r-- 1 wallabot wallabot  15K dic  6 01:49 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 dic  6 01:06 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 dic  6 01:08 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K dic  6 01:52 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K dic  6 01:53 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K dic  6 01:53 tocompress.tar.gz
-r

## Processos em segundo plano e em primeiro plano

### Pause um processo e coloque-o em segundo plano com `CTRL+z`.

Quando executamos um processo no terminal, ele pode não parar de ser executado e queremos continuar usando o terminal. Para resolver isso, podemos mover o processo para segundo plano pressionando `CTRL+z`.

Por exemplo, posso fazer um ping em mim mesmo, sem especificar o número de tentativas, de modo que isso será executado até que eu interrompa o processo pressionando `CTRL+C`.

In [191]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.036 ms
^C
--- localhost ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5127ms
rtt min/avg/max/mdev = 0.024/0.027/0.036/0.004 ms


No entanto, se você quiser interromper o processo por um momento para continuar usando o terminal, digite `CTRL+Z`.

In [191]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.020 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.017 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.055 ms
^Z
[1]+  Detenido                ping localhost


Conforme indicado, o processo foi interrompido, não está em execução enquanto eu o coloco em segundo plano.

### Veja os processos em segundo plano com `jobs`.

Para ver quais processos estão em segundo plano, temos dois comandos: por um lado, podemos usar `jobs`.

In [191]:
!jobs

jobs
[1]+  Detenido                ping localhost


Esse comando nos fornece o número do processo e do trabalho; esse número será o que usaremos para colocar o processo em primeiro plano.

### Visualizar processos em segundo plano com `ps`.

Outro comando que podemos usar é o `ps` (processes).

In [191]:
!ps

    PID TTY          TIME CMD
  16232 pts/3    00:00:00 bash
  17070 pts/3    00:00:00 ping
  18376 pts/3    00:00:00 ps


Esse comando não apenas fornece informações sobre os processos em execução em segundo plano, mas também sobre todos os processos em execução no terminal.

É importante observar que, se abrirmos um novo terminal e usarmos qualquer um desses comandos, ele não nos fornecerá as informações de ping, pois as executamos em outro terminal.

In [191]:
!ps

    PID TTY          TIME CMD
  18993 pts/2    00:00:00 bash
  19290 pts/2    00:00:00 ps


Como podemos ver, `jobs` não retorna nada porque nesse terminal não há nenhum processo em segundo plano e `ps` retorna apenas as informações do bash (o próprio terminal) e o comando ps iniciado.

### Levar um processo do plano de fundo para o primeiro plano

Para trazer um processo para o primeiro plano, você deve usar o comando `fg`; se quiser trazer o último processo que foi trazido para o segundo plano, basta colocar `fg`; caso contrário, você deve indicar o número do trabalho.

Vamos dar outra olhada nos processos que tínhamos em segundo plano.

In [191]:
!jobs

[1]+  Detenido                ping localhost


Podemos colocar esse processo em primeiro plano apenas digitando `fg` ou especificando o número do trabalho com `fg %1`.

In [191]:
!fg %1

ping localhost
64 bytes from localhost (127.0.0.1): icmp_seq=7 ttl=64 time=0.032 ms
64 bytes from localhost (127.0.0.1): icmp_seq=8 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=9 ttl=64 time=0.045 ms
64 bytes from localhost (127.0.0.1): icmp_seq=10 ttl=64 time=0.035 ms
64 bytes from localhost (127.0.0.1): icmp_seq=11 ttl=64 time=0.031 ms


### Executando um processo diretamente em segundo plano

Agora, reiniciaremos o navegador firefox digitando `firefox` no terminal e pressionando `CTRL+Z` para colocá-lo em segundo plano.

In [191]:
!firefox

[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:16:17Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update
^Z
[1]+  Detenido                firefox


Como podemos ver, ele diz que o processo foi interrompido, portanto, se quisermos navegar no Firefox, não poderemos, pois ele foi interrompido.

Para poder iniciar o Firefox e colocá-lo em segundo plano, de modo que ele não bloqueie o terminal, é necessário escrever um `&` no final do comando

In [191]:
!firefox &

[1] 23663
$ [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:19:40Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update

$


Agora iniciamos o Firefox, ele nos informa o número do trabalho e permanece em execução em segundo plano.

De fato, se olharmos agora para os processos, veremos que o status do firefox é *Executando*.

In [191]:
!jobs

[1]+  Ejecutando              firefox &


### Encerrar um processo que está em segundo plano

Como o firefox está sendo executado em segundo plano, se quisermos que ele seja encerrado, devemos usar `kill` e o número do trabalho do processo. Vamos usar `jobs` para ver o número do trabalho do firefox.

In [191]:
!jobs

[1]+  Ejecutando              firefox &


Seu número de trabalho é 1, portanto, definimos esse número para encerrar o processo.

In [191]:
!kill %1

Isso não responde a nada, mas se voltarmos a usar `jobs` para ver os processos em segundo plano

In [191]:
!jobs

[1]+  Terminado               firefox


Vemos que ele nos diz que o firefox terminou, mas se executarmos `jobs` novamente, nada aparecerá.

In [191]:
!jobs

## Processamento em segundo plano independente do terminal

Até agora, vimos como executar processos em segundo plano dependentes do terminal, ou seja, se enviarmos um processo para o segundo plano e fecharmos o terminal, ele enviará uma mensagem de fim para todos os processos em seu segundo plano e eles serão encerrados.

Mas há ocasiões em que queremos que o processo permaneça em segundo plano, para podermos fechar o terminal, abrir outro e recuperar o processo, e para isso usaremos o `tmux`, que é um multiplexador de terminal.

É possível que você já o tenha instalado, portanto, para instalá-lo, é necessário inserir o seguinte

``` bash
sudo apt install tmux
```

Depois de instalado, podemos criar uma nova sessão do `tmux` usando `tmux new -s <nome>`.

``` bash
tmux new -s session1
```

Isso abrirá um novo terminal, que na verdade é uma sessão do `tmux`.

Dentro dele, podemos iniciar um processo, por exemplo, um `ping` em nós mesmos.

In [191]:
!ping localhost

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.019 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.031 ms


Podemos fechar esse terminal

Se abrirmos um novo, poderemos ver todas as sessões `tmux` abertas com o comando `tmux ls`.

In [6]:
!tmux ls

session1: 1 windows (created Tue Nov 29 08:15:22 2022)


E podemos entrar em uma sessão usando o comando `tmux`, seguido de `a` (attach), `-t` (tag) e o nome da sessão

In [191]:
!tmux a -t session1

64 bytes from localhost (127.0.0.1): icmp_seq=146 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=147 ttl=64 time=0.022 ms
64 bytes from localhost (127.0.0.1): icmp_seq=148 ttl=64 time=0.026 ms
64 bytes from localhost (127.0.0.1): icmp_seq=149 ttl=64 time=0.013 ms
64 bytes from localhost (127.0.0.1): icmp_seq=150 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=151 ttl=64 time=0.019 ms


Como podemos ver, recuperamos o `ping` de antigamente.

Quando estamos em uma sessão, podemos sair (matar) a sessão digitando `CTRL+D` ou digitando `exit`.

## Gerenciamento de processos

Para gerenciar os processos em nosso sistema, temos várias opções

### `ps` manipulador de processos

Como vimos anteriormente, o `ps` nos fornece os processos que estão sendo executados em nosso terminal. Por exemplo, executamos um processo em segundo plano e vemos os processos com `ps`.

In [191]:
!firefox &

[1] 50555


Agora vamos examinar os processos

In [191]:
!ps

    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  50555 pts/3    00:00:02 firefox
  50613 pts/3    00:00:00 Socket Process
  50635 pts/3    00:00:00 Privileged Cont
  50683 pts/3    00:00:00 WebExtensions
  50741 pts/3    00:00:00 Web Content
  50743 pts/3    00:00:00 Web Content
  50748 pts/3    00:00:00 Web Content
  50840 pts/3    00:00:00 ps


Quando soubermos seu PID, poderemos encerrar o processo.

In [191]:
!kill 50555

Agora vamos examinar os processos

In [191]:
!ps

    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  51132 pts/3    00:00:00 ps


Mas, como já dissemos, o lado ruim do ps é que ele mostra apenas os processos do seu terminal.

Para mostrar todos os processos do sistema, é necessário adicionar `aux`.

In [3]:
terminal("ps aux", max_lines_output=10)

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.2  0.0 169936 13172 ?        Ss   23:06   0:01 /sbin/init splash
root           2  0.0  0.0      0     0 ?        S    23:06   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   23:06   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   23:06   0:00 [rcu_par_gp]
root           5  0.0  0.0      0     0 ?        I<   23:06   0:00 [netns]
root           7  0.0  0.0      0     0 ?        I<   23:06   0:00 [kworker/0:0H-events_highpri]
root           9  0.0  0.0      0     0 ?        I<   23:06   0:00 [kworker/0:1H-events_highpri]
root          10  0.0  0.0      0     0 ?        I<   23:06   0:00 [mm_percpu_wq]
root          11  0.0  0.0      0     0 ?        S    23:06   0:00 [rcu_tasks_rude_]
	 ...
wallabot   11094  0.0  0.2 1184730916 65900 ?    Sl   23:19   0:00 /opt/google/chrome/chrome --type=renderer --crashpad-handler-pid=5080 --enable-crash-reporter=, -

Agora, se eu quiser pesquisar apenas os processos que meu usuário está executando, posso fazer isso criando um `pipe` e pesquisando com o `grep`.

In [7]:
!ps aux | grep wallabot

avahi        802  0.0  0.0   8536  3912 ?        Ss   23:06   0:00 avahi-daemon: running [wallabot.local]
wallabot    1153  0.0  0.0  19856 10624 ?        Ss   23:06   0:00 /lib/systemd/systemd --user
wallabot    1154  0.0  0.0 170004  3680 ?        S    23:06   0:00 (sd-pam)
wallabot    1159  0.1  0.0 2569384 22808 ?       S<sl 23:06   0:01 /usr/bin/pulseaudio --daemonize=no --log-target=journal
wallabot    1161  0.1  0.1 591424 37248 ?        SNsl 23:06   0:02 /usr/libexec/tracker-miner-fs
wallabot    1164  0.0  0.0 390744  8664 ?        SLl  23:06   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
wallabot    1168  0.0  0.0 166804  6616 tty2     Ssl+ 23:06   0:00 /usr/lib/gdm3/gdm-x-session --run-script env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --systemd --session=ubuntu
wallabot    1173  0.0  0.0   8904  6012 ?        Ss   23:06   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
wallabot    1181  0

### Manipulador de processos principais

Com o `top`, podemos ver todos os processos do sistema operacional. Ele nos mostrará as informações com `less`, portanto, conforme explicado anteriormente, quando você quiser interromper o `top`, digite `q` para interrompê-lo.

In [191]:
!top

top - 09:31:32 up  3:21,  1 user,  load average: 2,42, 2,79, 2,48
Tareas: 382 total,   1 ejecutar,  381 hibernar,    0 detener,    0 zombie
%Cpu(s): 14,2 usuario,  1,5 sist,  0,0 adecuado, 84,3 inact,  0,0 en espera,  0,
MiB Mem :  32006,4 total,  20281,8 libre,   6229,0 usado,   5495,6 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24979,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 137,5   1,2 282:24.59 python   
  44161 wallabot  20   0   30,2g 217208 100148 S  12,5   0,7   0:40.92 spotify  
     76 root      20   0       0      0      0 S   6,2   0,0   0:00.12 ksoftir+ 
   1105 root     -51   0       0      0      0 S   6,2   0,0   2:54.29 irq/125+ 
  43990 wallabot  20   0 3998836 246260 145800 S   6,2   0,8   0:53.69 spotify  
  44101 wallabot  20   0 1995108 130316  89848 S   6,2   0,4   0:08.34 spotify  
  51510 wallabot  20   0   14876   4088   3288 R   

Como você pode ver, o `PID` 44161 é o Spotify, que estou usando agora para reproduzir música, mas com o `ps` não o tínhamos visto.

Como antes, se quisermos eliminar um processo, devemos digitar `kill` e seu `PID`.

O bom do top é que ele nos oferece muito mais utilitários; se pressionarmos `h`, ele nos mostrará a ajuda

In [191]:
!h

Help for Interactive Commands - procps-ng 3.3.16
Window 1:Def: Cumulative mode Apagado.  System: Delay 3,0 secs; Secure mode Apag

  Z,B,E,e   Global: 'Z' colors; 'B' bold; 'E'/'e' summary/task memory scale
  l,t,m     Toggle Summary: 'l' load avg; 't' task/cpu stats; 'm' memory info
  0,1,2,3,I Toggle: '0' zeros; '1/2/3' cpus or numa node views; 'I' Irix mode
  f,F,X     Fields: 'f'/'F' add/remove/order/sort; 'X' increase fixed-width

  L,&,<,> . Locate: 'L'/'&' find/again; Move sort column: '<'/'>' left/right
  R,H,J,C . Toggle: 'R' Sort; 'H' Threads; 'J' Num justify; 'C' Coordinates
  c,i,S,j . Toggle: 'c' Cmd name/line; 'i' Idle; 'S' Time; 'j' Str justify
  x,y     . Toggle highlights: 'x' sort field; 'y' running tasks
  z,b     . Toggle: 'z' color/mono; 'b' bold/reverse (only if 'x' or 'y')
  u,U,o,O . Filter by: 'u'/'U' effective/any user; 'o'/'O' other criteria
  n,#,^O  . Set: 'n'/'#' max tasks displayed; Show: Ctrl+'O' other filter(s)
  V,v     . Toggle: 'V' forest view; 'v' h

Para sair, pressione `ESC` ou `q`.

Conforme mostrado na ajuda, se digitarmos `u`, poderemos filtrar por usuário; digitamos meu usuário (wallabot) e posso ver apenas meus processos.

In [191]:
!u

top - 09:35:57 up  3:25,  1 user,  load average: 1,02, 2,27, 2,39
Tareas: 378 total,   1 ejecutar,  377 hibernar,    0 detener,    0 zombie
%Cpu(s): 13,4 usuario,  0,4 sist,  0,0 adecuado, 86,1 inact,  0,1 en espera,  0,
MiB Mem :  32006,4 total,  20288,0 libre,   6212,0 usado,   5506,4 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24989,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 148,2   1,2 288:46.50 python   
  43990 wallabot  20   0 3998836 246552 146092 S   2,7   0,8   0:59.55 spotify  
   1384 wallabot  20   0 4909848 453700 133164 S   1,7   1,4  11:14.02 gnome-s+ 
   1119 wallabot   9 -11 3093876  24504  17836 S   1,3   0,1   0:48.99 pulseau+ 
  32462 wallabot  20   0 1134,0g 643412 128632 S   1,3   2,0   7:39.91 chrome   
  44161 wallabot  20   0   30,2g 217112 100488 S   1,3   0,7   0:44.87 spotify  
  10135 wallabot  20   0  826220  58164  41648 S   

Outra maneira de ver isso seria poder filtrar por usuário, ou seja, criar um pipeline e usar o `grep`.

In [191]:
!top | grep wallabot

   1440 wallabot  20   0 4684708 505432 118024 S   6,7   1,5   2:05.92 gnome-s+ 
  25326 wallabot  20   0 1133,0g 527912 123732 S   1,7   1,6   1:31.73 chrome   
   1440 wallabot  20   0 4684708 505476 118024 S   1,3   1,5   2:05.96 gnome-s+ 
   6199 wallabot  20   0 1131,0g 266068 116164 S   0,3   0,8   0:15.23 chrome   
  17606 wallabot  20   0  818228  52096  39488 S   0,3   0,2   0:02.59 gnome-t+ 
  34284 wallabot  20   0   14876   4376   3308 R   0,3   0,0   0:00.02 top


### Manipulador de processo `htop

É semelhante ao `top`, mas mais avançado

Você provavelmente não o tem instalado, portanto, para instalá-lo, digite o comando

``` bash
sudo apt install htop
```

o

``` bash
sudo snap install htop
```

### Manipulador de processos `glances`

É semelhante ao `top`, mas mais avançado

Você provavelmente não o tem instalado, portanto, para instalá-lo, digite o comando

``` bash
sudo apt install glances
```

## Gerenciamento de RAM

Se quisermos obter apenas informações sobre a memória, podemos usar o comando `free`.

In [8]:
!free

              total       usado       libre  compartido búfer/caché  disponible
Memoria:    32774516     6563544    20091804      276296     6119168    25479600
Swap:       2097148           0     2097148


Mas como essas informações não são muito fáceis de digerir, adicionamos o sinalizador `-h` (humano) para facilitar a leitura.

In [9]:
!free -h

              total       usado       libre  compartido búfer/caché  disponible
Memoria:        31Gi       6,3Gi        19Gi       270Mi       5,8Gi        24Gi
Swap:         2,0Gi          0B       2,0Gi


## Gerenciamento do disco rígido

Para obter informações do disco rígido, usamos o comando `du`. Se digitarmos esse comando apenas pelo terminal, ele nos fornecerá as informações de todas as pastas de nossa máquina, portanto, para não obtermos muitas informações, é necessário digitar um caminho que desejamos verificar.

In [10]:
!du ~/Documentos/web/portafolio/posts/

8	/home/wallabot/Documentos/web/portafolio/posts/__pycache__
1648	/home/wallabot/Documentos/web/portafolio/posts/notebooks_translated
4288	/home/wallabot/Documentos/web/portafolio/posts/html_files
336	/home/wallabot/Documentos/web/portafolio/posts/prueba/tocompress
1132	/home/wallabot/Documentos/web/portafolio/posts/prueba
16	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python/__pycache__
28	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python
11232	/home/wallabot/Documentos/web/portafolio/posts/


Como antes, adicionamos o sinalizador `-h` (humano) para facilitar a leitura.

In [11]:
!du ~/Documentos/web/portafolio/posts/ -h

8,0K	/home/wallabot/Documentos/web/portafolio/posts/__pycache__
1,7M	/home/wallabot/Documentos/web/portafolio/posts/notebooks_translated
4,2M	/home/wallabot/Documentos/web/portafolio/posts/html_files
336K	/home/wallabot/Documentos/web/portafolio/posts/prueba/tocompress
1,2M	/home/wallabot/Documentos/web/portafolio/posts/prueba
16K	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python/__pycache__
28K	/home/wallabot/Documentos/web/portafolio/posts/introduccion_python
11M	/home/wallabot/Documentos/web/portafolio/posts/


## Gerenciamento de interface

No Ubuntu, por padrão, inicializamos em uma interface gráfica, mas podemos abrir outras interfaces, que não serão gráficas, digitando `CTRL`+`ALT`+`F<num>`, em que o número pode variar de 1 a 6. Apenas 2 terão a interface gráfica e 1 será o login.

Ao lidar com várias interfaces, talvez não saibamos em qual delas estamos, portanto, digitar o comando `tty` nos informará em qual delas estamos.

In [1]:
!tty

/dev/pts/0


## Manuseio de pacotes

### Repositórios PPA (Personal Package Archives)

No Linux, o gerenciamento de pacotes é feito por meio de repositórios. Essa é uma lista de endereços onde estão localizados os binários de nossos programas. Assim, quando quisermos atualizar ou instalar nossos programas (explicaremos como mais tarde), o que o sistema operacional fará é ver a lista desses repositórios e ir até os endereços indicados para procurar os binários.

Essa lista de repositórios está localizada em `/etc/apt/sources.list` e dentro da pasta `/etc/apt/sources.list.d`. Vamos dar uma olhada nessa lista

In [19]:
terminal("cat /etc/apt/sources.list", max_lines_output=10)

# deb cdrom:[Ubuntu 20.04.2.0 LTS _Focal Fossa_ - Release amd64 (20210209.1)]/ focal main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://es.archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://es.archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://es.archive.ubuntu.com/ubuntu/ focal-updates main restricted
	 ...
deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
# deb-src https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
deb https://apt.kitware.com/ubuntu/ focal main
# deb-src https://apt.kitware.com/ubuntu/ focal main



As primeiras linhas que incluem a palavra `cd-rom` são referências ao cd de instalação, elas sempre vêm com as palavras `deb cdrom:`, mesmo que tenha sido instalado via rede ou usb.

A partir desse ponto, você começa a ver várias linhas que começam com `deb` ou `deb-src`. O `deb` contém os binários e o `deb-src` contém o código-fonte.

Todo endereço de repositório válido tem um desses formatos:

 * deb http://direccion_del_servidor/nombre_carpeta version_name (main ou universe ou multiverse ou main restricted, etc.)
 * deb-src http://direccion_del_servidor/nombre_carpeta nome_da_versão (principal ou universo ou multiverso ou principal restrito, etc.)

Os seis tipos de repositórios do Ubuntu são :
 1. principal

Main é o repositório principal do Ubuntu. O repositório `Main` é ativado por padrão e contém apenas software livre e de código aberto ou `FOSS` (Free and Open Source Software). Todos os softwares fornecidos pelo `Main` podem ser distribuídos livremente e sem restrições.

 2. universo

Assim como o `Main`, o `Universe` também oferece o `FOSS`. A diferença é que, nesse repositório, não é o Ubuntu que garante atualizações de segurança regulares, mas a comunidade que o suporta. Ele é ativado por padrão, mas nem sempre. Alguns sistemas operacionais o têm desativado por padrão e talvez seja necessário ativá-lo se estivermos executando uma Live Session. Se não o tivermos adicionado, podemos fazê-lo com este comando:
    
``` bash
sudo add-apt-repository universe
```

O que encontramos no Universe? Eu diria que a maioria dos softwares que valem a pena, incluindo o VLC ou o OpenShot.

 3. multiverso

Daí vêm os repositórios do Ubuntu com menos liberdade: o `Multiverse` contém software que não é mais `FOSS` e o Ubuntu não pode ativar esse repositório por padrão devido a questões legais e de licenciamento. Por outro lado, ele também não pode fornecer patches e atualizações. Com isso em mente, temos que considerar se devemos adicioná-lo ou não, o que podemos fazer com este comando:

``` bash
sudo add-apt-repository multiverse
```

 4. restrito

Nos repositórios do Ubuntu, podemos encontrar software gratuito e de código aberto, mas isso não é possível quando se trata de hardware. Nos repositórios `Restricted` você encontrará drivers, como os de placas de vídeo, painéis de toque ou placas de rede.

``` bash
sudo add-apt-repository restricted
```

 5. parceiro

Este repositório contém software proprietário compilado pelo Ubuntu a partir de seus parceiros.

 6. repositórios de terceiros do Ubuntu

Por fim, há os repositórios de terceiros. O Ubuntu sempre tenta oferecer a melhor experiência ao usuário e essa é uma das razões pelas quais ele rejeita determinados softwares. Há também desenvolvedores que preferem ter controle total sobre o que oferecem e, portanto, criam seus próprios repositórios.

### Adicionar repositórios

Se estivermos no Ubuntu, poderemos adicionar um repositório usando o comando `add-apt-repository <repositório>`. Mas como em outras distribuições que não o Ubuntu não temos esse comando

### Atualizar repositórios

Usando o comando `apt update`, podemos atualizar as versões mais recentes dos pacotes em nosso repositório.

### Atualizar pacotes

Por meio do comando `apt upgrade`, podemos atualizar os programas que instalamos e cujo repositório foi atualizado anteriormente.

### Atualizar o kernel

O uso do comando `apt dist-upgrade` também atualizará os pacotes do kernel.

 > Cuidado: a atualização dos pacotes do kernel pode resultar em pacotes quebrados

 > Lembrete: ao atualizar os pacotes do kernel, é necessário reiniciar o computador para que a atualização tenha efeito.

### Procurar por pacotes

Com o comando `apt search <package>`, podemos encontrar pacotes

In [5]:
terminal("apt search vlc", max_lines_output=10)

Ordenando...
Buscar en todo el texto...
anacrolix-dms/focal 1.1.0-1 amd64
  Go UPnP DLNA Digital Media Server with basic video transcoding

cubemap/focal 1.4.3-1build1 amd64
  scalable video reflector, designed to be used with VLC

dvblast/focal 3.4-1 amd64
  Simple and powerful dvb-streaming application
	 ...

x264/focal 2:0.155.2917+git0a84d98-2 amd64
  video encoder for the H.264/MPEG-4 AVC standard




### Lista de pacotes instalados

Para ver quais pacotes foram instalados, podemos usar o `dpkg -l`, que nos fornecerá uma lista de todos os pacotes instalados em nosso computador.

In [6]:
terminal("dpkg -l", max_lines_output=10)

Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                     Versión                               Arquitectura Descripción
+++-==========================================-=====================================-============-===========================================================================================================================================================================================================================================================================================================================================================================================================================================
ii  accountsservice                            0.6.55-0ubuntu12~20.04.5              amd64        query and manipulate user account infor

Se quisermos descobrir se temos um pacote instalado, podemos usar o comando acima, criar um `pipe` e procurar o nome do pacote com o `grep`.

In [7]:
terminal("dpkg -l | grep vlc")

Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión      Arquitectura Descripción
+++-==============-============-============-=================================
ii  grep           3.4-1        amd64        GNU grep, egrep and fgrep
ii  vlc            3.0.9.2-1    amd64        multimedia player and streamer



### Instalar pacotes baixados e não de repositórios

Às vezes, quando você deseja instalar um programa, o que eles fazem é fornecer um arquivo `.deb` e, para instalá-lo, usamos o comando `dpkg -i <arquivo.deb>`.

## Administrador do usuário

### Informações do usuário ativo com `id`.

Ao usar o comando `id`, posso ver qual é o meu usuário

In [8]:
!id

uid=1000(wallabot) gid=1000(wallabot) grupos=1000(wallabot),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),998(docker)


Com esse comando, posso ver meu `id`, o `gid` do grupo e os grupos aos quais pertenço. Nas distribuições baseadas no debian, os usuários recebem um id a partir de 1000, enquanto o usuário root recebe o `id` 0.

### Informações do usuário ativo com `whoami`.

Outro comando para descobrir qual é o meu usuário é o `whoami`.

In [9]:
!whoami

wallabot


### Arquivo com as informações de todos os usuários

As informações do usuário estão no arquivo `/etc/passwd`.

In [11]:
terminal("cat /etc/passwd", max_lines_output=10)

root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
	 ...
sshd:x:126:65534::/run/sshd:/usr/sbin/nologin
nvidia-persistenced:x:127:135:NVIDIA Persistence Daemon,,,:/nonexistent:/usr/sbin/nologin
fwupd-refresh:x:128:136:fwupd-refresh user,,,:/run/systemd:/usr/sbin/nologin
glances:x:129:137::/var/lib/glances:/usr/sbin/nologin



### Alterar a senha de um usuário

Se eu quiser alterar a senha de um usuário, preciso usar o comando `passwd <user> <password`; se o usuário não for especificado, ele usará o que o comando `whoami` retornar.

### Criar usuários com `useradd`.

Para criar um novo usuário, use o comando `useradd <nome do usuário>`, vamos criar um novo usuário.

In [11]:
!sudo useradd usertest1

Vamos ver se ele está no arquivo com todos os usuários.

In [1]:
!cat /etc/passwd | grep usertest

usertest1:x:1001:1001::/home/usertest1:/bin/sh


Como podemos ver, o usuário foi criado com o `id` 1001, o próximo ao que meu usuário wallabot tinha, que era o último.

No entanto, ao criar esse usuário, ele não nos pediu para atribuir uma senha. Além disso, se observarmos o que está dentro de `home`

In [2]:
!ls /home

wallabot


Somente a pasta de usuário `wallabot` está lá, mas não a pasta de usuário `test1`.

### Criar usuários com `adduser`.

Portanto, vamos examinar outro comando para criar usuários que solicita uma senha e cria uma pasta em `home`. Esse comando é o `adduser`.

In [11]:
!sudo adduser usertest2

[sudo] contraseña para wallabot: 
Añadiendo el usuario `usertest2' ...
Añadiendo el nuevo grupo `usertest2' (1002) ...
Añadiendo el nuevo usuario `usertest2' (1002) con grupo `usertest2' ...
Creando el directorio personal `/home/usertest2' ...
Copiando los ficheros desde `/etc/skel' ...
Nueva contraseña: 
Vuelva a escribir la nueva contraseña: 
passwd: contraseña actualizada correctamente
Cambiando la información de usuario para usertest2
Introduzca el nuevo valor, o presione INTRO para el predeterminado
	Nombre completo []: 
	Número de habitación []: 
	Teléfono del trabajo []: 
	Teléfono de casa []: 
	Otro []: 
¿Es correcta la información? [S/n] s


Se olharmos o arquivo com todos os usuários

In [3]:
!cat /etc/passwd | grep usertest

usertest1:x:1001:1001::/home/usertest1:/bin/sh
usertest2:x:1002:1002:,,,:/home/usertest2:/bin/bash


Vemos que o usuário `usertest2` foi criado.

In [4]:
!ls /home

usertest2  wallabot


E vemos que foi criada uma pasta para ele em `home`.

Para excluir um usuário, use o comando `userdel <nome do usuário>`.

In [11]:
!sudo userdel usertest1

In [11]:
!sudo userdel usertest2

Vamos ver se eles estão no arquivo com todos os usuários.

In [5]:
!cat /etc/passwd | grep usertest

Vemos que nada mais aparece, na verdade, vemos o fim desse arquivo.

In [17]:
!tail /etc/passwd

geoclue:x:122:127::/var/lib/geoclue:/usr/sbin/nologin
pulse:x:123:128:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin
gnome-initial-setup:x:124:65534::/run/gnome-initial-setup/:/bin/false
gdm:x:125:130:Gnome Display Manager:/var/lib/gdm3:/bin/false
wallabot:x:1000:1000:wallabot,,,:/home/wallabot:/bin/bash
systemd-coredump:x:999:999:systemd Core Dumper:/:/usr/sbin/nologin
sshd:x:126:65534::/run/sshd:/usr/sbin/nologin
nvidia-persistenced:x:127:135:NVIDIA Persistence Daemon,,,:/nonexistent:/usr/sbin/nologin
fwupd-refresh:x:128:136:fwupd-refresh user,,,:/run/systemd:/usr/sbin/nologin
glances:x:129:137::/var/lib/glances:/usr/sbin/nologin


## Crie um usuário administrador

Primeiro, vamos criar um novo usuário, que não será um administrador no início.

In [11]:
!sudo adduser noadmin

Añadiendo el usuario `noadmin' ...
Añadiendo el nuevo grupo `noadmin' (1001) ...
Añadiendo el nuevo usuario `noadmin' (1001) con grupo `noadmin' ...
Creando el directorio personal `/home/noadmin' ...
Copiando los ficheros desde `/etc/skel' ...
Nueva contraseña: 
Vuelva a escribir la nueva contraseña: 
passwd: contraseña actualizada correctamente
Cambiando la información de usuario para noadmin
Introduzca el nuevo valor, o presione INTRO para el predeterminado
	Nombre completo []: 
	Número de habitación []: 
	Teléfono del trabajo []: 
	Teléfono de casa []: 
	Otro []: 
¿Es correcta la información? [S/n] s


Vamos ver em quais grupos o usuário que acabamos de criar está, usando o comando `groups <user>`.

In [6]:
!groups noadmin

noadmin : noadmin


Como podemos ver, ele está apenas no grupo `noadmin`, que é um grupo que foi criado quando o usuário foi criado.

Vamos ver a quais grupos meu usuário pertence

In [7]:
!groups wallabot

wallabot : wallabot adm cdrom sudo dip plugdev lpadmin lxd sambashare docker


Como podemos ver, meu usuário pertence a vários outros grupos, incluindo um chamado `sudo`. Os usuários que têm acesso a esse grupo têm poderes de administrador, portanto, para que o novo usuário que criamos tenha esses poderes, devemos adicioná-lo ao grupo `sudo`.

Para adicionar um usuário a um grupo, há duas maneiras: uma delas é com o comando `gpasswd -a <user> <group>`.

In [11]:
!sudo gpasswd -a noadmin sudo

Añadiendo al usuario noadmin al grupo sudo


Agora vemos a quais grupos o usuário `noadmin` pertence.

In [8]:
!groups noadmin

noadmin : noadmin sudo


Como podemos ver, ele já pertence ao grupo sudo, portanto, já tem poderes de administrador.

Remova o usuário `noadmin` do grupo `sudo` com o comando `gpasswd -d <user> <group>`.

In [7]:
!sudo gpasswd -d noadmin sudo

Eliminando al usuario noadmin del grupo sudo


Vemos que o `noadmin` não pertence mais ao grupo `sudo`.

In [10]:
!groups noadmin

noadmin : noadmin


O segundo comando para adicionar um usuário a um grupo é `usermod -aG <group> <user>`.

In [7]:
!sudo usermod -aG sudo noadmin

Vamos examinar novamente a quais grupos o usuário `noadmin` pertence.

In [11]:
!groups noadmin

noadmin : noadmin sudo


Remova o usuário `noadmin` do grupo `sudo` e exclua-o.

In [7]:
!sudo gpasswd -d noadmin sudo

Eliminando al usuario noadmin del grupo sudo


In [7]:
!sudo userdel noadmin

## Histórico de comandos

### `histórico`

Se digitarmos o comando `history` no terminal, veremos um histórico dos comandos usados.

In [7]:
!history

 1009  docker build . nvidia/cuda
 1010  docker build --help
 1011  docker build --build-arg nvidia/cuda
 1012  docker build --build-arg [nvidia/cuda]
 1013  cd ../docker/
 1014  docker ps -a
 1015  docker rm boring_wescoff 
 1016  docker compose up -d
 1017  docker compose exec deepstream61 bash
 1018  cd ..
    ....
 1996  ps
 1997  ps aux
 1998  camerasIP.sh 
 1999  sudo su
 2000  sudo useradd usertest
 2001  sudo userdel usertest
 2002  sudo useradd usertest
 2003  sudo userdel usertest
 2004  sudo su
 2005  sudo apt install history
 2006  history
 2007  clear
 2008  history


Se quisermos executar um dos comandos no histórico, faremos isso por meio de `!<num comando>`, por exemplo, se eu quiser reexecutar o comando 1996

In [7]:
! !1996

    PID TTY          TIME CMD
   6610 pts/0    00:00:00 bash
  20826 pts/0    00:00:00 ps


### `reverse-i-search`.

Uma maneira mais refinada de pesquisar o histórico é digitar `CTRL`+`r`; ao fazer isso, a seguinte mensagem será exibida no console

In [7]:
!reverse-i-search)`':

Assim, à medida que você digitar, verá comandos que correspondem ao que você digitou; por exemplo, se eu digitar `if`, verei a última vez que usei `ifconfig`.

Ao digitar novamente `CTRL`+`r`, as ocorrências mais antigas serão exibidas.

### Excluir comandos do histórico

Há comandos como `ls`, `cd`, `pwd` que não são muito úteis para constar no histórico, portanto, você pode configurá-los para não serem salvos no histórico. Para fazer isso, modificamos o arquivo `~/.bashrc` e adicionamos a linha `HISTIGNORE="pwd:ls:cd"`.

## Segurança

### Fireward `ufw`

O Ubunut vem com o fireward `ufw` instalado, mas, para verificá-lo, usamos o seguinte comando

In [7]:
!sudo ufw status

Estado: inactivo


Como podemos ver, por padrão ele está inativo, portanto, vamos criar um conjunto de regras. Por exemplo, vamos começar abrindo a porta 22 (SSH), para isso usamos o comando `sudo allow <port> comment "<coment>"`, com o qual abrimos uma porta e adicionamos um comentário

In [7]:
!sudo ufw allow 22 comment 'ssh'

Regla añadida
Regla añadida (v6)


Como podemos ver, você abriu a porta 22 para IPv4 e IPv6. Agora vamos ativar o `ufW` com o comando `ufw enable`.

In [7]:
!sudo ufw enable

El cortafuegos está activo y habilitado en el arranque del sistema


Se quisermos ver as regras que temos no fireward, usaremos o comando `ufw status`.

In [7]:
!sudo ufw enable

Hasta                      Acción      Desde
-----                      ------      -----
22                         ALLOW       Anywhere                   # ssh
22 (v6)                    ALLOW       Anywhere (v6)              # ssh


Também podemos instruí-lo a exibir as regras numeradas com o comando `ufw status numbered`.

In [7]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh
[ 2] 22 (v6)                    ALLOW IN    Anywhere (v6)              # ssh


Como as regras estão numeradas, podemos excluir uma delas usando o comando `ufw delete <número da regra>`; portanto, para excluir a regra para IPv6, fazemos o seguinte

In [7]:
!sudo ufw delete 2

Estado: activo

Borrando:
 allow 22 comment 'ssh'
¿Continuar con la operación (s|n)? s
Regla eliminada (v6)


Analisamos novamente o estado

In [7]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh


Vemos que a regra número 2 foi de fato removida.

Se quisermos ativar a conexão ssh de um único IP, usaremos o sinalizador `from <IP>`.

In [7]:
!sudo ufw  allow from 192.168.1.103 proto tcp to any port 22 comment 'ssh ip'

Regla añadida


Verificamos novamente as regras

In [7]:
!sudo ufw status numbered

Estado: activo

     Hasta                      Acción      Desde
     -----                      ------      -----
[ 1] 22                         ALLOW IN    Anywhere                   # ssh
[ 2] 22/tcp                     ALLOW IN    192.168.1.103              # ssh ip


Se quisermos excluir todas as regras, usaremos o comando `reset`.

In [7]:
!sudo ufw reset

Estado: activo

Reiniciando todas las reglas a sus valores predeterminados instalados.
¿Continuar con la operación (s|n)? s
Respaldando «user.rules» en «/etc/ufw/user.rules.20221205_171730»
Respaldando «before.rules» en «/etc/ufw/before.rules.20221205_171730»
Respaldando «after.rules» en «/etc/ufw/after.rules.20221205_171730»
Respaldando «user6.rules» en «/etc/ufw/user6.rules.20221205_171730»
Respaldando «before6.rules» en «/etc/ufw/before6.rules.20221205_171730»
Respaldando «after6.rules» en «/etc/ufw/after6.rules.20221205_171730»


Verificamos novamente o status

In [7]:
!sudo ufw status numbered

Estado: inactivo


Vemos que não há mais regras

Para desativar o fireward, usamos o comando `ufw disable`.

In [7]:
!sudo ufw disable

El cortafuegos está detenido y deshabilitado en el arranque del sistema


Verificamos novamente o status

In [7]:
!sudo ufw status

Estado: inactivo


### Auditoria de segurança com o `Lynis`.

Para instalar o Lynis, é necessário usar o comando `sudo apt install lynis`.

Para auditar seu sistema, use o comando `lynis audit system`. Esse comando inicia uma varredura de todo o sistema e envia um relatório para você.

 > Não vou mostrar o resultado da verificação do meu sistema para não mostrar minhas vulnerabilidades na Internet.

## Programação de comandos

### Programação de comandos periódicos com o `cron`.

Com o comando `cron`, podemos agendar comandos para serem executados periodicamente. Para fazer isso, precisamos editar o arquivo `/etc/crontab`.

In [22]:
!cat /etc/crontab

# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / &&

Como você pode ver, nesse arquivo há uma série de comandos que são executados periodicamente. O formato desses comandos é o seguinte

```
<minuto> <hora> <dia do mês> <mês> <dia da semana> <usuário> <comando>.
```



Para acertar a data em que você deseja que o comando seja executado, há muitas páginas on-line que o ajudam a escrevê-lo bem, como [crontab guru](https://crontab.guru/).

### Agendamento de comando de execução única com `at`

Quando quisermos que um comando seja executado no futuro, mas não quisermos que ele seja feito periodicamente, mas apenas uma vez, podemos usar o comando `at`. Por exemplo, se você ligar uma máquina do Azure ou da Amazon pela qual está sendo cobrado e quiser ter certeza de que ela será desligada e que você não terá uma surpresa na conta, poderá programá-la para ser desligada à noite. Dessa forma, mesmo que você se esqueça de desligá-la, ela se desligará sozinha.

Fazemos um `ls` na pasta `/tmp`.

In [15]:
!ls -l /tmp

total 60
-rw------- 1 wallabot wallabot    0 sep 24 08:51 config-err-QM3AAe
-rw-r--r-- 1 root     root     2049 sep 24 08:51 glances-root.log
drwx------ 2 wallabot wallabot 4096 sep 24 09:06 pyright-9853-BG3nXEXw0Tao
drwxrwxr-x 3 wallabot wallabot 4096 sep 24 09:06 python-languageserver-cancellation
drwx------ 3 root     root     4096 sep 24 08:51 snap-private-tmp
drwx------ 2 wallabot wallabot 4096 sep 24 08:51 ssh-mHjlSPPoqCp7
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-colord.service-rpjPri
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-fwupd.service-FzPoQf
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-geoclue.service-F6pMWi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-ModemManager.service-Orf6Bi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8

Agora vamos programar a criação de um novo arquivo em `/tmp` em 5 minutos.

In [19]:
!at 09:55 touch /tmp/at.txt

at> touch /tmp/at.txt
at> <EOT>
job 1 at Sun Sep 24 09:55:00 2023


Como podemos ver, temos que escrever `at <time>` e, na linha seguinte, o comando que queremos que seja executado

Agora vamos examinar os arquivos em `/tmp`.

In [20]:
!ls -l /tmp

total 60
-rw-rw-r-- 1 wallabot wallabot    0 sep 24 09:55 at.txt
-rw------- 1 wallabot wallabot    0 sep 24 08:51 config-err-QM3AAe
-rw-r--r-- 1 root     root     2049 sep 24 08:51 glances-root.log
drwx------ 2 wallabot wallabot 4096 sep 24 09:06 pyright-9853-BG3nXEXw0Tao
drwxrwxr-x 3 wallabot wallabot 4096 sep 24 09:06 python-languageserver-cancellation
drwx------ 3 root     root     4096 sep 24 08:51 snap-private-tmp
drwx------ 2 wallabot wallabot 4096 sep 24 08:51 ssh-mHjlSPPoqCp7
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-colord.service-rpjPri
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-fwupd.service-FzPoQf
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-geoclue.service-F6pMWi
drwx------ 3 root     root     4096 sep 24 08:51 systemd-private-371a1d9479324db8bd79b6844b8b589b-ModemManager.service-Orf6Bi
drwx------ 3 root     roo

Como podemos ver, há um `at.txt` que foi criado às 09:55

## Atalhos de teclado

Aqui estão alguns atalhos úteis para usar o terminal
 * Ctrl+a: leva o cursor para o início da linha de comando.
 * Ctrl+e: move o cursor para o final da linha de comando.
 * Ctrl+l: limpa o terminal, semelhante ao que o comando `clear` faz.
 * Ctrl+u: limpa da posição do cursor até o início da linha. Se você estiver no final da linha, ele limpará a linha inteira.
 * Ctrl+k: limpa da posição do cursor até o final da linha. Se você estiver no início, ele limpa a linha inteira.
 * Ctrl+h: faz o mesmo que a tecla backspace, exclui o caractere imediatamente anterior à posição do cursor.
 * Ctrl+w: exclui a palavra imediatamente antes do cursor.
 * Alt+d ou Esc+d: exclui a próxima palavra após o cursor.
 * Ctrl+p: define a linha de comando para o último comando inserido.
 * Ctrl+r: inicia a busca por comandos usados anteriormente, digitando parte de um comando que já foi usado, incluindo opções e parâmetros. Uma pesquisa pressionando a combinação de teclas novamente encontrará correspondências anteriores.
 * Ctrl+c: encerra o processo em execução, útil para recuperar o controle do sistema.
 * Ctrl+d: sai do terminal, semelhante ao comando exit.
 * Ctrl+z: suspende a execução do processo que está em andamento e o coloca em segundo plano; com o comando fg, podemos retomar sua execução.
 * Ctrl+t: troca a posição dos dois caracteres antes do cursor, o que é útil para corrigir erros de digitação.
 * Esc+t: troca a posição das duas palavras antes do cursor, o que é útil para corrigir erros de digitação.
 * Alt+f: move o cursor para o início da próxima palavra na linha, o mesmo que Ctrl+direita no terminal do GNOME.
 * Alt+b: move o cursor para o início da palavra anterior na linha, o mesmo que Ctrl+esquerda no terminal do GNOME.
 * Tabulação: autocompleta comandos ou caminhos para diretórios ou arquivos.
 * Ctrl+Shift+f: abre uma caixa de diálogo para fazer uma pesquisa de texto na saída do terminal.
 * Ctrl+Shift+g: pesquisa a próxima ocorrência da pesquisa anterior no terminal.
 * Ctrl+Shift+h: procura a ocorrência anterior da pesquisa anterior no terminal.
 * Ctrl+Shift+c: copia o texto selecionado do terminal para a área de transferência.
 * Ctrl+Shift+v: cola o texto da área de transferência na linha de comando.
 * Up: define o comando anterior no histórico na linha de comando, assim como Ctrl+p.
 * Down: define a linha de comando para o próximo comando no histórico.
 * Mouse esquerdo: seleciona linhas de texto no terminal.
 * Ctrl+Mouse esquerdo: seleciona blocos de texto do terminal.

## Fricadas

### Você esqueceu de usar o sudo

Já aconteceu com você de usar um comando que deveria ser executado com `sudo`, mas esqueceu de digitar `sudo`? Bem, depois de receber o erro correspondente, se você digitar `sudo !!`, o comando anterior será executado com `sudo`.

In [1]:
!apt update

Leyendo lista de paquetes... Hecho
E: No se pudo abrir el fichero de bloqueo «/var/lib/apt/lists/lock» - open (13: Permiso denegado)
E: No se pudo bloquear el directorio /var/lib/apt/lists/
W: Se produjo un problema al desligar el fichero /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permiso denegado)
W: Se produjo un problema al desligar el fichero /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permiso denegado)


Como você pode ver, a execução do `sudo update` gera um erro, mas se agora executarmos o `sudo !!`, ele executará o `sudo apt update`.

In [2]:
!sudo !!

[sudo] contraseña para wallabot: 


### Mensagens de Kernell

Com o comando `dmesg` (display kernell ring buffer messages), podemos ver as mensagens do kernel. Por exemplo, isso é muito útil para ver se um dispositivo USB está conectado ou para depurar erros de HW em seu computador.

In [5]:
!dmesg | tail

[   35.812312] input: LogiOps Virtual Input as /devices/virtual/input/input33
[   35.916406] input: LogiOps Virtual Input as /devices/virtual/input/input34
[   36.002064] input: LogiOps Virtual Input as /devices/virtual/input/input35
[   63.879806] input: MX Master 3 as /devices/virtual/misc/uhid/0005:046D:B023.0006/input/input36
[   63.879931] logitech-hidpp-device 0005:046D:B023.0006: input,hidraw3: BLUETOOTH HID v0.15 Keyboard [MX Master 3] on 4c:77:cb:1d:66:d0
[   63.902120] logitech-hidpp-device 0005:046D:B023.0006: HID++ 4.5 device connected.
[   69.604899] input: MX Keys Keyboard as /devices/virtual/misc/uhid/0005:046D:B35B.0007/input/input37
[   69.605221] input: MX Keys Mouse as /devices/virtual/misc/uhid/0005:046D:B35B.0007/input/input38
[   69.606204] hid-generic 0005:046D:B35B.0007: input,hidraw4: BLUETOOTH HID v0.13 Keyboard [MX Keys] on 4c:77:cb:1d:66:d0
[  188.285030] input: T9 (AVRCP) as /devices/virtual/input/input40


Com o sinalizador `--follow`, podemos ver em tempo real as novas mensagens que são geradas.

In [7]:
!dmesg --follow

[    0.000000] Linux version 5.15.0-84-generic (buildd@lcy02-amd64-005) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 (Ubuntu 5.15.0-84.93~20.04.1-generic 5.15.116)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-84-generic root=UUID=59002381-d88d-44a6-b83d-8c5a226ce058 ro quiet splash vt.handoff=7
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai  
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000009d01fff] usable
[    0.000000] BIOS-e820: [mem 0x0000000009d02000-0x0000000009ffffff] reserved
[    0.000000] BIOS-

^C


### Informações de hardware

Com o `lshw`, podemos visualizar informações sobre o hardware do nosso computador.

In [10]:
!lshw

AVISO: debería ejecutar este programa como superusuario.
wallabot                    
    descripción: Computer
    anchura: 64 bits
    capacidades: smp vsyscall32
  *-core
       descripción: Motherboard
       id físico: 0
     *-memory
          descripción: Memoria de sistema
          id físico: 0
          tamaño: 32GiB
...
          producto: PnP device PNP0501
          id físico: 6
          capacidades: pnp
          configuración: driver=serial
     *-pnp00:05
          producto: PnP device PNP0c02
          id físico: 7
          capacidades: pnp
          configuración: driver=system
AVISO: la salida puede ser incompleta o imprecisa, debería ejecutar este programa como superusuario.


### Cowsay

Há um comando chamado `cowsay` para o qual você passa como parâmetro um texto e ele desenha uma vaca dizendo esse texto.

É possível que você não o tenha instalado, portanto, para instalá-lo, é necessário digitar o comando

``` bash
sudo apt install cowsay
```

In [12]:
terminal("cowsay MaximoFN")

 __________
< MaximoFN >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||



Se você adicionar o sinalizador `-f dragon`, quem quer que diga que é um dragão.

In [15]:
terminal("cowsay -f dragon MaximoFN")

 __________
< MaximoFN >
 ----------
      \                    / \  //\
       \    |\___/|      /   \//  \\
            /0  0  \__  /    //  | \ \    
           /     /  \/_/    //   |  \  \  
           @_^_@'/   \/_   //    |   \   \ 
           //_^_/     \/_ //     |    \    \
        ( //) |        \///      |     \     \
      ( / /) _|_ /   )  //       |      \     _\
    ( // /) '/,_ _ _/  ( ; -.    |    _ _\.-~        .-~~~^-.
  (( / / )) ,-{        _      `-.|.-~-.           .~         `.
 (( // / ))  '/\      /                 ~-. _ .-~      .-~^-.  \
 (( /// ))      `.   {            }                   /      \  \
  (( / ))     .----~-.\        \-'                 .~         \  `. \^-.
             ///.----..>        \             _ -~             `.  ^-`  ^-_
               ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                  /.-~



In [14]:
terminal("cowsay -f dragon-and-cow MaximoFN")

 __________
< MaximoFN >
 ----------
                       \                    ^    /^
                        \                  / \  // \
                         \   |\___/|      /   \//  .\
                          \  /O  O  \__  /    //  | \ \           *----*
                            /     /  \/_/    //   |  \  \          \   |
                            @___@`    \/_   //    |   \   \         \/\ \
                           0/0/|       \/_ //     |    \    \         \  \
                       0/0/0/0/|        \///      |     \     \       |  |
                    0/0/0/0/0/_|_ /   (  //       |      \     _\     |  /
                 0/0/0/0/0/0/`/,_ _ _/  ) ; -.    |    _ _\.-~       /   /
                             ,-}        _      *-.|.-~-.           .~    ~
            \     \__/        `/\      /                 ~-. _ .-~      /
             \____(oo)           *.   }            {                   /
             (    (--)          .----~-.\        \-`          

## Limpeza

Como a pasta `test` foi criada, nós a excluímos para deixar tudo como encontramos.

In [1]:
!rm -r prueba