# Docker

## Contêineres

Este caderno foi traduzido automaticamente para torná-lo acessível a mais pessoas, por favor me avise se você vir algum erro de digitação..

### Olá mundo

Execute o primeiro contêiner Hello world com o comando `docker run hello-world`.

In [1]:
!docker run hello-world

Unable to find image 'hello-world:latest' locally


latest: Pulling from library/hello-world

85e32844: Pull complete 457kB/2.457kBBDigest: sha256:dcba6daec718f547568c562956fa47e1b03673dd010fe6ee58ca806767031d1c
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.dock

Como não temos o contêiner salvo localmente, o docker faz o download a partir do docker hub. Se agora executarmos o contêiner novamente, a primeira mensagem, indicando que ele está sendo baixado, não será mais exibida.

In [2]:
!docker run hello-world


Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/



Para ver quais contêineres estão em execução, execute `docker ps`.

In [3]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Como podemos ver, não há contêineres abertos. No entanto, se executarmos `docker ps -a` (`all`), veremos que há

In [6]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND    CREATED          STATUS                      PORTS     NAMES
1efb51bbbf38   hello-world   "/hello"   10 seconds ago   Exited (0) 9 seconds ago              strange_thompson
5f5705e7603e   hello-world   "/hello"   15 seconds ago   Exited (0) 14 seconds ago             laughing_jang


Vemos que aparecem dois contêineres chamados `hello-world`, que são os dois que executamos anteriormente. Portanto, toda vez que executamos o comando `run`, o docker cria um novo contêiner, não executa um que já existe.

Se quisermos obter mais informações sobre um dos dois contêineres, podemos executar `docker inspect <id>`, em que `<id>` corresponde ao ID do contêiner mostrado na lista acima.

In [7]:
!docker inspect 1efb51bbbf38

[
    {
        "Id": "1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e",
        "Created": "2023-09-04T03:59:17.795499354Z",
        "Path": "/hello",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-09-04T03:59:18.406663026Z",
            "FinishedAt": "2023-09-04T03:59:18.406181184Z"
        },
        "Image": "sha256:9c7a54a9a43cca047013b82af109fe963fde787f63f9e016fdc3384500c2823d",
        "ResolvConfPath": "/var/lib/docker/containers/1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e/hostname",
        "HostsPath": "/var/lib/docker/containers/1efb

Como lembrar os IDs é complicado para nós, o docker atribui nomes aos contêineres para facilitar nossa vida. Assim, na lista acima, a última coluna corresponde ao nome que o docker atribuiu a cada contêiner, portanto, se agora executarmos `docker inspect <name>`, obteremos as mesmas informações que com o ID

Executo novamente o `docker ps -a` para ver a lista novamente

In [8]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS                     PORTS     NAMES
1efb51bbbf38   hello-world   "/hello"   2 minutes ago   Exited (0) 2 minutes ago             strange_thompson
5f5705e7603e   hello-world   "/hello"   2 minutes ago   Exited (0) 2 minutes ago             laughing_jang


E agora executo `docker inspect <name>` para ver as informações do contêiner.

In [9]:
!docker inspect strange_thompson

[
    {
        "Id": "1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e",
        "Created": "2023-09-04T03:59:17.795499354Z",
        "Path": "/hello",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-09-04T03:59:18.406663026Z",
            "FinishedAt": "2023-09-04T03:59:18.406181184Z"
        },
        "Image": "sha256:9c7a54a9a43cca047013b82af109fe963fde787f63f9e016fdc3384500c2823d",
        "ResolvConfPath": "/var/lib/docker/containers/1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1efb51bbbf38917affd1b5871db8e658ebfe0b2efa5ead17545680b7866f682e/hostname",
        "HostsPath": "/var/lib/docker/containers/1efb

Mas por que com o `docker ps` não vemos nenhum contêiner e com o `docker ps -a` vemos. Isso ocorre porque o `docker ps` mostra apenas os contêineres em execução, enquanto o `docker ps -a` mostra todos os contêineres, em execução e desligados.

Podemos criar um contêiner atribuindo um nome a ele usando o comando `docker run --name <name> hello-world`.

In [10]:
!docker run --name hello_world hello-world


Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/



Isso será mais conveniente para nós, pois poderemos controlar os nomes dos contêineres por conta própria.

Se agora quisermos criar outro contêiner com o mesmo nome, não será possível, pois o docker não permite nomes de contêineres duplicados. Portanto, se quisermos renomear o contêiner, podemos usar o comando `docker rename <old name> <new name>`.

In [11]:
!docker rename hello_world hello_world2

Agora temos vários contêineres iguais. Portanto, se quisermos excluir qualquer um deles, teremos que usar o comando `docker rm <id>` ou `docker rm <name>`.

In [12]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS                     PORTS     NAMES
f432c9c2ca21   hello-world   "/hello"   9 seconds ago   Exited (0) 8 seconds ago             hello_world2
1efb51bbbf38   hello-world   "/hello"   4 minutes ago   Exited (0) 4 minutes ago             strange_thompson
5f5705e7603e   hello-world   "/hello"   4 minutes ago   Exited (0) 4 minutes ago             laughing_jang


In [13]:
!docker rm hello_world2

hello_world2


Se olharmos a lista de contêineres novamente, o contêiner `hello_world2` não está mais lá.

In [14]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS                     PORTS     NAMES
1efb51bbbf38   hello-world   "/hello"   5 minutes ago   Exited (0) 5 minutes ago             strange_thompson
5f5705e7603e   hello-world   "/hello"   5 minutes ago   Exited (0) 5 minutes ago             laughing_jang


Se quisermos excluir todos os contêineres, podemos fazer isso um a um, mas como é muito pesado, podemos excluir todos eles usando o comando `docker container prune`. Esse comando exclui apenas os contêineres que estão parados.

In [17]:
!docker container prune

WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y

O Docker pergunta se você tem certeza e, se você disser que sim, ele exclui todos eles. Se agora você listar todos os contêineres, nenhum deles aparecerá

In [19]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


### Modo iterativo

Vamos executar o ubuntu usando o comando `docker run ubuntu`.

In [29]:
!docker run ubuntu

Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu

Digest: sha256:20fa2d7bb4de7723f542be5923b06c4d704370f0390e4ae9e1c833c8785644c1[1A
Status: Downloaded newer image for ubuntu:latest


Como podemos ver agora, o download demorou mais. Se listarmos os contêineres usando o comando `docker ps`, veremos que o contêiner que acabamos de criar não aparece, ou seja, não está em execução.

In [30]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Agora listamos todos os contêineres

In [31]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED         STATUS                     PORTS     NAMES
da16b3a85178   ubuntu    "bash"    4 seconds ago   Exited (0) 3 seconds ago             hardcore_kare


Vemos que o estado do contêiner é `Exited (0)`.

Se olharmos para o comando do contêiner, `bash` aparece e, ao lado do status `Exited (0)`, ele nos diz que o Ubuntu foi iniciado, executou seu *bash*, terminou a execução e retornou um 0. Isso acontece porque o bash do Ubuntu não foi informado sobre o que fazer. Para resolver isso, agora vamos executar o contêiner usando o comando `docker run -it ubuntu`, com `it` o que estamos dizendo é que queremos executá-lo no modo iterativo.

In [31]:
!docker run -it ubuntu

root@5b633e9d838f:/#

Agora vemos que estamos dentro do bash do Ubuntu. Se executarmos o comando `cat /etc/lsb-release`, poderemos ver a distribuição do Ubuntu

In [31]:
!root@5b633e9d838f:/# cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

Se abrirmos outro terminal e olharmos a lista de contêineres, agora aparecerá o contêiner que está executando o Ubuntu.

In [35]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED         STATUS         PORTS     NAMES
5b633e9d838f   ubuntu    "bash"    3 minutes ago   Up 3 minutes             funny_mirzakhani


Vemos o contêiner com o Ubuntu e, em seu status, podemos ver `UP`.

Se olharmos agora para a lista de todos os contêineres, veremos que os dois contêineres com o Ubuntu aparecem, o primeiro desligado e o segundo em execução

In [36]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED         STATUS                     PORTS     NAMES
5b633e9d838f   ubuntu    "bash"    3 minutes ago   Up 3 minutes                         funny_mirzakhani
da16b3a85178   ubuntu    "bash"    3 minutes ago   Exited (0) 3 minutes ago             hardcore_kare


Se voltarmos ao terminal onde tínhamos o Ubuntu em execução dentro de uma janela de encaixe, digitar ``exit`` encerrará o Ubuntu.

In [36]:
!root@5b633e9d838f:/# exit

exit

Se executarmos o ``docker ps``, o contêiner não aparecerá mais.

In [37]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Mas se eu executar o ``docker ps -a``, ele aparecerá. Isso significa que o contêiner está desligado

In [38]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED         STATUS                      PORTS     NAMES
5b633e9d838f   ubuntu    "bash"    4 minutes ago   Exited (0) 27 seconds ago             funny_mirzakhani
da16b3a85178   ubuntu    "bash"    4 minutes ago   Exited (0) 4 minutes ago              hardcore_kare


Isso acontece porque quando digitamos ``exit``, na verdade estamos digitando no console do Ubuntu bash, o que significa que estamos encerrando o processo do Ubuntu bash.

### Ciclo de vida de um contêiner

No docker, quando o processo principal de um contêiner termina, o contêiner é encerrado. Vários processos podem ser executados dentro de um contêiner, mas somente quando o processo principal termina é que o contêiner é encerrado.

Portanto, se quisermos executar um contêiner que não seja encerrado quando um processo for encerrado, devemos fazer com que seu processo principal não seja encerrado. Nesse caso, não encerre o bash

Se quisermos executar um contêiner com o ubuntu, mas não encerrá-lo quando o processo bash terminar, podemos fazer isso da seguinte maneira

In [39]:
!docker run --name alwaysup -d ubuntu tail -f /dev/null

ce4d60427dcd4b326d15aa832b816c209761d6b4e067a016bb75bf9366c37054


Primeiro, damos a ele o nome ``alwaysup``, depois passamos a opção ``-d`` (``detach``) para fazer com que o contêiner seja executado em segundo plano e, por fim, informamos o processo principal que queremos executar no contêiner, que nesse caso é ``tail -f /dev/null``, o que equivale a um comando ``nop``.

Isso retornará o ID do contêiner, mas não estaremos dentro do ubuntu como antes.

Se olharmos agora para a lista de contêineres em execução, o contêiner que acabamos de criar será exibido

In [40]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS          PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   18 seconds ago   Up 17 seconds             alwaysup


Como já temos um contêiner em execução o tempo todo, podemos nos conectar a ele usando o comando ``exec``. Informamos a ele o nome ou ID do contêiner e passamos o processo que queremos executar. Também passamos a opção ``-it`` para dizer a ele que deve ser iterativo.

In [40]:
!docker exec -it alwaysup bash

root@ce4d60427dcd:/#

Agora estamos de volta ao Ubuntu. Se executarmos o comando ``ps -aux``, poderemos ver uma lista dos processos em execução no Ubuntu.

In [40]:
!ps -aux

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2820  1048 ?        Ss   13:04   0:00 tail -f /dev/null
root           7  0.0  0.0   4628  3796 pts/0    Ss   13:04   0:00 bash
root          15  0.0  0.0   7060  1556 pts/0    R+   13:05   0:00 ps -aux

Vemos apenas três processos, o ``ps -aux``, o ``bash`` e o ``tail -f /dev/null``.

Esse contêiner estará sempre ativo enquanto o processo ``tail -f /dev/null`` estiver em execução.

Se sairmos do contêiner com o comando ``exit`` e executarmos o comando ``docker ps``, veremos que o contêiner ainda está ativo.

In [40]:
!exit

exit

In [41]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED         STATUS         PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   2 minutes ago   Up 2 minutes             alwaysup


Para encerrar o processo e fechar o contêiner, devemos usar o comando ``docker stop <name>``.

In [53]:
!docker stop alwaysup

alwaysup


Se agora listarmos novamente os contêineres ativados, o contêiner com o Ubuntu não aparecerá mais.

In [54]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


E se listarmos todos os contêineres, veremos o contêiner com o Ubuntu e seu status ``Exited``.

In [55]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS                            PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   14 minutes ago   Exited (137) About a minute ago             alwaysup
5b633e9d838f   ubuntu    "bash"                19 minutes ago   Exited (0) 15 minutes ago                   funny_mirzakhani
da16b3a85178   ubuntu    "bash"                20 minutes ago   Exited (0) 20 minutes ago                   hardcore_kare


### Recipientes de uso único

Se definirmos a opção `--rm` ao executar um contêiner, esse contêiner será excluído quando terminar de ser executado.

In [77]:
!docker run --rm --name autoremove ubuntu:latest

Se olharmos agora para os contêineres que temos

In [79]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Vemos que o contêiner que acabamos de criar está faltando.

### Expondo contêineres ao mundo externo

Vamos criar um novo contêiner com um servidor

In [56]:
!docker run -d --name proxy nginx

Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx

f1ad4ce1: Pulling fs layer 
b079d0f8: Pulling fs layer 
5fbbebc6: Pulling fs layer 
ffdd25f4: Pulling fs layer 
32c8fba2: Pulling fs layer 
24b8ba39: Pull complete 393kB/1.393kBB[5ADigest: sha256:2888a97f7c7d498bbcc47ede1ad0f6ced07d72dfd181071dde051863f1f79d7b
Status: Downloaded newer image for nginx:latest
1a530e04f14be082811b72ea8b6ea5a95dad3037301ee8a1351a0108ff8d3b30


Isso cria um servidor, vamos listar novamente os contêineres que estão em execução

In [57]:
!docker ps

CONTAINER ID   IMAGE     COMMAND                  CREATED        STATUS                  PORTS     NAMES
1a530e04f14b   nginx     "/docker-entrypoint.…"   1 second ago   Up Less than a second   80/tcp    proxy


Agora, uma nova coluna aparece com a porta e nos informa que o servidor que acabamos de criar está na porta ``80`` sob o protocolo ``tcp``.

Se abrirmos um navegador e tentarmos nos conectar ao servidor via ``http://localhost:80``, não conseguiremos nos conectar. Isso ocorre porque cada contêiner tem sua própria interface de rede. Ou seja, o servidor está escutando na porta ``80`` do contêiner, mas estamos tentando nos conectar à porta ``80`` do host.

Paramos o contêiner para relançá-lo de outra forma

In [58]:
!docker stop proxy

proxy


Se listarmos os contêineres, ele não aparecerá em execução

In [59]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Nós o excluímos para recriá-lo

In [60]:
!docker rm proxy

proxy


Se listarmos todos os contêineres, não será mais

In [61]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS                       PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   19 minutes ago   Exited (137) 5 minutes ago             alwaysup
5b633e9d838f   ubuntu    "bash"                24 minutes ago   Exited (0) 20 minutes ago              funny_mirzakhani
da16b3a85178   ubuntu    "bash"                24 minutes ago   Exited (0) 24 minutes ago              hardcore_kare


Para recriar o contêiner com o servidor e poder vê-lo a partir do host, precisamos usar a opção ``-p`` (``publish``), indicando primeiro a porta na qual queremos vê-lo no host e, em seguida, a porta do contêiner, ou seja, ``-p <ip host>:<ip conteiner>``.

In [62]:
!docker run -d --name proxy -p 8080:80 nginx

c199235e42f76a30266f6e1af972e0a59811806eb3d3a9afdd873f6fa1785eae


Listamos os contêineres

In [63]:
!docker ps

CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS                                   NAMES
c199235e42f7   nginx     "/docker-entrypoint.…"   22 seconds ago   Up 21 seconds   0.0.0.0:8080->80/tcp, :::8080->80/tcp   proxy


Vemos que a porta do contêiner é `0.0.0.0.0:8080->80/tcp`. Se agora formos a um navegador e digitarmos `0.0.0.0.0:8080`, poderemos acessar o servidor de contêineres.

Ao listar os contêineres, a coluna ``PORTS`` indica ``0.0.0.0.0:8080->80/tcp``, o que nos ajuda a ver a relação entre as portas.

Para visualizar os logs do contêiner, usando o comando ``docker logs <name>``, posso visualizar os logs do contêiner.

In [64]:
!docker logs proxy

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/09/13 13:24:06 [notice] 1#1: using the "epoll" event method
2022/09/13 13:24:06 [notice] 1#1: nginx/1.23.1
2022/09/13 13:24:06 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2022/09/13 13:24:06 [notice] 1#1: OS: Linux 5.15.0-46-generic
2022/09/13 13:24:06 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576

Agora posso ver todas as solicitações que foram feitas ao servidor. Mas se eu quiser ver os logs em tempo real, posso usar ``docker logs -f <name>``.

In [64]:
!docker logs -f proxy

Agora posso visualizar os registros em tempo real. Para sair, digite ``CTRL+C``.

Como pode haver um momento em que há muitos logs, se você quiser apenas os logs mais recentes, usando a opção ``--tail <num>`` posso ver os logs mais recentes ``<num>``. Se eu adicionar a opção ``-f``, sempre veremos os últimos registros ``<num>``.

In [65]:
!docker logs --tail 10 proxy

2022/09/13 13:24:06 [notice] 1#1: start worker process 41
2022/09/13 13:24:06 [notice] 1#1: start worker process 42
172.17.0.1 - - [13/Sep/2022:13:24:16 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\x01E\x14\x8E\xB6\x0BEg\xF3\xC9\x9A\x19\x9C\xCA\xEC\xA7y#3\x92\x05\x95\xDCQ\x07\x19\x1D\xEF\xEA$\xBF# \x0B\x83\xF7-,s\x1B!r\xEA|\xAE\xDF\xA1\x9DLZ\xAA4y\xB3t\xAB\xC0\xCE_\xB8\xE7\xFF'\xCF\x86\x00 \xEA\xEA\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x8A\x8A\x00\x00\x00\x00\x00\x0E\x00\x0C\x00\x00\x09localhost\x00\x17\x00\x00\xFF\x01\x00\x01\x00\x00" 400 157 "-" "-" "-"
172.17.0.1 - - [13/Sep/2022:13:24:16 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03}\xA9Dr{\x8C;\x90z\x82\xAD\xBC\x8Az\xC2x\xDF\x1E\x9A\xE6l?\xA7\xE0DoK\x91'g\xBB\xB5 %\xBB\xFD\xD9\x82?\xDB\x80\xB3T\xF6cJ\xF7\xE5\xC2\xD2\x11\xBC\xA2\x1F\x90\x14\xA3\xEB\xBD=R\xBC\x83\x89\x85\x00 \xCA\xCA\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\

Se também adicionarmos a opção `-t`, poderemos ver a data e a hora de cada registro, portanto, se tivermos um problema, poderemos saber quando ele ocorreu.

In [ ]:
!docker logs --tail -t 10 proxy

2022-09-13T13:24:06.573362728Z 2022/09/13 13:24:06 [notice] 1#1: start worker process 41
2022-09-13T13:24:06.651127107Z 2022/09/13 13:24:06 [notice] 1#1: start worker process 42
2022-09-13T13:24:16.651160189Z 172.17.0.1 - - [13/Sep/2022:13:24:16 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\x01E\x14\x8E\xB6\x0BEg\xF3\xC9\x9A\x19\x9C\xCA\xEC\xA7y#3\x92\x05\x95\xDCQ\x07\x19\x1D\xEF\xEA$\xBF# \x0B\x83\xF7-,s\x1B!r\xEA|\xAE\xDF\xA1\x9DLZ\xAA4y\xB3t\xAB\xC0\xCE_\xB8\xE7\xFF'\xCF\x86\x00 \xEA\xEA\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\x8A\x8A\x00\x00\x00\x00\x00\x0E\x00\x0C\x00\x00\x09localhost\x00\x17\x00\x00\xFF\x01\x00\x01\x00\x00" 400 157 "-" "-" "-"
2022-09-13T13:24:16.116817914Z 172.17.0.1 - - [13/Sep/2022:13:24:16 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03}\xA9Dr{\x8C;\x90z\x82\xAD\xBC\x8Az\xC2x\xDF\x1E\x9A\xE6l?\xA7\xE0DoK\x91'g\xBB\xB5 %\xBB\xFD\xD9\x82?\xDB\x80\xB3T\xF6cJ\xF7\xE5\xC2\xD2

Paramos e excluímos o contêiner

In [71]:
!docker rm -f proxy

proxy


In [72]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS                        PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   26 minutes ago   Exited (137) 13 minutes ago             alwaysup
5b633e9d838f   ubuntu    "bash"                31 minutes ago   Exited (0) 27 minutes ago               funny_mirzakhani
da16b3a85178   ubuntu    "bash"                32 minutes ago   Exited (0) 32 minutes ago               hardcore_kare


## Dados no Docker

### Montarias vinculadas

Vamos dar uma olhada nos contêineres que estão parados

In [73]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS                        PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   26 minutes ago   Exited (137) 13 minutes ago             alwaysup
5b633e9d838f   ubuntu    "bash"                31 minutes ago   Exited (0) 28 minutes ago               funny_mirzakhani
da16b3a85178   ubuntu    "bash"                32 minutes ago   Exited (0) 32 minutes ago               hardcore_kare


Vamos excluir os dois do ubuntu em que seu comando principal é bash e vamos deixar o que deixamos sem operação

In [75]:
!docker rm funny_mirzakhani

funny_mirzakhani


In [76]:
!docker rm hardcore_kare

hardcore_kare


In [77]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS                        PORTS     NAMES
ce4d60427dcd   ubuntu    "tail -f /dev/null"   27 minutes ago   Exited (137) 14 minutes ago             alwaysup


Vamos reiniciar o contêiner do Ubuntu que nos resta, o que é feito usando o comando `start

In [78]:
!docker start alwaysup

alwaysup


Voltamos ao assunto

In [78]:
!docker exec -it alwaysup bash

root@ce4d60427dcd:/#


No contêiner, posso criar uma nova pasta chamada ``dockerfolder``.

In [78]:
!mkdir dockerfolder

Se listarmos os arquivos, a nova pasta será exibida.

In [78]:
!ls

bin  boot  dev  dockerfolder  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

Se sairmos do contêiner

In [78]:
!exit

exit

E nós o excluímos

In [79]:
!docker rm -f alwaysup

alwaysup


Se listarmos todos os contêineres, o último que criamos não será mais exibido.

In [81]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


Vamos refazer tudo, mas primeiro vamos criar uma pasta no host onde compartilharemos os dados com o contêiner.

In [82]:
!mkdir dockerHostFolder

Vemos que não há nada dentro da pasta.

In [83]:
!ls dockerHostFolder

Agora temos nossa rota absoluta

In [84]:
!pwd

/home/wallabot/Documentos/web/portafolio/posts


Recriamos o contêiner, mas adicionamos a opção ``-v`` (``bind mount``). Em seguida, adicione o caminho absoluto da pasta do host e o caminho absoluto da pasta no contêiner, ``-v <caminho do host>:<caminho do contêiner>``.

In [87]:
!docker run -d --name alwaysup -v ~/Documentos/web/portafolio/posts/dockerHostFolder:/dockerContainerFolder ubuntu tail -f /dev/null

4ede4512c293bdcc155e9c8e874dfb4a28e5163f4d5c7ddda24ad2863f28921b


Entramos no contêiner, listamos os arquivos e a pasta que criamos é exibida.

In [87]:
!docker exec -it alwaysup bash

root@4ede4512c293:/#

In [87]:
root@4ede4512c293:/# ls

bin   dev                    etc   lib    lib64   media  opt   root  sbin  sys  usr
boot  dockerContainerFolder  home  lib32  libx32  mnt    proc  run   srv   tmp  var


Vamos para o diretório do contêiner que compartilhamos, criamos um arquivo e saímos do contêiner.

In [87]:
root@4ede4512c293:/# cd dockerContainerFolder

In [87]:
root@4ede4512c293:/dockerContainerFolder# touch bindFile.txt

In [87]:
root@4ede4512c293:/dockerContainerFolder# exit

exit

Vemos o que está dentro da pasta compartilhada

In [88]:
!ls dockerHostFolder

bindFile.txt


Além disso, se excluirmos o contêiner, o arquivo ainda estará lá.

In [89]:
!docker rm -f alwaysup

alwaysup


In [90]:
!ls dockerHostFolder

bindFile.txt


Se eu recriar um contêiner compartilhando as pastas, todos os arquivos estarão no contêiner.

In [91]:
!docker run -d --name alwaysup -v ~/Documentos/web/portafolio/posts/dockerHostFolder:/dockerContainerFolder ubuntu tail -f /dev/null

6c021d37ea29d8b23fe5cd4968baa446085ae1756682f65340288b4c851c362d


In [91]:
!docker exec -it alwaysup bash

root@6c021d37ea29:/#

In [91]:
!root@6c021d37ea29:/# ls dockerContainerFolder/

bindFile.txt:/#

Removemos o contêiner

In [92]:
!docker rm -f alwaysup

alwaysup


In [93]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


### Volumes

Os volumes foram criados como uma evolução do ``bind mounts`` para oferecer mais segurança. Podemos listar todos os volumes do docker usando ``docker volume ls``.

In [1]:
!docker volume ls

DRIVER    VOLUME NAME


Vamos criar um novo volume para o contêiner do ubuntu, usando o comando ``docker volume create <volume name>``.

In [2]:
!docker volume create ubuntuVolume

ubuntuVolume


Se listarmos os volumes novamente, aparecerá o que acabamos de criar.

In [3]:
!docker volume ls

DRIVER    VOLUME NAME
local     ubuntuVolume


No entanto, ele não aparece como uma pasta no sistema de arquivos do host. Com `ls -d */`, listamos todas as pastas

In [7]:
!ls -d */

dockerHostFolder/  __pycache__/


Vamos criar um contêiner novamente, mas agora vamos criá-lo com o volume que acabamos de criar com a opção ``--mount``, indicando o volume de origem por ``src=<nome do volume>` (se o volume não existir, o docker o criará), depois o destino separado por ``,``, ``dst=<caminho do contêiner>`, ou seja, ``--mount src=<nome do volume>,dst=<caminho do contêiner>``.

In [8]:
!docker run -d --name alwaysup --mount src=ubuntuVolume,dst=/dockerVolumeFolder ubuntu tail -f /dev/null

42cdcddf4e46dc298a87b0570115e0b2fc900cb4c6db5eea22a61409b8cb271d


Após a criação, podemos visualizar os volumes do contêiner usando o comando ``inspect`` e filtrando por `'{{.Mounts}}'`.

````bash
$ docker inspect --format '{{.Mounts}}' alwaysup
[
    {
        volume ubuntuVolume /var/lib/docker/volumes/ubuntuVolume/_data /dockerVolumeFolder local z true
    }

```

Vemos que o volume se chama `ubuntuVolume` e também podemos ver o caminho onde ele está armazenado, nesse caso em `/var/lib/docker/volumes/ubuntuVolume/_data`. Fazemos o mesmo que antes, entramos no contêiner, criamos um arquivo no caminho do volume, saímos e vemos no host se ele foi criado.

````bash
$ docker exec -it alwaysup bash
root@42cdcdcddf4e46:/# touch dockerVolumeFolder/volumeFile.txt
root@42cdcdcddf4e46:/# exit
```


````bash
$ sudo ls /var/lib/docker/volumes/ubuntuVolume/_data
volumeFile.txt
```

O arquivo é criado

### Inserção e extração de arquivos de um contêiner

Primeiro, criaremos um arquivo que queremos copiar para um contêiner.

In [14]:
!touch dockerHostFolder/text.txt

Entramos no contêiner

````bash
$ docker exec -it alwaysup bash
root@42cdcdcddf4e46:/#
```

Criamos uma nova pasta na qual copiaremos o arquivo e saímos

````bash
root@42cdcdcddf4e46:/# mkdir folderToCopy
root@42cdcdcddf4e46:/# ls
bin boot dev dockerVolumeFolder etc folderToCopy home lib lib32 lib64 libx32 libx32 media mnt opt proc root run sbin srv sys tmp usr var
root@42cdcdcddf4e46:/# exit
saída
```

Copiamos o arquivo dentro do contêiner usando o comando ``cp``, indicando o arquivo que queremos copiar, o contêiner onde queremos copiá-lo e o caminho dentro do contêiner, ``docker cp <arquivo> <contêiner>:<caminho do contêiner>``.

In [15]:
!docker cp dockerHostFolder/text.txt alwaysup:/folderToCopy

Entramos novamente no contêiner e verificamos se o arquivo está lá.

````bash
$ docker exec -it alwaysup bash
root@42cdcdcddf4e46:/# ls folderToCopy/
text.txt
```

Saímos do contêiner

````bash
/# saída
saída
```

Agora vamos extrair o arquivo do contêiner e salvá-lo no host com outro nome, para isso usamos o comando ``cp`` novamente, mas indicando agora o contêiner, o caminho do arquivo no contêiner e o caminho e o nome do arquivo que queremos que tenha no host, ``docker cp <container>:<docker file path> <host file path>``.

In [16]:
!docker cp alwaysup:/folderToCopy/text.txt dockerHostFolder/fileExtract.txt

Vimos que você está no host

In [17]:
!ls dockerHostFolder

bindFile.txt  fileExtract.txt  text.txt


Mesmo que o contêiner esteja parado, os arquivos também podem ser copiados.

Por fim, excluímos o contêiner

In [8]:
!docker rm -f alwaysup

alwaysup


## Imagens

### Conceitos fundamentais

As imagens são os arquivos ("modelos") com toda a configuração para criar um contêiner. Toda vez que criamos um contêiner, ele é criado a partir de uma imagem. Quando criamos novos contêineres, na primeira vez recebemos uma mensagem dizendo que não tínhamos a imagem e que iríamos baixá-la. No docker hub, há muitas imagens com todos os tipos de máquinas, mas, para um ambiente de desenvolvimento muito específico, podemos criar nosso próprio modelo para passá-lo a outra pessoa e ela trabalhará em um contêiner com a mesma configuração que a nossa.

Podemos ver todas as imagens que salvamos em nosso computador usando o comando ``docker image ls``.

In [1]:
!docker image ls

REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
nginx         latest    2d389e545974   8 hours ago     142MB
ubuntu        latest    2dc39ba059dc   11 days ago     77.8MB
hello-world   latest    feb5d9fea6a5   11 months ago   13.3kB


Podemos ver os tamanhos e podemos ver como o `nginx` ocupa muito espaço e é por isso que o download demorou mais do que os demais.

Outra coluna que podemos ver é a coluna ``TAG``, que indica a versão da imagem. Em todas elas está escrito ``latest``, o que significa que é a mais recente. Ou seja, no momento do download, baixamos a versão mais recente no docker hub. Isso não é o ideal em um ambiente de desenvolvimento, pois podemos baixar uma imagem do Ubuntu e, se não especificarmos uma versão, ela baixará a mais recente, por exemplo, 20.04. Mas, depois de algum tempo, alguém pode querer desenvolver com você e baixar essa imagem, mas, se não especificar a versão, ele baixará novamente a mais recente, que, no seu caso, pode ser a 22.04. Isso pode gerar problemas e coisas que uma pessoa trabalha e a outra não.

Você pode ver todas as imagens no hub do docker acessando ``https://hub.docker.com/``. Lá, você pode pesquisar a imagem que melhor se adapta ao projeto que deseja realizar. Se navegarmos até a imagem do Ubuntu, por exemplo, poderemos ver as versões (`tags`) das imagens.

Vamos fazer o download, **mas não executar**, de uma imagem. Para fazer isso, usamos o comando ``docker pull <hub> <nome da imagem>:<tag>``. Se não especificarmos o hub, o download será feito a partir do hub padrão do docker, mas podemos especificar outro, por exemplo, um hub privado de nossa organização. Além disso, se não especificarmos a tag, ele fará o download da versão mais recente por padrão.

In [2]:
!docker pull ubuntu:20.04

20.04: Pulling from library/ubuntu

Digest: sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16[1A
Status: Downloaded newer image for ubuntu:20.04
docker.io/library/ubuntu:20.04


Se listarmos as imagens novamente, veremos que agora temos duas imagens do ubuntu, uma com a tag ``20.04`` e outra com a tag ``latest``.

In [3]:
!docker image ls

REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
nginx         latest    2d389e545974   8 hours ago     142MB
ubuntu        latest    2dc39ba059dc   11 days ago     77.8MB
ubuntu        20.04     a0ce5a295b63   11 days ago     72.8MB
hello-world   latest    feb5d9fea6a5   11 months ago   13.3kB


### Criar imagens usando o `Dockerfile`.

Criamos um diretório no host chamado ``dockerImages`` para trabalhar no

In [15]:
!mkdir dockerImages

Criamos um ``Dockerfile`` com o qual criaremos uma imagem.

In [16]:
!touch dockerImages/Dockerfile

Abra o arquivo criado com seu editor preferido e digite o seguinte:

````Dockerfile
DE ubuntu:latest
```

Isso diz ao docker para criar a imagem a partir da imagem "mais recente" do Ubuntu.

Em seguida, escrevemos um comando a ser executado no momento da compilação

```DOckerfile
RUN touch /test.txt
```

Isso significa que, quando o `Dockefile` for compilado, esse comando será executado, mas não quando o contêiner de imagem for executado.

No final, o `Dockerfile` tem a seguinte aparência:
````dockerfile
    DE ubuntu:latest
    RUN touch /test.txt
```

Compilamos o `Dockerfile` usando o comando `build`, com a opção `-t` podemos dar a ele uma `tag`. Por fim, temos que fornecer o caminho para o contexto `build`, o que explicaremos mais tarde.

In [21]:
!docker build -t ubuntu:test ./dockerImages

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu:latest
 ---> 2dc39ba059dc
Step 2/2 : RUN touch /test.txt
 ---> Using cache
 ---> a78cf3ea16d8
Successfully built a78cf3ea16d8
Successfully tagged ubuntu:test

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Como podemos ver, ele é compilado em duas etapas, cada uma com um `id`, e cada um desses `id` são camadas da imagem, como veremos mais adiante.

Voltamos às imagens que salvamos em nosso computador e a que acabamos de criar aparece.

In [10]:
!docker image ls

REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
ubuntu        test      a78cf3ea16d8   8 minutes ago   77.8MB
nginx         latest    2d389e545974   8 hours ago     142MB
ubuntu        latest    2dc39ba059dc   11 days ago     77.8MB
ubuntu        20.04     a0ce5a295b63   11 days ago     72.8MB
hello-world   latest    feb5d9fea6a5   11 months ago   13.3kB


Executamos o contêiner a partir da imagem que acabamos de criar.

````bash
$ docker run -it ubuntu:test
root@b57b9d4eedeb:/#
```

Entramos no bash do contêiner. Como dissemos, o comando RUN foi executado no momento da compilação da imagem, portanto, o arquivo que pedimos para ser criado deve estar em nosso contêiner.

````bash
root@b57b9d4eedeb:/# ls
bin boot dev etc home lib lib32 lib32 lib64 lib64 libx32 media mnt opt proc root run sbin srv sys test.txt tmp usr var
```

É importante entender que esse arquivo foi criado quando a imagem foi construída, ou seja, a imagem do contêiner já tem esse arquivo. Ele não é criado quando o contêiner é iniciado

Saímos do contêiner

````bash
root@b57b9d4eedeb:/# exit
saída
```

Como já temos uma imagem, podemos carregá-la no hub do docker, mas vamos listar novamente as imagens antes disso.

In [12]:
!docker image ls

REPOSITORY    TAG       IMAGE ID       CREATED          SIZE
ubuntu        test      a78cf3ea16d8   20 minutes ago   77.8MB
nginx         latest    2d389e545974   8 hours ago      142MB
ubuntu        latest    2dc39ba059dc   11 days ago      77.8MB
ubuntu        20.04     a0ce5a295b63   11 days ago      72.8MB
hello-world   latest    feb5d9fea6a5   11 months ago    13.3kB


Se virmos que ele está nos dizendo que a imagem que acabamos de criar pertence ao repositório do ubuntu, mas não temos acesso ao repositório do ubuntu, então no docker hub temos que criar uma conta para fazer upload da imagem para o nosso repositório. No meu caso, meu repositório se chama `maximofn`, então altero o repositório da imagem usando o comando `tag`, indicando a imagem que queremos alterar o repositório e o novo repositório. No novo repositório, você geralmente especifica o nome do repositório seguido do tipo de imagem e da tag, no meu caso `maximofn/ubuntu:test`.

In [22]:
!docker tag ubuntu:test maximofn/ubuntu:test

Se agora listarmos as imagens novamente

In [14]:
!docker image ls

REPOSITORY        TAG       IMAGE ID       CREATED          SIZE
ubuntu            test      a78cf3ea16d8   24 minutes ago   77.8MB
maximofn/ubuntu   test      a78cf3ea16d8   24 minutes ago   77.8MB
nginx             latest    2d389e545974   8 hours ago      142MB
ubuntu            latest    2dc39ba059dc   11 days ago      77.8MB
ubuntu            20.04     a0ce5a295b63   11 days ago      72.8MB
hello-world       latest    feb5d9fea6a5   11 months ago    13.3kB


Agora precisamos fazer login no hub do docker para fazer upload da imagem, usando o comando `login`.

````bash
$ docker login
Faça login com seu Docker ID para enviar e extrair imagens do Docker Hub. Se você não tiver um ID do Docker, acesse https://hub.docker.com para criar um.
Nome de usuário: maximofn
Senha:

Login bem-sucedido
```

Agora podemos fazer upload da imagem usando o comando `push`.

In [25]:
!docker push maximofn/ubuntu:test

The push refers to repository [docker.io/maximofn/ubuntu]

06994357: Preparing 
06994357: Pushed  from library/ubuntu test: digest: sha256:318d83fc3c35ff930d695b0dc1c5ad1b0ea54e1ec6e3478b8ca85c05fd793c4e size: 735


Ele carregou apenas a primeira camada, a segunda, como eu a usei depois da imagem do Ubuntu, o que ele faz é colocar um ponteiro para essa imagem para evitar que as camadas sejam carregadas mais de uma vez.

Observe que esse repositório é público, portanto, você não deve carregar imagens com dados confidenciais. Além disso, se uma imagem não for usada dentro de 6 meses, ela será excluída.

### O sistema de camadas

Usando o comando `history`, podemos visualizar as camadas de uma imagem. Se quisermos ver as camadas da imagem que acabamos de criar, usaremos o comando `docker history ubuntu:test`.

In [1]:
!docker history ubuntu:test

IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
a78cf3ea16d8   3 minutes ago  /bin/sh -c touch /test.txt                      0B        
2dc39ba059dc   12 days ago    /bin/sh -c #(nop)  CMD ["bash"]                 0B        
<missing>      12 days ago    /bin/sh -c #(nop) ADD file:a7268f82a86219801…   77.8MB    


Vemos que a primeira camada tem o comando que inserimos no `Dockerfile` e diz que foi criada há 3 minutos. No entanto, o restante das camadas foi criado há 12 dias e são as camadas da imagem do Ubuntu na qual nos baseamos.

No `Dockerfile` que criamos anteriormente, adicionamos a linha

```docker
EXECUTAR rm /test.txt
```

No final, o `Dockerfile` tem a seguinte aparência:
````dockerfile
    DE ubuntu:latest
    RUN touch /test.txt
    EXECUTAR rm /test.txt
```

Se compilarmos novamente, veremos o que acontece

In [2]:
!docker build -t ubuntu:test ./dockerImages

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:latest
 ---> 2dc39ba059dc
Step 2/3 : RUN touch /test.txt
 ---> Using cache
 ---> a78cf3ea16d8
Step 3/3 : RUN rm /test.txt
 ---> Running in c2e6887f2025
Removing intermediate container c2e6887f2025
 ---> 313243a9b573
Successfully built 313243a9b573
Successfully tagged ubuntu:test

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Como podemos ver, há mais uma camada com a nova linha que adicionamos. Se olharmos novamente para as camadas da imagem com `history`, veremos que há mais uma camada com a nova linha.

In [3]:
!docker history ubuntu:test

IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
313243a9b573   About a minute ago   /bin/sh -c rm /test.txt                         0B        
a78cf3ea16d8   3 minutes ago        /bin/sh -c touch /test.txt                      0B        
2dc39ba059dc   12 days ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B        
<missing>      12 days ago          /bin/sh -c #(nop) ADD file:a7268f82a86219801…   77.8MB    


Podemos ver que as primeiras camadas são as mesmas de antes e que você adicionou uma nova camada com o novo comando

## Usando o docker para criar aplicativos

### Exibição da porta

Anteriormente, vimos como poderíamos vincular uma porta de contêiner a uma porta de computador (`-p 8080:80`). Mas, para que isso seja possível, ao criar a imagem, você precisa expor a porta, o que é feito adicionando ao Dockerfile a linha `EXPOSE <port>`, no caso de antes

```docker
EXPOSE 80
```

Ou use imagens como base que já tenham portas expostas.

### Reutilização do cache de camada na compilação

Quando compilamos uma imagem, se alguma das camadas que definimos já tiver sido compilada antes, o docker detecta isso e as utiliza, não as recompila. Se recompilarmos a imagem que definimos no `Dockerfile` agora, isso levará muito pouco tempo, pois todas as camadas já foram compiladas e o docker não as recompila.

In [4]:
!docker build -t ubuntu:test ./dockerImages

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:latest
 ---> 2dc39ba059dc
Step 2/3 : RUN touch /test.txt
 ---> Using cache
 ---> a78cf3ea16d8
Step 3/3 : RUN rm /test.txt
 ---> Using cache
 ---> 313243a9b573
Successfully built 313243a9b573
Successfully tagged ubuntu:test

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Na segunda e terceira camadas, aparece o texto `Usando cache`.

Como esse é um notebook Jupyter, ao executar as células, ele fornece as informações sobre o tempo de execução; na vez anterior em que compilei a imagem, levou 1,4 segundo, enquanto agora levou 0,5 segundo.

Mas se eu agora alterar o Dockerfile e, na primeira linha, onde dizia que estávamos nos baseando na versão mais recente do Ubuntu, e mudarmos para a versão 20.04, alterarei o Dockerfile para a versão 20.04.

```docker
DO ubuntu:20.04
```

No final, o `Dockerfile` tem a seguinte aparência:
````dockerfile
    DO ubuntu:20.04
    RUN touch /test.txt
    EXECUTAR rm /test.txt
```

A recompilação levará muito mais tempo.

In [5]:
!docker build -t ubuntu:test ./dockerImages

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:20.04
 ---> a0ce5a295b63
Step 2/3 : RUN touch /test.txt
 ---> Running in a40fe8df2c0d
Removing intermediate container a40fe8df2c0d
 ---> 0bb9b452c11f
Step 3/3 : RUN rm /test.txt
 ---> Running in 2e14919f3685
Removing intermediate container 2e14919f3685
 ---> fdc248fa833b
Successfully built fdc248fa833b
Successfully tagged ubuntu:test

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Levou 1,9 segundos e o texto `Usando cache` não é mais exibido.

Ao alterar a primeira camada, a janela de encaixe recompila todas as camadas. Isso pode ser um problema porque, ao desenvolver o código, pode ocorrer o seguinte caso
 * Desenvolvemos o código em nosso computador
 * Ao criar a imagem, copiamos todo o código do nosso computador para o contêiner.
 * Em seguida, solicitamos que a imagem instale as bibliotecas necessárias.

Isso pode significar que, ao alterar qualquer parte do código, a camada na qual as bibliotecas estão instaladas terá de ser recompilada, pois uma camada anterior foi alterada.

Para resolver isso, a ideia seria que, ao criar a imagem, primeiro solicitássemos a instalação das bibliotecas e, em seguida, copiássemos o código do nosso computador para o contêiner. Dessa forma, toda vez que alterarmos o código e compilarmos a imagem novamente, somente a camada em que o código foi copiado será recompilada, de modo que a compilação será mais rápida.

Você pode pensar que é melhor compartilhar uma pasta entre o host e o container (`bind mount`) onde teremos o código e assim não precisaremos recompilar a imagem toda vez que alterarmos o código. E a resposta é que isso é verdade, só coloquei esse exemplo porque é muito fácil de entender, mas é para mostrar que, ao criar imagens, você deve pensar bem para que, se precisar recompilar, recompile o número mínimo de camadas.

### Como escrever corretamente um Dockerfile

Como vimos, o Docker não recompila as camadas de um Dockerfile se já as tiver compilado antes, portanto, ele as carrega do cache. Vamos ver como deve ser a maneira correta de escrever um Dockerfile para tirar proveito disso

Vamos começar com esse Dockerfile para comentar sobre possíveis correções.

``` Dockerfile
DO ubuntu
COPY ./sourceCode /sourceCode
Execute o apt-get update
Executar apt-get install -y python3 ssh
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

Como você pode ver, você inicia a partir de uma imagem do Ubuntu, copia a pasta com o código, atualiza os repositórios, instala o python, instala o ssh e executa o aplicativo.

#### Copiar código antes da execução

Como dissemos antes, se primeiro copiarmos o código e depois instalarmos o python, toda vez que fizermos uma alteração no código e compilarmos a imagem, ela compilará toda a imagem, mas se copiarmos o código depois de instalar o python, toda vez que alterarmos o código e compilarmos a imagem, ela compilará somente a partir da cópia do código e não reinstalará o python, portanto, o Dockerfile deverá ter a seguinte aparência

``` Dockerfile
DO ubuntu
Execute o apt-get update
Executar apt-get install -y python3 ssh
COPY ./sourceCode /sourceCode
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Copie apenas o código necessário

Estamos copiando a pasta com todo o código, mas talvez tenhamos um código dentro que não precisamos, portanto, temos que copiar apenas o código que realmente precisamos para o aplicativo, dessa forma a imagem ocupará menos memória. Portanto, o Dockerfile teria a seguinte aparência

``` Dockerfile
DO ubuntu
Execute o apt-get update
Executar apt-get install -y python3 ssh
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Atualize os repositórios e instale o python na mesma linha

Estamos atualizando os repositórios em uma linha e instalando o python3 em outra. Mas pode acontecer que, na linha em que instalamos o python3, também adicionemos o pip3; no entanto, como a linha anterior, em que os repositórios são atualizados, não é alterada, ela não será compilada novamente, pois está em cache. Portanto, pode acontecer que os repositórios que atualizamos não contenham os repositórios necessários para o pip3. Portanto, é preciso colocar as duas ações em uma única linha

``` Dockerfile
DO ubuntu
Execute o apt-get update && apt-get install -y python3 ssh
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Não instale o ssh

Instalamos o ssh na imagem para que pudéssemos depurar se fosse necessário, mas isso faz com que a imagem ocupe mais memória. Caso precisemos depurar, devemos entrar no contêiner, instalar o ssh e depois depurar. Portanto, removemos a instalação do ssh.

``` Dockerfile
DO ubuntu
Execute o apt-get update && apt-get install -yython3
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Use `--no-install-recommends`.

Quando instalamos algo no Ubuntu, ele instala os pacotes recomendados, mas não precisamos deles, o que faz com que a imagem ocupe mais espaço. Portanto, para evitar isso, adicionamos "no-install-recommends" à instalação.

``` Dockerfile
DO ubuntu
Execute o apt-get update && apt-get install -yython3 --no-install-recommends
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Limpar a lista de repositórios atualizados

Atualizamos a lista de repositórios e instalamos o python, mas, depois de fazer isso, não precisamos mais da lista de repositórios atualizada, porque eles só aumentarão a imagem, então os removemos depois de instalar o python e na mesma linha

``` Dockerfile
DO ubuntu
EXECUTAR apt-get update && apt-get install -yython3 --no-install-recommends && rm -rf /var/lib/apt/lists/*
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Usando uma imagem Python

Tudo o que fizemos para atualizar a lista de pacotes e instalar o Python não é necessário, pois já existem imagens do Python no Ubuntu, que provavelmente também seguiram as boas práticas, que se saíram até melhor do que nós e que foram verificadas quanto a vulnerabilidades pelo Docker Hub. Então, tiramos tudo isso e começamos com uma imagem do Python

``` Dockerfile
DE python
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Especificando a imagem do Python

Ao não especificar a imagem do Python, você está baixando a mais recente, mas, dependendo de quando você constrói o contêiner, pode baixar uma ou outra, portanto, é necessário adicionar a tag com a versão do Python que você deseja

``` Dockerfile
DE python:3.9.18
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Escolha uma etiqueta pequena

Escolhemos a tag `3.9.18`, mas essa versão do python tem muitas bibliotecas de que talvez não precisemos, portanto, podemos usar a versão `3.9.18-slim`, que tem muito menos bibliotecas instaladas, ou a versão `3.9.18-alphine`, que é uma versão do python sobre o alpine e não sobre o Ubuntu. O Alpine é uma distribuição Linux muito leve que tem pouquíssimos pacotes instalados e é frequentemente usada em contêineres do Docker para que ocupem pouco espaço.

A imagem python `3.9.18` tem 997 MB, a `3.9.18-slim` tem 126 MB e a `3.9.18-alpine` tem 47,8 MB.

``` Dockerfile
DE python:3.9.18-alpine
COPY ./sourceCode/sourceApp /sourceCode/sourceApp
CMD ["python3", "/sourceCode/sourceApp/app.py"]
```

#### Indicar o espaço de trabalho

Em vez de especificar o caminho para a imagem `/sourceCode/sourceApp`, definimos o caminho para o espaço de trabalho da imagem. Dessa forma, quando copiarmos o código ou executarmos o aplicativo, não precisaremos indicar o caminho

``` Dockerfile
DE python:3.9.18-alpine
WORKDIR /sourceCode/sourceApp
COPY ./sourceCode/sourceApp .
CMD ["python3", "app.py"]
```

#### Indicar o espaço de trabalho

Em vez de especificar o caminho para a imagem `/sourceCode/sourceApp`, definimos o caminho para o espaço de trabalho da imagem. Dessa forma, quando copiarmos o código ou executarmos o aplicativo, não precisaremos indicar o caminho

``` Dockerfile
DE python:3.9.18-alpine
WORKDIR /sourceCode/sourceApp
COPY ./sourceCode/sourceApp .
CMD ["python3", "app.py"]
```

### Código compartilhado em uma pasta `bind mount`

Criamos uma pasta chamada `dockerHostFolder` na qual compartilhamos arquivos entre o host e um contêiner. Dentro dela, também deve haver três arquivos

In [1]:
!ls dockerHostFolder

bindFile.txt  fileExtract.txt  text.txt


Vamos aproveitar o arquivo `text.txt` para dar uma olhada nisso. Vamos ver o que há dentro do arquivo `text.txt`.

In [3]:
!cat dockerHostFolder/text.txt

Não há saída, o arquivo está vazio. Vamos criar novamente um contêiner do Ubuntu que compartilha a pasta `dockerHostFolder`.

In [4]:
!docker run --name alwaysup -d -v ~/Documentos/web/portafolio/posts/dockerHostFolder:/dockerContainerFolder ubuntu tail -f /dev/null

24adbded61f507cdf7f192eb5e246e43ee3ffafc9944b7c57918eb2d547dff19


Vemos que o contêiner está em execução

In [5]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS          PORTS     NAMES
24adbded61f5   ubuntu    "tail -f /dev/null"   16 seconds ago   Up 15 seconds             alwaysup


Entramos no contêiner, vemos que `text.txt` está lá e que está vazio.

````bash
$ docker exec -it alwaysup bash
root@24adbded61f5:/# ls dockerContainerFolder/
bindFile.txt fileExtract.txt fileExtract.txt text.txt
root@24adbded61f5:/# cat dockerContainerFolder/text.txt
root@24adbded61f5:/#
```

Agora, abrimos o arquivo `text.txt` no host com o editor de texto de nossa escolha, digitamos `Hello world` e salvamos. Se agora virmos o que está dentro do arquivo no contêiner, veremos o mesmo texto

````bash
root@24adbded61f5:/# cat dockerContainerFolder/text.txt
Olá mundo
```

Agora, editamos o arquivo no contêiner e saímos dele.

````bash
root@24adbded61f5:/# echo hello container > dockerContainerFolder/text.txt
root@24adbded61f5:/# cat dockerContainerFolder/text.txt
hello container
root@24adbded61f5:/# exit
saída
```

Se olharmos o arquivo no host, veremos o texto que escrevemos no contêiner

In [6]:
!cat dockerHostFolder/text.txt

hola contenedor


Excluímos o contêiner

In [7]:
!docker rm -f alwaysup

alwaysup


### Conectar contêineres via rede

Se quisermos ter vários contêineres em execução e quisermos que eles se comuniquem, podemos fazer com que eles se comuniquem por meio de uma rede. O Docker nos dá a possibilidade de fazer isso por meio de suas redes virtuais.

Vamos ver quais redes o docker possui usando o comando `docker network ls`.

In [8]:
!docker network ls

NETWORK ID     NAME      DRIVER    SCOPE
de6e8b7b737e   bridge    bridge    local
da1f5f6fccc0   host      host      local
d3b0d93993c0   none      null      local


Vemos que, por padrão, o docker tem três redes
 * Bridge: é compatível com versões anteriores, mas não devemos mais usá-la.
 * Host: essa é a rede do host
 * none: É a opção a ser usada se quisermos que um contêiner não tenha acesso à Internet.

Podemos criar novas redes às quais outros contêineres podem se conectar. Para isso, usamos o comando `docker network create <name>`, para que outros contêineres possam se conectar a ela, também devemos adicionar a opção `--attachable`.

In [11]:
!docker network create --attachable myNetwork

2f6f3ddbfa8642e9f6819aa0965c16339e9e910be7bcf56ebb718fcac324cc27


Podemos inspecioná-lo usando o comando `docker network inspect <name>`.

In [12]:
!docker network inspect myNetwork

[
    {
        "Name": "myNetwork",
        "Id": "2f6f3ddbfa8642e9f6819aa0965c16339e9e910be7bcf56ebb718fcac324cc27",
        "Created": "2022-09-14T15:20:08.539830161+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]


Agora precisamos criar dois contêineres para que eles possam se comunicar.

Vamos criar um novo contêiner, que chamaremos de `contêiner1`, com uma pasta compartilhada e, dentro dela, será chamado de `pasta1`.

In [17]:
!docker run --name container1 -d -v ~/Documentos/web/portafolio/posts/dockerHostFolder:/folder1 ubuntu tail -f /dev/null

a5fca8ba1e4ff0a67002f8f1b8cc3cd43185373c2a7e295546f774059ad8dd1a


Agora criamos outro contêiner, chamado `container2`, com outra pasta compartilhada, mas chamada `folder2`.

In [18]:
!docker run --name container2 -d -v ~/Documentos/web/portafolio/posts/dockerHostFolder:/folder2 ubuntu tail -f /dev/null

6c8dc18315488ef686f7548516c19b3d716728dd8a173cdb889ec0dd082232f9


Vemos os contêineres funcionando e vemos que ambos são

In [19]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED         STATUS         PORTS     NAMES
6c8dc1831548   ubuntu    "tail -f /dev/null"   3 seconds ago   Up 2 seconds             container2
a5fca8ba1e4f   ubuntu    "tail -f /dev/null"   4 seconds ago   Up 3 seconds             container1


Agora temos que conectar os contêineres à rede, para isso usamos o comando `docker network connect <nome da rede> <nome do contêiner>`.

In [20]:
!docker network connect myNetwork container1

In [21]:
!docker network connect myNetwork container2

Para verificar se eles estão bem conectados, podemos inspecionar a rede, mas filtrando pelos contêineres conectados.

````bash
$ docker network inspect --format '{{.Containers}}' myNetwork
mapa
[
    6c8dc18315488ef686f7548516c19b3d716728dd8a173cdb889ec0dd082232f9:
    {
        contêiner2
        f828d211e894f7a5a992ce41a2a0def8e2424e9737fb4e1485fc09cc2d607b69
        02:42:ac:12:00:03
        172.18.0.3/16
    }
    a5fca8ba1e4ff0a67002f8f1b8cc3cd43185373c2a7e295546f774059ad8dd1a:
    {
        contêiner1
        cff762e6286ebc169804b2a675bbff904102de796751d367c18d4b490c994c45
        02:42:ac:12:00:02
        172.18.0.2/16
    }

```

Como podemos ver, o contêiner `container1` tem o IP `172.18.0.2` e o contêiner `container2` tem o IP `172.18.0.3`.

Entramos no contêiner `container1` e instalamos o `ping`.

``` bash
$ docker exec -it container1 bash
root@a5fca8ba1e4f:/# apt update
    ...
root@a5fca8ba1e4f:/# apt install iputils-ping
    ...
root@a5fca8ba1e4f:/#
```

Entramos no contêiner `container2` e instalamos o `ping`.

````bash
$ docker exec -it container2 bash
root@a5fca8ba1e4f:/# apt update
    ...
root@a5fca8ba1e4f:/# apt install iputils-ping
    ...
root@a5fca8ba1e4f:/#
```

Agora, a partir do contêiner `container1`, fazemos ping no IP `172.18.0.3`, que pertence ao contêiner `container2`.

````bash
root@a5fca8ba1e4f:/# ping 172.18.0.3
PING 172.18.0.3 (172.18.0.3) 56(84) bytes de dados.
64 bytes de 172.18.0.3: icmp_seq=1 ttl=64 time=0.115 ms
64 bytes de 172.18.0.3: icmp_seq=2 ttl=64 time=0.049 ms
64 bytes de 172.18.0.3: icmp_seq=3 ttl=64 time=0.056 ms
64 bytes de 172.18.0.3: icmp_seq=4 ttl=64 time=0.060 ms
^C
--- 172.18.0.3 estatísticas de ping ---
4 pacotes transmitidos, 4 recebidos, 0% de perda de pacotes, tempo 3068ms
rtt min/avg/max/mdev = 0,049/0,070/0,115/0,026 ms
```

E, a partir do contêiner `container2`, fazemos ping no IP `172.18.0.2`, que pertence ao contêiner `container1`.

````bash
root@6c8dc1831548:/# ping 172.18.0.2
PING 172.18.0.2 (172.18.0.2) 56(84) bytes de dados.
64 bytes de 172.18.0.2: icmp_seq=1 ttl=64 time=0.076 ms
64 bytes de 172.18.0.2: icmp_seq=2 ttl=64 time=0.045 ms
64 bytes de 172.18.0.2: icmp_seq=3 ttl=64 time=0.049 ms
64 bytes de 172.18.0.2: icmp_seq=4 ttl=64 time=0.051 ms
^C
--- 172.18.0.2 estatísticas de ping ---
4 pacotes transmitidos, 4 recebidos, 0% de perda de pacotes, tempo 3074ms
rtt min/avg/max/mdev = 0,045/0,055/0,076/0,012 ms
```

Mas há uma coisa melhor que o docker nos permite fazer: se eu não souber o IP do contêiner ao qual quero me conectar, em vez de digitar seu IP, posso digitar seu nome

Agora, a partir do contêiner `contêiner1`, fazemos o ping do IP `contêiner2`.

````bash
root@a5fca8ba1e4f:/# ping container2
PING contêiner2 (172.18.0.3) 56(84) bytes de dados.
64 bytes do container2.myNetwork (172.18.0.3): icmp_seq=1 ttl=64 time=0.048 ms
64 bytes do container2.myNetwork (172.18.0.3): icmp_seq=2 ttl=64 time=0.050 ms
64 bytes do container2.myNetwork (172.18.0.3): icmp_seq=3 ttl=64 time=0.052 ms
64 bytes do container2.myNetwork (172.18.0.3): icmp_seq=4 ttl=64 time=0.053 ms
^C
--- Estatísticas de ping do contêiner2 ---
4 pacotes transmitidos, 4 recebidos, 0% de perda de pacotes, tempo 3071ms
rtt min/avg/max/mdev = 0,048/0,050/0,053/0,002 ms
```

Como podemos ver, o docker sabe que o IP do contêiner `conteiner2` é `172.18.0.3`.

E, a partir do contêiner `contêiner2`, fazemos ping no IP `contêiner1`.

````bash
root@6c8dc1831548:/# ping container1
PING container1 (172.18.0.2) 56(84) bytes de dados.
64 bytes do container1.myNetwork (172.18.0.2): icmp_seq=1 ttl=64 time=0.051 ms
64 bytes do container1.myNetwork (172.18.0.2): icmp_seq=2 ttl=64 time=0.058 ms
64 bytes do container1.myNetwork (172.18.0.2): icmp_seq=3 ttl=64 time=0.052 ms
64 bytes do container1.myNetwork (172.18.0.2): icmp_seq=4 ttl=64 time=0.056 ms
^C
--- Estatísticas de ping do contêiner1 ---
4 pacotes transmitidos, 4 recebidos, 0% de perda de pacotes, tempo 3057ms
rtt min/avg/max/mdev = 0,051/0,054/0,058/0,003 ms
```

Como podemos ver, o docker sabe que o IP do contêiner `conteiner1` é `172.18.0.2`.

Saímos dos contêineres e os apagamos.

In [23]:
!docker rm -f container1 container2

container1
container2


Também excluímos a rede que criamos

In [25]:
!docker network rm myNetwork

myNetwork


## Uso de GPUs

Para usar GPUs host em contêineres docker, é necessário seguir as etapas descritas na página de instalação do [Nvidia container toolkit] (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

### Configurando o repositório e a chave GPG

Temos que configurar o repositório `nvidia container toolkit` e a chave GPG. Para isso, executamos o seguinte comando no console

``` bash
distribuição=$$((. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | | |
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g'
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

### Instalação do `nvidia container toolkit`.

Depois de atualizarmos o repositório e a chave, atualizamos os repositórios usando o comando
``` bash
sudo apt update
```

E instale o `nvidia container toolkit`.
``` bash
sudo apt install -y nvidia-docker2
```

### Reiniciar o Docker

Quando terminarmos, teremos que reiniciar o daemon do docker por meio de
``` bash
sudo systemctl restart docker
```

### Uso de GPUs

Agora que configuramos o docker para poder usar as GPUs do host dentro dos contêineres, podemos testá-lo usando a opção `--gpus all`. Se você tiver mais de uma GPU e quiser usar apenas uma, especifique-a, mas, por enquanto, só explicaremos como usar todas elas.

Criamos um contêiner que não será executado em segundo plano, mas executará o comando `nvidia-smi` para que possamos ver se ele tem acesso às GPUs.

In [32]:
!docker run --name container_gpus --gpus all ubuntu nvidia-smi

Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu

6a12be2b: Pull complete .54MB/29.54MBBDigest: sha256:aabed3296a3d45cede1dc866a24476c4d7e093aa806263c27ddaadbdce3c1054
Status: Downloaded newer image for ubuntu:latest
Mon Sep  4 07:10:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 510.39.01    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro T1000        On   | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P0    15W /  N/A |      9MiB /  4096MiB |      0%      Default |

Excluímos o contêiner

In [ ]:
!doker rm container_gpus

## Docker compose

### Docker compose vs docker-compose

O Docker-compose era uma ferramenta criada para ajudar a manter imagens e contêineres e precisava ser instalada separadamente do docker. No entanto, o docker a incorporou em suas versões mais recentes e não é mais necessário instalá-la; porém, para usá-la, em vez de usar o comando `docker-compose`, é necessário usar o comando `docker-compose`. Em muitos lugares você encontrará informações sobre o `docker-compose`, mas ao instalar o docker você já terá o `docker compose` instalado, então tudo o que você poderia fazer com o `docker-compose` é compatível com o `docker compose`.

### Docker compose

O Docker compose é uma ferramenta do Docker que faz tudo o que vimos até agora, mas nos poupa tempo e esforço. Ao editar um arquivo `.yml`, podemos dizer ao docker compose para criar quantos contêineres quisermos.

Usá-lo uma vez não fará muita diferença em relação a digitar todos os comandos que vimos antes ou digitar o arquivo `.yml`, mas quando você quiser fazer com que a mesma configuração de contêiner funcione novamente, basta chamar o arquivo `.yml` para recriar toda a configuração.

Vamos criar uma pasta onde armazenaremos os arquivos do docker compose

In [26]:
!mkdir dockerComposeFiles

Criamos dentro do arquivo `.yml

In [27]:
!touch dockerComposeFiles/docker-compose.yml

Um arquivo docker compose deve começar com a versão

```json
versão: "<v.v>"
```

No momento da redação deste texto, a versão mais recente é a `3.8`, portanto, escrevemos essa versão

*docker-compose.yml*:

```json
    versão: "3.8".
```

A seguir estão os serviços, que são os contêineres. Em cada serviço, a imagem deve ser especificada e outros parâmetros, como portas, variáveis de ambiente etc., podem ser adicionados.

```json
serviços:
    contêiner1:
        imagem: ubuntu
    
    contêiner2:
        imagem: ubuntu
```

O arquivo `docker-compose.yml` teria a seguinte aparência:

```json
    versão: "3.8".

    serviços:
    contêiner1:
        imagem: ubuntu
    
    contêiner2:
        imagem: ubuntu
```

Depois de criar o arquivo, em seu caminho, podemos executar tudo por meio do comando `docker compose up`, mas também adicionar a opção `-d` fará com que ele seja executado em segundo plano.

In [30]:
!cd dockerComposeFiles && docker compose up -d

[+] Running 1/0
 ⠿ Network dockercomposefiles_default         Created                      0.1s
 ⠋ Container dockercomposefiles-container2-1  Creating                     0.0s
 ⠋ Container dockercomposefiles-container1-1  Creating                     0.0s
[+] Running 1/3
 ⠿ Network dockercomposefiles_default         Created                      0.1s
 ⠙ Container dockercomposefiles-container2-1  Creating                     0.1s
 ⠙ Container dockercomposefiles-container1-1  Creating                     0.1s
[+] Running 1/3
 ⠿ Network dockercomposefiles_default         Created                      0.1s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.2s
 ⠿ Container dockercomposefiles-container1-1  Starting                     0.2s
[+] Running 1/3
 ⠿ Network dockercomposefiles_default         Created                      0.1s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.3s
 ⠿ Container dockercomposefiles-container1-1  Starting  

Se você observar os dois contêineres `dockercomposefiles-container1-1` e `dockercomposefiles-container2-1` e a rede que os vincula `dockercomposefiles_default`, terá criado dois contêineres `dockercomposefiles-container1-1` e `dockercomposefiles-container2-1`.

Vamos excluir os dois contêineres

In [34]:
!docker rm -f dockercomposefiles-container1-1 dockercomposefiles-container2-1

dockercomposefiles-container1-1
dockercomposefiles-container2-1


E excluímos a rede que ele criou

In [35]:
!docker network rm dockercomposefiles_default

dockercomposefiles_default


Vamos tentar fazer o que fizemos antes com o que sabemos até agora. Criamos uma nova imagem que vem com o `ping` instalado.

*Arquivo do Docker:
```docker
    DO ubuntu:20.04
    Executar apt update
    Execute o apt install iputils-ping -y
```

E nós o compilamos

In [2]:
!docker build -t ubuntu:ping ./dockerImages

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:20.04
 ---> a0ce5a295b63
Step 2/3 : RUN apt update
 ---> Running in 3bd5278d39b4


Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [898 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2133 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1501 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/restri

Verificamos se ele foi criado

In [3]:
!docker image ls

REPOSITORY        TAG       IMAGE ID       CREATED              SIZE
ubuntu            ping      c3d32aa9de02   About a minute ago   112MB
maximofn/ubuntu   test      a78cf3ea16d8   25 hours ago         77.8MB
nginx             latest    2d389e545974   33 hours ago         142MB
ubuntu            latest    2dc39ba059dc   12 days ago          77.8MB
ubuntu            20.04     a0ce5a295b63   12 days ago          72.8MB
hello-world       latest    feb5d9fea6a5   11 months ago        13.3kB


Alteramos a tag

In [6]:
!docker tag ubuntu:ping maximofn/ubuntu:ping

In [8]:
!docker image ls

REPOSITORY        TAG       IMAGE ID       CREATED              SIZE
ubuntu            ping      c3d32aa9de02   About a minute ago   112MB
maximofn/ubuntu   ping      c3d32aa9de02   About a minute ago   112MB
maximofn/ubuntu   test      c3d32aa9de02   About a minute ago   112MB
nginx             latest    2d389e545974   33 hours ago         142MB
ubuntu            latest    2dc39ba059dc   12 days ago          77.8MB
ubuntu            20.04     a0ce5a295b63   12 days ago          72.8MB
hello-world       latest    feb5d9fea6a5   11 months ago        13.3kB


Edite o arquivo docker compose para obter as imagens que acabamos de criar.

*docker-compose.yml*:
```json
    versão: "3.8".

    serviços:
      contêiner1:
        imagem: maximofn/ubuntu:ping

    contêiner2:
        imagem: maximofn/ubuntu:ping
```

E também dizemos a ele para executar uma não operação.

O arquivo `docker-compose.yml` teria a seguinte aparência:
```json
    versão: "3.8".

    serviços:
      contêiner1:
        imagem: ubuntu
        comando: tail -f /dev/null

    contêiner2:
        imagem: ubuntu
        comando: tail -f /dev/null
```

Nós o levantamos

In [9]:
!cd dockerComposeFiles && docker compose up -d

[+] Running 0/0
 ⠋ Container dockercomposefiles-container1-1  Recreate                     0.1s
 ⠋ Container dockercomposefiles-container2-1  Recreate                     0.1s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Recreated                    0.1s
 ⠙ Container dockercomposefiles-container2-1  Recreate                     0.2s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Recreated                    0.1s
 ⠹ Container dockercomposefiles-container2-1  Recreate                     0.3s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Recreated                    0.1s
 ⠸ Container dockercomposefiles-container2-1  Recreate                     0.4s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Recreated                    0.1s
 ⠼ Container dockercomposefiles-container2-1  Recreate                     0.5s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Recreated                    0.1s
 ⠴ Container dockercompo

Vemos os contêineres que estão em execução

In [10]:
!docker ps

CONTAINER ID   IMAGE                  COMMAND               CREATED          STATUS          PORTS     NAMES
935939e5a75d   maximofn/ubuntu:ping   "tail -f /dev/null"   15 seconds ago   Up 13 seconds             dockercomposefiles-container2-1
f9138d7064dd   maximofn/ubuntu:ping   "tail -f /dev/null"   25 seconds ago   Up 13 seconds             dockercomposefiles-container1-1


Os dois contêineres estão em execução. Agora, entramos em um deles e tentamos "pingar" o outro.

````bash
$ docker exec -it dockercomposefiles-container1-1 bash
root@f9138d7064dd:/# ping dockercomposefiles-container2-1
PING dockercomposefiles-container2-1 (172.21.0.3) 56(84) bytes de dados.
64 bytes de dockercomposefiles-container2-1.dockercomposefiles_default (172.21.0.3): icmp_seq=1 ttl=64 time=0.110 ms
64 bytes de dockercomposefiles-container2-1.dockercomposefiles_default (172.21.0.3): icmp_seq=2 ttl=64 time=0.049 ms
64 bytes de dockercomposefiles-container2-1.dockercomposefiles_default (172.21.0.3): icmp_seq=3 ttl=64 time=0.049 ms
64 bytes de dockercomposefiles-container2-1.dockercomposefiles_default (172.21.0.3): icmp_seq=4 ttl=64 time=0.075 ms
^C
--- dockercomposefiles-container2-1 ping statistics ---
4 pacotes transmitidos, 4 recebidos, 0% de perda de pacotes, tempo 3068ms
rtt min/avg/max/mdev = 0,049/0,070/0,110/0,025 ms
```

Como podemos ver, podemos fazer o `ping`, criamos a imagem bem com o `ping` instalado. Além disso, no docker compose, criamos uma não operação a ser executada para que os contêineres estejam em execução

Exclua os dois contêineres e a rede que eles criaram.

In [11]:
!docker rm -f dockercomposefiles-container1-1 dockercomposefiles-container2-1

dockercomposefiles-container1-1
dockercomposefiles-container2-1


In [12]:
!docker network rm dockercomposefiles_default

dockercomposefiles_default


### Como o nome do docker compõe contêineres?

Se você observar os contêineres que o docker criou, eles foram chamados de `dockercomposefiles-container1-1` e `dockercomposefiles-container1-1`. Isso ocorre porque a pasta em que o arquivo docker compose está localizado é uma pasta chamada `dockerComposeFiles`, portanto, a primeira parte do nome dos contêineres é `dockercomposefiles`, depois o nome do serviço que fornecemos no arquivo docker compose (`container1` e `container2`) e, por fim, um número para criar mais, se necessário.

O mesmo acontece com o nome da rede que você criou `dockercomposefiles_default`.

### Registros no docker compose

Agora vamos alterar o arquivo docker compose, nas linhas onde tínhamos ```command: tail -f /dev/null```, vamos colocar ```command: ping 0.0.0.0.0.0```.

E também dizemos a ele para executar uma não operação.

O arquivo `docker-compose.yml` teria a seguinte aparência:
```json
    versão: "3.8".

    serviços:
      contêiner1:
        imagem: ubuntu
        comando: ping 0.0.0.0.0.0

    contêiner2:
        imagem: ubuntu
        comando: ping 0.0.0.0.0.0
```

Fazemos isso de modo que cada contêiner esteja constantemente emitindo o ping, portanto, simulamos os registros.

Se executarmos novamente o docker compose

In [1]:
!cd dockerComposeFiles && docker compose up -d

[+] Running 0/0
 ⠋ Container dockercomposefiles-container1-1  Recreate                     0.1s
 ⠋ Container dockercomposefiles-container2-1  Recreate                     0.1s
[+] Running 0/2
 ⠙ Container dockercomposefiles-container1-1  Recreate                     0.2s
 ⠙ Container dockercomposefiles-container2-1  Recreate                     0.2s
[+] Running 0/2
 ⠹ Container dockercomposefiles-container1-1  Recreate                     0.3s
 ⠹ Container dockercomposefiles-container2-1  Recreate                     0.3s
[+] Running 0/2
 ⠸ Container dockercomposefiles-container1-1  Recreate                     0.4s
 ⠸ Container dockercomposefiles-container2-1  Recreate                     0.4s
[+] Running 0/2
 ⠼ Container dockercomposefiles-container1-1  Recreate                     0.5s
 ⠼ Container dockercomposefiles-container2-1  Recreate                     0.5s
[+] Running 0/2
 ⠴ Container dockercomposefiles-container1-1  Recreate                     0.6s
 ⠴ Container dockercompo

Agora podemos visualizar os registros dos dois contêineres usando o comando `docker compose logs`.

In [3]:
!cd dockerComposeFiles && docker compose logs

dockercomposefiles-container2-1  | PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.042 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.025 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.022 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.030 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.021 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=6 ttl=64 time=0.021 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=7 ttl=64 time=0.030 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=8 ttl=64 time=0.028 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=9 ttl=64 time=0.028 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=10 ttl=64 time=0.026 

Como podemos ver, podemos ver os logs de ambos os contêineres, mas caso queiramos ver os logs de apenas um contêiner, podemos especificar o **nome do serviço**.

In [5]:
!cd dockerComposeFiles && docker compose logs container1

dockercomposefiles-container1-1  | PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.037 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.025 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.023 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.031 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.034 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=6 ttl=64 time=0.033 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=7 ttl=64 time=0.034 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=8 ttl=64 time=0.022 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=9 ttl=64 time=0.032 ms
dockercomposefiles-container1-1  | 64 bytes from 127.0.0.1: icmp_seq=10 ttl=64 time=0.029 

In [6]:
!cd dockerComposeFiles && docker compose logs container2

dockercomposefiles-container2-1  | PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.042 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.025 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.022 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.030 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.021 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=6 ttl=64 time=0.021 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=7 ttl=64 time=0.030 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=8 ttl=64 time=0.028 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=9 ttl=64 time=0.028 ms
dockercomposefiles-container2-1  | 64 bytes from 127.0.0.1: icmp_seq=10 ttl=64 time=0.026 

Se quisermos ver os registros continuamente, podemos adicionar a opção `-f`, `docker compose logs - <service name>`.

Se você tiver criado um docker compose com mais de dois serviços, quando quiser ver os registros de vários serviços, basta adicionar mais nomes ao comando, `docker compose logs <nome do serviço 1> <nome do serviço 2> ...`.

### Serviços de execução

Como vimos, usando o comando `exec`, podemos entrar em um contêiner especificando o nome do contêiner, o comando que queremos executar e a opção `-it`. Com o docker compose, isso é mais fácil, já que apenas o nome do serviço e o comando são necessários, mas a opção `-it` não é necessária, pois o docker compose a considera garantida.

````bash
$ docker compose exec container1 bash
root@a7cf282fe66c:/#
```

### Parando o docker compose

Quando terminamos de trabalhar, com um único comando (`stop`), o docker compose para tudo, não há necessidade de parar cada contêiner um a um.

In [7]:
!cd dockerComposeFiles && docker compose stop

[+] Running 0/0
 ⠋ Container dockercomposefiles-container2-1  Stopping                     0.1s
 ⠋ Container dockercomposefiles-container1-1  Stopping                     0.1s
[+] Running 0/2
 ⠙ Container dockercomposefiles-container2-1  Stopping                     0.2s
 ⠙ Container dockercomposefiles-container1-1  Stopping                     0.2s
[+] Running 0/2
 ⠹ Container dockercomposefiles-container2-1  Stopping                     0.3s
 ⠹ Container dockercomposefiles-container1-1  Stopping                     0.3s
[+] Running 0/2
 ⠸ Container dockercomposefiles-container2-1  Stopping                     0.4s
 ⠸ Container dockercomposefiles-container1-1  Stopping                     0.4s
[+] Running 0/2
 ⠼ Container dockercomposefiles-container2-1  Stopping                     0.5s
 ⠼ Container dockercomposefiles-container1-1  Stopping                     0.5s
[+] Running 0/2
 ⠴ Container dockercomposefiles-container2-1  Stopping                     0.6s
 ⠴ Container dockercompo

Como você pode ver, o docker compose parou os dois contêineres, mas não os excluiu, nem excluiu a rede.

In [8]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


In [9]:
!docker ps -a

CONTAINER ID   IMAGE                  COMMAND          CREATED          STATUS                        PORTS     NAMES
1e6c1dd9adb2   maximofn/ubuntu:ping   "ping 0.0.0.0"   16 minutes ago   Exited (137) 25 seconds ago             dockercomposefiles-container2-1
a7cf282fe66c   maximofn/ubuntu:ping   "ping 0.0.0.0"   16 minutes ago   Exited (137) 25 seconds ago             dockercomposefiles-container1-1


In [10]:
!docker network ls

NETWORK ID     NAME                         DRIVER    SCOPE
13cc632147f3   bridge                       bridge    local
d4a2f718cd83   dockercomposefiles_default   bridge    local
da1f5f6fccc0   host                         host      local
d3b0d93993c0   none                         null      local


### Docker compose como uma ferramenta de desenvolvimento

Como vimos anteriormente, para que seja possível desenvolver, o ideal seria compartilhar a pasta que contém o código com o serviço. Isso é feito com o docker compose, adicionando a tag `volumes` ao arquivo docker compose. Primeiro, temos de adicionar o caminho para a pasta onde o código está no host e, em seguida, o caminho para o contêiner.

*docker-compose.yml*:
```json
    versão: "3.8".

    serviços:
      contêiner1:
        imagem: ubuntu
        comando: ping 0.0.0.0.0.0
        volumes:
            - ../dockerHostFolder/:/dockerContainerFolder

    contêiner2:
        imagem: ubuntu
        comando: ping 0.0.0.0.0.0
```

Como você pode ver, o caminho para a pasta do host que defini em relação a

Se levantarmos o docker compose

In [11]:
!cd dockerComposeFiles && docker compose up -d

[+] Running 1/0
 ⠋ Container dockercomposefiles-container1-1  Recreate                     0.1s
 ⠿ Container dockercomposefiles-container2-1  Created                      0.0s
[+] Running 0/2
 ⠿ Container dockercomposefiles-container1-1  Starting                     0.2s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.2s
[+] Running 0/2
 ⠿ Container dockercomposefiles-container1-1  Starting                     0.3s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.3s
[+] Running 0/2
 ⠿ Container dockercomposefiles-container1-1  Starting                     0.4s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.4s
[+] Running 1/2
 ⠿ Container dockercomposefiles-container1-1  Started                      0.5s
 ⠿ Container dockercomposefiles-container2-1  Starting                     0.5s
[+] Running 2/2
 ⠿ Container dockercomposefiles-container1-1  Started                      0.5s
 ⠿ Container dockercompo

Se entrarmos no contêiner, poderemos ver o que está dentro do arquivo text.txt.

````bash
$ docker compose exec container1 bash
root@c8aae9d619d3:/# ls dockerContainerFolder/
bindFile.txt fileExtract.txt fileExtract.txt text.txt
root@c8aae9d619d3:/# cat dockerContainerFolder/text.txt
hello container
```

Se agora o abrirmos no host, digitaremos `hello host` e veremos novamente no contêiner

````bash
root@c8aae9d619d3:/# cat dockerContainerFolder/text.txt
olá host
```

E agora, ao contrário, se o modificarmos no contêiner

````bash
root@c8aae9d619d3:/# echo hello compose > dockerContainerFolder/text.txt
root@c8aae9d619d3:/# exit
saída
```

Se olharmos para ele a partir do host, devemos obter `hello compose`.

In [12]:
!cat dockerHostFolder/text.txt

hola compose


### Exposição de portas no docker compose

Também podemos configurar as portas no arquivo docker compose, usando a tag `ports`, especificando a porta do host e, em seguida, o ip do serviço

```json
portos:
    - <porta do host>:<porta do serviço>:<porta do serviço>.
```

### Docker compose na equipe - substituição do docker

Se formos um grupo de pessoas desenvolvendo no docker com o docker compose, é provável que muitas pessoas estejam alterando o arquivo docker compose, o que pode fazer com que eles não sincronizem bem e causem conflitos.

Para resolver isso, o docker oferece uma ferramenta chamada docker override. Dessa forma, pode haver um arquivo de composição do docker básico e todos podem modificá-lo usando o docker override.

Para isso, agora precisamos criar um arquivo chamado `docker-compose.override.yml` que podemos editar.

In [13]:
!touch dockerComposeFiles/docker-compose.override.yml

Se agora tentarmos aumentar o docker compose, receberemos um erro

In [14]:
!cd dockerComposeFiles && docker compose up -d

Top-level object must be a mapping


Isso ocorre porque o docker compose detectou que existe um arquivo chamado `docker-compose.override.yml` e ele está vazio, portanto, vamos editá-lo. O arquivo `docker-compose.override.yml` edita o arquivo `docker-compose.yml`, portanto, se, por exemplo, quisermos fazer uma alteração no serviço `container2` para adicionar um volume a ele, escreveremos o arquivo `docker-compose.override.yml` da seguinte forma

*docker-compose.override.yml*:
```json
    versão: "3.8".

    serviços:
    contêiner2:
        volumes:
        - ../dockerHostFolder/:/dockerOverrideFolder
```

Observe que a pasta compartilhada no serviço é chamada de `dockerOverrideFolder`, portanto, vamos abrir o docker compose e ver se vemos essa pasta no contêiner `container2`.

In [15]:
!cd dockerComposeFiles && docker compose up -d

[+] Running 1/0
 ⠋ Container dockercomposefiles-container2-1  Recreate                     0.1s
 ⠿ Container dockercomposefiles-container1-1  Running                      0.0s
[+] Running 1/2
 ⠙ Container dockercomposefiles-container2-1  Recreate                     0.2s
 ⠿ Container dockercomposefiles-container1-1  Running                      0.0s
[+] Running 1/2
 ⠹ Container dockercomposefiles-container2-1  Recreate                     0.3s
 ⠿ Container dockercomposefiles-container1-1  Running                      0.0s
[+] Running 1/2
 ⠸ Container dockercomposefiles-container2-1  Recreate                     0.4s
 ⠿ Container dockercomposefiles-container1-1  Running                      0.0s
[+] Running 1/2
 ⠼ Container dockercomposefiles-container2-1  Recreate                     0.5s
 ⠿ Container dockercomposefiles-container1-1  Running                      0.0s
[+] Running 1/2
 ⠴ Container dockercomposefiles-container2-1  Recreate                     0.6s
 ⠿ Container dockercompo

Vemos que foram necessários 10 segundos para montar o serviço `container2`, o que se deve ao fato de ele estar aplicando as alterações.

````bash
$ docker compose exec container2 bash
root@d8777a4e611a:/# ls dockerOverrideFolder/
bindFile.txt fileExtract.txt fileExtract.txt text.txt
root@d8777a4e611a:/# cat dockerOverrideFolder/text.txt
hello compose
root@d8777a4e611a:/# exit
saída
```

Baixamos a composição e excluímos os contêineres e a rede criada.

In [16]:
!cd dockerComposeFiles && docker compose down

[+] Running 0/0
 ⠋ Container dockercomposefiles-container2-1  Stopping                     0.1s
 ⠋ Container dockercomposefiles-container1-1  Stopping                     0.1s
[+] Running 0/2
 ⠙ Container dockercomposefiles-container2-1  Stopping                     0.2s
 ⠙ Container dockercomposefiles-container1-1  Stopping                     0.2s
[+] Running 0/2
 ⠹ Container dockercomposefiles-container2-1  Stopping                     0.3s
 ⠹ Container dockercomposefiles-container1-1  Stopping                     0.3s
[+] Running 0/2
 ⠸ Container dockercomposefiles-container2-1  Stopping                     0.4s
 ⠸ Container dockercomposefiles-container1-1  Stopping                     0.4s
[+] Running 0/2
 ⠼ Container dockercomposefiles-container2-1  Stopping                     0.5s
 ⠼ Container dockercomposefiles-container1-1  Stopping                     0.5s
[+] Running 0/2
 ⠴ Container dockercomposefiles-container2-1  Stopping                     0.6s
 ⠴ Container dockercompo

Nesse caso, apenas com `down` o docker compose parou e excluiu tudo, como podemos ver nos contêineres e na rede, onde está escrito `Removed`.

### Reiniciar o Docker compose

Ao escrever um docker compose, podemos adicionar a tag `restart` para que, se o contêiner falhar, ele seja reiniciado automaticamente.

```json
reiniciar: sempre
```

Dessa forma, se o contêiner falhar, ele será reiniciado automaticamente. Se quisermos que ele seja reiniciado apenas um determinado número de vezes, podemos adicionar a opção `on-failure`.

```json
reiniciar: on-failure:<número>
```

Agora, o contêiner será reiniciado várias vezes, mas, se houver mais falhas, ele não será reiniciado. Se quisermos que ele sempre reinicie, podemos adicionar a opção `unless-stopped` a ele.

```json
reiniciar: a menos que seja interrompido
```

Agora, o contêiner será sempre reiniciado, a menos que seja interrompido manualmente.

## Docker avançado

### Gerenciar o ambiente de trabalho

#### Exclusão de contêineres desativados

Depois de um tempo de desenvolvimento, podemos ter vários contêineres desativados, mas armazenados no computador. Isso acaba ocupando memória, portanto, com o `docker contanier prune`, podemos excluir todos os contêineres parados.

In [19]:
!docker run ubuntu

In [20]:
!docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


In [23]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED          STATUS                      PORTS     NAMES
effcee24f54a   ubuntu    "bash"    37 seconds ago   Exited (0) 36 seconds ago             musing_rosalind


``` bash
$ docker container prune
AVISO: Isso removerá todos os contêineres parados.
Tem certeza de que deseja continuar? [y/N] y
Contêineres excluídos:
effcee24f54aab22e34fdea2465b3b7af132d8c627e5432ba3e915a370876977

Total de espaço recuperado: 0B
```

Nesse caso, economizamos 0 bytes, mas no caso de deixar os contêineres desativados após muito desenvolvimento, a economia de memória certamente será maior.

#### Exclusão de todos os contêineres

Caso tenhamos contêineres em execução, podemos eliminar todos os contêineres com outro comando

O comando `docker ps -q` retorna o ID de todos os contêineres, portanto, com o comando `docker rm -f $(docker ps -aq)`, interromperemos e excluiremos todos os contêineres.

In [27]:
!docker run -d ubuntu tail -f /dev/null

c22516186ef7e3561fb1ad0d508a914857dbc61274a218f297c4d80b1fc33863


In [32]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED              STATUS              PORTS     NAMES
c22516186ef7   ubuntu    "tail -f /dev/null"   About a minute ago   Up About a minute             agitated_knuth


In [33]:
!docker rm -f $(docker ps -aq)

c22516186ef7


In [34]:
!docker ps -a

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES


#### Excluiu tudo

Como vimos, o docker também cria redes, imagens, volumes etc. Portanto, com o comando `docker system prune`, podemos excluir todos os contêineres parados, todas as redes que não são usadas por pelo menos um contêiner, as imagens repetidas e tudo o que estiver repetido no cache de compilação.

``` bash
$ docker system prune
AVISO: Isso removerá:
  - todos os contêineres parados
  - todas as redes não usadas por pelo menos um contêiner
  - todas as imagens suspensas
  - todos os cache de compilação pendentes

Tem certeza de que deseja continuar? [y/N] y
Total de espaço recuperado: 0B
```

Como antes, não foi economizado muito espaço, mas após um longo período de desenvolvimento, a economia será considerável.

### Uso de recursos do host pelo contêiner

Por exemplo, ao criar um contêiner, podemos limitar a RAM do host que ele pode usar usando a opção `--memory`.

In [35]:
!docker run -d --memory 1g ubuntu tail -f /dev/null

d84888eafe531831ef8915d2270422365adec02678122bf59580e2da782e6972


Mas com o `docker ps` não temos acesso aos recursos que estão sendo consumidos pelo contêiner.

In [36]:
!docker ps

CONTAINER ID   IMAGE     COMMAND               CREATED          STATUS          PORTS     NAMES
d84888eafe53   ubuntu    "tail -f /dev/null"   35 seconds ago   Up 34 seconds             musing_ritchie


Para isso, temos o comando `docker stats`.

````bash
$ docker stats
CONTÊINER ID NOME CPU % MEM USO / LIMITE MEM % NET I/O BLOCK I/O PIDS
d84888eafe53 musing_ritchie 0.00% 540KiB / 1GiB 0.05% 5.62kB / 0B 0B / 0B 1
```

Isso é muito útil se quisermos simular um ambiente com um limite de RAM.

### Parando os contêineres corretamente: SHELL vs EXEC

Como explicamos, quando atribuímos um processo a um contêiner, quando esse processo termina, o contêiner para, mas às vezes podemos encontrar problemas com isso. Vamos criar uma nova pasta chamada Dockerfile_loop

In [1]:
!mkdir Dockerfile_loop

Agora, vamos criar um arquivo chamado `loop.sh` dentro de `Dockerfile_loop`.

In [2]:
!touch Dockerfile_loop/loop.sh

E vamos escrever o seguinte dentro do `loop.sh`

``` shell
#!/usr/bin/env bash
trap "exit 0" SIGTERM
while true; do :; done
```

Se eu executar esse script no host, ele será executado até que eu digite `CTRL+C`.


``` bash
 ./loop
 ^C
 ```

Agora vamos criar um arquivo `Dockerfile` dentro de `Dockerfile_loop`.

In [3]:
!touch Dockerfile_loop/Dockerfile

*Arquivo do Docker:
``` docker
DE ubuntu:trusty
COPY ["loop.sh", "/"]
CMD /loop.sh
```

Criaremos uma imagem baseada no Ubuntu que copia o script dentro dele e o executa, e o script é executado até receber o sinal `SIGTERM` do sistema operacional. Compilamos a imagem

In [10]:
!docker build -t ubuntu:loop ./Dockerfile_loop

Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM ubuntu:trusty
 ---> 13b66b487594
Step 2/3 : COPY ["loop.sh", "/"]
 ---> 89f2bbd25a88
Step 3/3 : CMD /loop.sh
 ---> Running in ff52569c35fd
Removing intermediate container ff52569c35fd
 ---> feb091e4efa3
Successfully built feb091e4efa3
Successfully tagged ubuntu:loop

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Executamos o contêiner

``` bash
docker run -d --name looper ubuntu:loop bash
```

In [24]:
!docker run -d --name looper ubuntu:loop

8a28f8cc9892213c4e0603dfdde320edf52c091b82c60510083549a391cd6645


Verificamos e constatamos que o contêiner está em execução

In [25]:
!docker ps

CONTAINER ID   IMAGE         COMMAND                 CREATED         STATUS         PORTS     NAMES
8a28f8cc9892   ubuntu:loop   "/bin/sh -c /loop.sh"   4 seconds ago   Up 3 seconds             looper


Tentamos parar o contêiner com o `docker stop looper`. O Docker stop tenta parar o contêiner enviando-lhe o sinal `SIGTERM`.

In [26]:
%%time
!docker stop looper

looper
CPU times: user 89.2 ms, sys: 21.7 ms, total: 111 ms
Wall time: 10.6 s


Isso levou cerca de 10 segundos para parar, quando deveria ter parado imediatamente. Isso ocorre porque o `stop` enviou o comando `SIGTERM` para parar o contêiner, mas como ele não parou, depois de algum tempo ele enviou um `SIGKILL` para forçá-lo a parar. Vamos ver o que acontece se listarmos os contêineres.

In [27]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND                 CREATED          STATUS                       PORTS     NAMES
8a28f8cc9892   ubuntu:loop   "/bin/sh -c /loop.sh"   23 seconds ago   Exited (137) 2 seconds ago             looper


Podemos ver que o sinal `Exited` é `137`, o que significa SIGKILL, ou seja, o docker teve que forçar o desligamento.

Vamos excluir o contêiner e executá-lo novamente.

In [28]:
!docker rm looper

looper


In [29]:
!docker run -d --name looper ubuntu:loop

84bc37f944d270be5f84a952968db2b8cf5372c61146d29383468198ceed18fd


Se agora tentarmos parar o contêiner com `docker kill looper`, tentaremos parar o contêiner com `docker kill looper`.

In [30]:
%%time
!docker kill looper

looper
CPU times: user 9.1 ms, sys: 857 µs, total: 9.96 ms
Wall time: 545 ms


Podemos ver que o tempo é de aproximadamente 500 ms, ou seja, o docker o parou em um momento enviando o comando `SIGKILL`. Como o `kill` não envia o `SIGTERM` e, se o contêiner não tiver sido parado há algum tempo, ele envia o `SIGKILL`, o que ele faz é enviar o `SIGKILL` desde o início.

Se observarmos os contêineres, veremos que o sinal de saída é o mesmo, `137`.

In [31]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND                 CREATED         STATUS                       PORTS     NAMES
84bc37f944d2   ubuntu:loop   "/bin/sh -c /loop.sh"   6 seconds ago   Exited (137) 2 seconds ago             looper


Essa não é a maneira correta de encerrar um contêiner, pois quando quisermos encerrar o contêiner, teremos que fazer isso com o sinal `SIGTERM`, para que o contêiner termine de processar o que estava fazendo e, em seguida, encerre.

Se excluirmos o contêiner e o executarmos novamente

In [32]:
!docker rm looper

looper


In [33]:
!docker run -d --name looper ubuntu:loop

b9d9f370cc0de7569eb09d0a85cd67e8ea6babc0754a517ccba5c5057f5cc50e


Se observarmos agora os processos que estão sendo executados dentro do contêiner

In [34]:
!docker exec looper ps -ef

UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 14:05 ?        00:00:00 /bin/sh -c /loop.sh
root           7       1 93 14:05 ?        00:00:02 bash /loop.sh
root           8       0  0 14:05 ?        00:00:00 ps -ef


Na verdade, o processo principal, o processo 1, não é o `/loop.sh`, mas o `/bin/sh -c /loop.sh`, ou seja, é um processo filho do `shell`. Portanto, quando o sinal `SIGTERM` chegou, ele foi enviado para o `shell`, mas ele não o envia para seus processos filhos, por isso não chegou ao `loop.sh`.

Para evitar que isso aconteça, altere o `Dockerfile` para o seguinte

*Arquivo do Docker:
``` docker
DE ubuntu:trusty
COPY ["loop.sh", "/"]
CMD ["/loop.sh"] # costumava ser CMD /loop.sh
```

Esse formulário é chamado de `exec form`, enquanto o formulário anterior é chamado de `shell form`, de modo que o formulário anterior executa o processo como um filho do `shell`, enquanto o `exec form` executa o processo que lhe indicamos. Portanto, excluímos o contêiner, recompilamos e executamos o contêiner com a imagem novamente.

In [41]:
!docker rm -f looper

looper


In [45]:
!docker build -t ubuntu:loop ./Dockerfile_loop

Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM ubuntu:trusty
 ---> 13b66b487594
Step 2/3 : COPY ["loop.sh", "/"]
 ---> Using cache
 ---> 89f2bbd25a88
Step 3/3 : CMD ["/loop.sh"]
 ---> Running in 6b8d92fcd57c
Removing intermediate container 6b8d92fcd57c
 ---> 35a7bb2b1892
Successfully built 35a7bb2b1892
Successfully tagged ubuntu:loop

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


In [46]:
!docker run -d --name looper ubuntu:loop

850ae70c071426850b28428ac60dcbf875c6d35d9b7cc66c17cf391a23392965


Se agora eu olhar para os processos dentro do contêiner

In [47]:
!docker exec looper ps -ef

UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0 88 14:14 ?        00:00:02 bash /loop.sh
root           7       0  0 14:14 ?        00:00:00 ps -ef


Agora vejo que o processo principal, o processo 1, é o `/loop.sh`.

Se agora eu tentar parar o contêiner

In [48]:
%%time
!docker stop looper

looper
CPU times: user 989 µs, sys: 7.55 ms, total: 8.54 ms
Wall time: 529 ms


Vemos que isso leva ms. Vamos ver o código com o qual ele parou

In [49]:
!docker ps -a

CONTAINER ID   IMAGE         COMMAND      CREATED              STATUS                      PORTS     NAMES
850ae70c0714   ubuntu:loop   "/loop.sh"   About a minute ago   Exited (0) 33 seconds ago             looper


### Contêineres executáveis

Se quisermos que um binário seja executado como um executável, no `dockerfile` temos que especificar o comando em `ENTRYPOINT` e os parâmetros de comando em `CMD`.

Vamos criar uma nova pasta onde salvaremos o `Dockerfile`.

In [4]:
!mkdir dockerfile_ping

Agora, criamos um Dockerfile dentro de

In [5]:
!touch dockerfile_ping/Dockerfile

Escrevemos o seguinte no Dockerfile

``` docker
DE ubuntu:trusty
ENTRYPOINT [ "/bin/ping", "-c", "3" ]
CMD [ "localhost" ]
```

Compilamos a imagem

In [8]:
!docker build -t ubuntu:ping ./dockerfile_ping

Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM ubuntu:trusty
 ---> 13b66b487594
Step 2/3 : ENTRYPOINT [ "/bin/ping", "-c", "3" ]
 ---> Using cache
 ---> 1cebcfb542b1
Step 3/3 : CMD [ "localhost" ]
 ---> Using cache
 ---> 04ddc3de52a2
Successfully built 04ddc3de52a2
Successfully tagged ubuntu:ping

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Se agora executarmos a imagem sem passar um parâmetro, o contêiner fará ping em si mesmo.

In [10]:
!docker run --name ping_localhost ubuntu:ping

PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.058 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.054 ms

--- localhost ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2027ms
rtt min/avg/max/mdev = 0.041/0.051/0.058/0.007 ms


Mas, se agora passarmos um parâmetro, ele fará o ping do endereço que dissermos para ele fazer.

In [11]:
!docker run --name ping_google ubuntu:ping google.com

PING google.com (216.58.209.78) 56(84) bytes of data.
64 bytes from waw02s06-in-f14.1e100.net (216.58.209.78): icmp_seq=1 ttl=111 time=3.93 ms
64 bytes from waw02s06-in-f14.1e100.net (216.58.209.78): icmp_seq=2 ttl=111 time=6.80 ms
64 bytes from waw02s06-in-f14.1e100.net (216.58.209.78): icmp_seq=3 ttl=111 time=6.92 ms

--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 3.930/5.886/6.920/1.383 ms


Excluímos os contêineres

In [12]:
!docker rm ping_localhost ping_google

ping_localhost
ping_google


### O contexto do `build`

Vamos criar uma pasta chamada `dockerfile_context`.

In [58]:
!mkdir dokerfile_contexto

Agora, criamos dois arquivos nele, um `test.txt` e o `Dockerfile`.

In [59]:
!touch dokerfile_contexto/Dockerfile dokerfile_contexto/text.txt

Modifique o Dockerfile e adicione o seguinte

``` docker
DE ubuntu:trusty
COPIAR [".", "/"]
```

Isso fará com que seja copiado para a imagem tudo o que você tem na pasta em que o `Dockerfile` está localizado. Compilar a imagem

In [60]:
!docker build -t ubuntu:contexto ./dokerfile_contexto

Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM ubuntu:trusty
 ---> 13b66b487594
Step 2/2 : COPY [".", "/"]
 ---> 3ab79fdce389
Successfully built 3ab79fdce389
Successfully tagged ubuntu:contexto

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


Vamos ver o que há dentro do contêiner

In [63]:
!docker run --name ls ubuntu:contexto ls

Dockerfile
bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
text.txt
tmp
usr
var


Como podemos ver, há o arquivo `text.txt`. Mas talvez dentro da pasta que está no mesmo diretório que o `Dockerfile` existam arquivos ou pastas que não queremos que sejam copiados na imagem, por qualquer motivo, então, assim como no git temos o `.gitignore`, no docker temos o `.dockerignore`, onde colocamos os arquivos ou pastas que não queremos que sejam levados em consideração ao compilar.

Portanto, criamos um arquivo `.dockerignore`.

In [62]:
!touch dokerfile_contexto/.dockerignore

Dentro dela, adicionamos o `text.txt` e, a propósito, o `Dockerfile` que não precisamos dentro da imagem.

*.dockerignore*:
```
Dockerfile
text.txt
```

Excluímos o contêiner que criamos, compilamos novamente e vemos o que está dentro do contêiner.

In [67]:
!docker rm ls

ls


In [71]:
!docker build -t ubuntu:contexto ./dokerfile_contexto

Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM ubuntu:trusty
 ---> 13b66b487594
Step 2/2 : COPY [".", "/"]
 ---> 7a6689546da4
Successfully built 7a6689546da4
Successfully tagged ubuntu:contexto

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them


In [72]:
!docker run --name ls ubuntu:contexto ls

bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var


Vemos que agora nem o `Dockerfile`, nem o `text.txt` estão lá. Excluímos o contêiner

In [73]:
!docker rm ls

ls


### Construção em vários estágios

No final de um desenvolvimento, não queremos que todo o código esteja na imagem a ser enviada para a produção.

Podemos dividir o `dockerfile` em dois, por exemplo, o `developer.Dockerfile` e o `production.Dockerfile`, onde no desenvolvimento haverá mais coisas do que na produção. Ao compilá-los, usando a opção `f`, escolhemos o `dockerfile` que queremos usar

``` bash
docker build -t <tag> -f developer.Dockerfile
docker build -t <tag> -f production.Dockerfile
```

Mas para evitar ter que criar dois arquivos `Dockerfile`, o docker criou o `multi stage buils`. Com um único `Dockerfile`, resolveremos o problema

Crie a pasta onde salvaremos o `Dockerfile`.

In [2]:
!mkdir docker_multi_stage

Dentro dele, criamos o arquivo `Dockerfile`.

In [3]:
!cd docker_multi_stage && touch Dockerfile

Editamos o arquivo inserindo o seguinte

``` dockerfile
# Etapa 1: gerar o executável com Python baseado no Alpine
DE python:3.9-alpine como estágio de compilação
WORKDIR /app
# Instalar dependências para o PyInstaller
Executar apk add --no-cache gcc musl-dev libc-dev
# Gerar hello.py
RUN echo 'print("Hello from Alpine!")' > hello.py
# Instalar o PyInstaller
Execute o pip install pyinstaller
# Use o PyInstaller para criar um executável autônomo
EXECUTAR pyinstaller --onefile hello.py

# Etapa 2: Executar o executável em uma imagem do Alpine
DE alpine:latest
WORKDIR /app
# Copie o executável do estágio de compilação
COPY --from=build-stage /app/dist/hello .
# Comando padrão para executar o executável
CMD ["./hello"]
```

Como você pode ver, o `Dockerfile` é dividido em dois, de um lado trabalhamos com a imagem `python:3.9-alpine` que é chamada de `build-stage`. E, do outro lado, trabalhamos com a imagem `alpine:latest`, que é uma imagem muito leve do Linux e é muito utilizada na produção.

Nós o compilamos

In [10]:
!docker build -t maximofn/multistagebuild:latest ./docker_multi_stage

[+] Building 0.0s (0/2)                                          docker:default


[+] Building 0.2s (4/6)                                          docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 722B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/alpine:latest           0.1s
 => [internal] load metadata for docker.io/library/python:3.9-alpine       0.1s
...
 => CACHED [stage-1 3/3] COPY --from=build-stage /app/dist/hello .         0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:7fb090d1495d00e892118b6bc3c03400b63a435fd4703  0.0s
 => => naming to docker.io/maximofn/multistagebuild:latest                 0.0s


Se olharmos agora para as imagens que temos

In [11]:
!docker image ls

REPOSITORY                 TAG       IMAGE ID       CREATED         SIZE
maximofn/multistagebuild   latest    7fb090d1495d   8 minutes ago   13.6MB


Podemos ver a imagem que acabamos de criar e ela pesa apenas 13,6 MB. Vamos baixar a imagem do Python para ver quanto ela pesa

In [12]:
!docker pull python:3.9-alpine

3.9-alpine: Pulling from library/python

a8db6415: Already exists 
d5e70e42: Already exists 
3fe96417: Already exists 
aa4dddbb: Already exists 
518be9f7: Already exists Digest: sha256:6e508b43604ff9a81907ec17405c9ad5c13664e45a5affa2206af128818c7486
Status: Downloaded newer image for python:3.9-alpine
docker.io/library/python:3.9-alpine


In [13]:
!docker image ls

REPOSITORY                 TAG          IMAGE ID       CREATED         SIZE
maximofn/multistagebuild   latest       7fb090d1495d   9 minutes ago   13.6MB
python                     3.9-alpine   6946662f018b   9 days ago      47.8MB


Podemos ver que, enquanto nossa imagem pesa apenas 13,6 MB, a imagem python com a qual ele criou o aplicativo pesa 47,8 MB. Portanto, podemos tirar duas conclusões: com a primeira imagem, a do python, ele criou o aplicativo, gerou o executável e esse executável é o que usamos na segunda imagem, a do alpine. Também podemos ver que, embora a primeira imagem usada seja a imagem python, ela não foi baixada em nosso sistema, pois tivemos que baixá-la nós mesmos.

Tudo o que resta é experimentá-lo

In [14]:
!docker run --rm --name multi_stage_build maximofn/multistagebuild

Hello from Alpine!


Funciona!

### Compilações multiarquitetura

Suponha que queiramos criar uma imagem que será executada em um computador e em um Raspberry. O computador provavelmente tem um micro com arquitetura AMD64, enquanto o Raspberry tem um micro com arquitetura ARM. Portanto, não podemos criar a mesma imagem para ambos, ou seja, quando criamos uma imagem, nós a criamos com um `Dockerfile` que geralmente começa assim

``` Dockerfile
DE ...
```

Portanto, o `Dockerfile` da imagem do computador poderia começar assim

``` Dockerfile
DE ubuntu:latest
```

Já o de framboesa poderia começar assim

``` Dockerfile
DE arm64v8/ubuntu:latest
```

Teríamos que criar dois arquivos `Dockerfile`, compilá-los e, no computador, usar uma imagem e, na impressora, usar outra.

Para não ter que ficar olhando a arquitetura do computador e ver qual imagem temos que usar o Docker eu crio o `manifest`, que como o próprio nome indica é um manifesto que indica dependendo de qual arquitetura de micro temos usa uma imagem ou outra.

Então, vamos ver como fazer isso

Primeiro, criamos uma pasta na qual criaremos nossos arquivos `Dockerfile`.

In [1]:
!mkdir docker_multi_arch

Agora, criamos os dois dockerfiles

In [2]:
!cd docker_multi_arch && touch Dockerfile_arm64 Dockerfile_amd64

Escrevemos a partir do `Dockerfile` para AMD64

In [4]:
!cd docker_multi_arch && echo "FROM ubuntu:20.04" >> Dockerfile_amd64 && echo "CMD echo 'Hello from amd64'" >> Dockerfile_amd64

In [30]:
!cd docker_multi_arch && echo "FROM arm64v8/ubuntu:latest" >> Dockerfile_arm && echo "CMD echo 'Hello from ARM'" >> Dockerfile_arm

Agora, compilamos as duas imagens

In [6]:
!cd docker_multi_arch && docker build -t maximofn/multiarch:amd64 -f Dockerfile_amd64 .

[+] Building 0.0s (0/1)                                          docker:default
[+] Building 0.2s (2/3)                                          docker:default
 => [internal] load build definition from Dockerfile_amd64                 0.1s
 => => transferring dockerfile: 89B                                        0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04            0.1s
[+] Building 0.3s (2/3)                                          docker:default
 => [internal] load build definition from Dockerfile_amd64                 0.1s
 => => transferring dockerfile: 89B                                        0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.

In [31]:
!cd docker_multi_arch && docker build -t maximofn/multiarch:arm -f Dockerfile_arm .

[+] Building 0.0s (0/1)                                          docker:default


[+] Building 0.2s (2/3)                                          docker:default
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile_arm                   0.0s
 => => transferring dockerfile: 94B                                        0.0s
 => [internal] load metadata for docker.io/arm64v8/ubuntu:latest           0.1s
[+] Building 0.3s (2/3)                                          docker:default
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile_arm                   0.0s
 => => transferring dockerfile: 94B                                        0.0s
 => [internal] load metadata for docker.io/arm64v8/ubuntu:latest           0.3s
[+] Building 0.5s (2/3)                 

Vejamos que temos as imagens compiladas ods

In [32]:
!docker image ls

REPOSITORY           TAG       IMAGE ID       CREATED       SIZE
maximofn/multiarch   arm       a9732c198875   4 weeks ago   69.2MB
maximofn/multiarch   amd64     5b612c83025f   6 weeks ago   72.8MB


Vemos que compilamos as duas imagens. Para criar um manifesto, primeiro precisamos fazer upload das imagens para o docker hub, portanto, fazemos upload delas

In [10]:
!docker push maximofn/multiarch:amd64

The push refers to repository [docker.io/maximofn/multiarch]

82bdeb5f: Mounted from library/ubuntu amd64: digest: sha256:30e820f2a11a24ad4d8fb624ae485f7c1bcc299e8cfc72c88adce1acd0447e1d size: 529


In [34]:
!docker push maximofn/multiarch:arm

The push refers to repository [docker.io/maximofn/multiarch]



eda53374: Layer already exists arm: digest: sha256:6ec5a0752d49d3805061314147761bf25b5ff7430ce143adf34b70d4eda15fb8 size: 529


Se eu acessar meu hub do docker, verei que minha imagem `maximofn/multiarch` tem as tags `amd64` e `arm`.

![docker_multi_arch_tags](https://maximofn.com/wp-content/uploads/2023/09/docker_multi_arch_tags.png)

Agora, vamos criar o `manifesto` com base nessas duas imagens

In [36]:
!docker manifest create maximofn/multiarch:latest maximofn/multiarch:amd64 maximofn/multiarch:arm

Created manifest list docker.io/maximofn/multiarch:latest


Depois de criadas, precisamos indicar as arquiteturas de CPU às quais cada uma corresponde.

In [37]:
!docker manifest annotate maximofn/multiarch:latest maximofn/multiarch:amd64 --os linux --arch amd64

In [38]:
!docker manifest annotate maximofn/multiarch:latest maximofn/multiarch:arm64 --os linux --arch arm64

manifest for image maximofn/multiarch:arm64 does not exist in maximofn/multiarch:latest


Depois de criado e anotado, podemos fazer upload do `manifest` para o hub do docker

In [39]:
!docker manifest push maximofn/multiarch:latest

sha256:1ea28e9a04867fe0e0d8b0efa455ce8e4e29e7d9fd4531412b75dbd0325e9304


Se eu observar as tags na minha imagem `maximofn/multiarch` agora, também verei a tag `latest`.

docker_multi_arch_tags_manifest](https://maximofn.com/wp-content/uploads/2023/09/docker_multi_arch_tags_manifest.png)

Agora, se eu quiser usar minha imagem a partir de uma máquina com CPU AMD64 ou ARM, ao fazer `FROM maximofn/multiarch:latest`, o docker verificará a arquitetura da CPU e puxará a tag `amd64` ou a tag `arm`. Vejamos, se eu executar a imagem em meu computador, obterei

In [29]:
!docker run maximofn/multiarch:latest

Unable to find image 'maximofn/multiarch:latest' locally


latest: Pulling from maximofn/multiarch
Digest: sha256:7cef0de10f7fa2b3b0dca0fbf398d1f48af17a0bbc5b9beca701d7c427c9fd84
Status: Downloaded newer image for maximofn/multiarch:latest
Hello from amd64


Como não o tem, ele faz o download e, em seguida, aparece o texto `Hello from amd64`, pois a CPU do meu computador tem arquitetura AMD64.

Se agora eu me conectar via ssh a um raspberry pi e tentar a mesma coisa, obtenho

````bash
raspiberry@raspberrypi:~ $ docker run maximofn/multiarch:latest
    Não foi possível localizar a imagem 'maximofn/multiarch:latest' localmente
    mais recente: Extraindo do maximofn/multiarch
    Digest: sha256:1ea28e9a04867fe0e0d8b0efa455ce8e4e29e7d9fd4531412b75dbd0325e9304
    Status: Imagem mais recente baixada para maximofn/multiarch:latest
    Olá da ARM
```

Hello from ARM" aparece porque o Raspberry tem uma microarquitetura ARM.

Como você pode ver, cada máquina baixou a imagem de que precisava.

### Correção da gravação de Dockerfiles avançados

Já vimos como escrever dockerfiles corretamente, mas há mais uma coisa que podemos fazer agora que conhecemos a compilação em vários estágios: criar um contêiner para criar o executável e outro menor para executá-lo

Chegamos à conclusão de que um bom dockerfile poderia ser este

``` Dockerfile
DE python:3.9.18-alpine
WORKDIR /sourceCode/sourceApp
COPY ./sourceCode/sourceApp .
CMD ["python3", "app.py"]
```

Agora, criaremos um executável em um contêiner do construtor e o executaremos em um contêiner menor.

``` dockerfile
FROM python:3.9.18-alpine as builder
WORKDIR /sourceCode/sourceApp
Execute o apk add --no-cache gcc musl-dev libc-dev && pip install pyinstaller
COPY ./sourceCode/sourceApp .
EXECUTAR pyinstaller --onefile app.py

DE alpine:3.18.3
WORKDIR /sourceCode/sourceApp
COPY --from=builder /sourceCode/sourceApp/dist/app .
CMD ["./app"]
```

Criamos o código python no caminho necessário

In [29]:
!mkdir multistagebuild/sourceCode
!mkdir multistagebuild/sourceCode/sourceApp
!touch multistagebuild/sourceCode/sourceApp/app.py
!echo 'print("Hello from Alpine!")' > multistagebuild/sourceCode/sourceApp/app.py

Agora, compilamos a imagem

In [30]:
!docker build -t maximofn/multistagebuild:alpine-3.18.3 ./multistagebuild

[+] Building 0.0s (0/0)                                          docker:default
[+] Building 0.0s (0/1)                                          docker:default
[+] Building 0.2s (3/5)                                          docker:default
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 357B                                       0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/alpine:3.18.3           0.1s
 => [internal] load metadata for docker.io/library/python:3.9.18-alpine    0.1s
 => [auth] library/alpine:pull token for registry-1.docker.io              0.0s
[+] Building 0.3s (3/5)                                          docker:default
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 357B    

Nós o executamos

In [31]:
!docker run --rm --name multi_stage_build maximofn/multistagebuild:alpine-3.18.3

Hello from Alpine!


A imagem `maximofn/multistagebuild:alpine-3.18.3` pesa apenas 13,6 MB

### Diferença entre RUN, CMD e ENTRYPOINT

#### RUN

O comando `RUN` é o comando mais simples, ele simplesmente executa um comando no momento da compilação da imagem. Por exemplo, se quisermos instalar um pacote na imagem, faremos isso com o `RUN`.

Portanto, é importante ressaltar que o `RUN` é executado no momento da compilação da imagem, e não quando o contêiner é executado.

#### CMD

O comando `CMD` é o comando que é executado quando o contêiner é executado. Por exemplo, se quisermos que o contêiner execute um comando quando for executado, faremos isso com o `CMD`. Por exemplo, se tivermos um aplicativo python em um contêiner, com `CMD` podemos dizer a ele para executar o aplicativo python quando o contêiner for executado.

Dessa forma, quando o contêiner for criado, o aplicativo python será executado. Ou seja, se fizermos `docker run <image>`, ele executará o aplicativo python. Mas o `CMD` nos permite substituir o comando que é executado quando o contêiner é levantado, ou seja, se fizermos `docker run <image> bash`, ele executará `bash` em vez do aplicativo python.

#### ENTRYPOINT

O comando `ENTRYPOINT` é semelhante ao comando `CMD`, mas com uma diferença: o `ENTRYPOINT` não se destina a ser sobrescrito. Ou seja, se tivermos um aplicativo python em um contêiner, com o `ENTRYPOINT` podemos dizer a ele para executar o aplicativo python quando o contêiner for executado. Mas se fizermos `docker run <image> bash`, ele executará o aplicativo python, não o `bash`.

Um uso muito comum do `ENTRYPOINT` é quando queremos que o contêiner seja um executável, por exemplo, se quisermos que o contêiner seja um executável de uma versão do python que não temos em nosso host, porque, por exemplo, queremos testar a nova versão do python que foi lançada, poderíamos fazer

``` Dockerfile
DE python:3.9.18-alpine
ENTRYPOINT ["python3"]
```

Dessa forma, quando o contêiner for levantado, o python será executado. Ou seja, se fizermos `docker run <image>`, ele executará o python. Mas o `ENTRYPOINT` nos permite sobrescrever o comando que é executado quando o contêiner é levantado, ou seja, se fizermos `docker run <image> myapp.py`, ele executará `python3 myapp.py` dentro do contêiner. Dessa forma, podemos testar nosso aplicativo python na nova versão do python.

### Docker no Docker

Suponhamos que tenhamos contêineres que precisem levantar ou desligar outros contêineres. Isso é feito da seguinte maneira

Como no Linux tudo é um arquivo e o host se comunica com o docker por meio de um soquete. Portanto, para o Linux, esse soquete é um arquivo. Portanto, um contêiner que montar esse soquete como um arquivo poderá se comunicar com o docker.

Primeiro, vamos montar um contêiner com o ubuntu

In [1]:
!docker run -d --name ubuntu ubuntu:latest tail -f /dev/null

144091e4a3325c9068064ff438f8865b40f944af5ce649c7156ca55a3453e423


Vamos montar o contêiner que poderá se comunicar com o docker montando a pasta `/var/run/docker.sock`.

``` bash
$ docker run -it --rm --name main -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.12

```

Nós nos colocamos dentro de um contêiner e, se estivermos dentro, executamos o `docker ps`

``` bash
# docker ps
ID DO CONTÊINER ID DO CONTÊINER IMAGE COMMAND CREATED STATUS PORTS NAMES
9afb778d6c20 docker:19.03.12 "docker-entrypoint.s..."   3 segundos atrás Up 2 segundos main
144091e4a332 ubuntu:latest "tail -f /dev/null" 19 seconds ago Up 18 seconds ubuntu
```

Como podemos ver, dentro da janela de encaixe, podemos ver os contêineres do host

Podemos executar um novo contêiner

``` bash
# docker run -d --name ubuntu_from_main ubuntu:latest tail -f /dev/null
362654a72bb0fb047c13968707a6f16b87fed7ce051eb5c1a146b15828589a1a

```

E se virmos os contêineres novamente

``` bash
# docker ps
ID DO CONTÊINER ID DO CONTÊINER IMAGE COMMAND CREATED STATUS PORTS NAMES
362654a72bb0 ubuntu:latest "tail -f /dev/null" 3 seconds ago Up 3 seconds ubuntu_from_main
9afb778d6c20 docker:19.03.12 "docker-entrypoint.s..."   Cerca de um minuto atrás Up Cerca de um minuto atrás
144091e4a332 ubuntu:latest "tail -f /dev/null" 2 minutes ago Up Cerca de um minuto ubuntu
```

Mas se agora executarmos um novo terminal de host, veremos o contêiner criado dentro do contêiner.

In [4]:
!docker ps

CONTAINER ID   IMAGE             COMMAND                  CREATED              STATUS              PORTS     NAMES
362654a72bb0   ubuntu:latest     "tail -f /dev/null"      About a minute ago   Up About a minute             ubuntu_from_main
9afb778d6c20   docker:19.03.12   "docker-entrypoint.s…"   3 minutes ago        Up 3 minutes                  main
144091e4a332   ubuntu:latest     "tail -f /dev/null"      3 minutes ago        Up 3 minutes                  ubuntu


Tudo o que fizermos no contêiner `main` será refletido no host.

Isso tem a vantagem de permitir a instalação de programas em um contêiner que tenha acesso ao host, de modo que não seja necessário instalá-los no host. Por exemplo, [dive](https://github.com/wagoodman/dive) é uma ferramenta para explorar contêineres, mas se você não quiser instalá-la no host, poderá instalá-la em um contêiner com acesso ao host, de modo que, a partir desse contêiner `principal`, você poderá explorar o restante dos contêineres sem precisar instalá-la no host.