huggingface_svg_path='icons/hf-logo-pirate.svg'
github_svg_path='icons/github-brands-solid.svg'
linkedin_svg_path='icons/linkedin-brands-solid.svg'
x_svg_path='icons/square-x-twitter-brands-solid.svg'
kaggle_svg_path='icons/kaggle-brands-solid.svg'
facebook_svg_path='icons/facebook-brands-solid.svg'
instagram_svg_path='icons/instagram-brands-solid.svg'
tiktok_svg_path='icons/tiktok-brands-solid.svg'
twitch_svg_path='icons/twitch-brands-solid.svg'
youtube_svg_path='icons/youtube-brands-solid.svg'
curriculum_svg_path='icons/cv-solid.svg'
spain_flag_svg_path='icons/spain-flag.svg'
united_states_flag_svg_path='icons/united-states-flag.svg'
brazil_flag_svg_path='icons/brazil-flag-optimized.svg'

huggingface_link='https://huggingface.co/Maximofn'
github_link='http://github.com/maximofn'
linkedin_link='http://linkedin.com/in/MaximoFN/'
x_link='https://x.com/Maximo_fn'
kaggle_link='http://kaggle.com/maximofn'
facebook_link='https://www.facebook.com/profile.php?id=100085177670661'
instagram_link='https://www.instagram.com/maximo__fn/'
tiktok_link='https://www.tiktok.com/@maximo__fn'
twitch_link='https://www.twitch.tv/maximofn/'
youtube_link='https://www.youtube.com/channel/UCdQwg2JU_fWRsHn3yIlf3tw'
curriculum_link='https://github.com/maximofn/maximofn/raw/main/Curriculum%20Vitae.pdf'

logo_path = 'icons/MFN-512x512.webp'

maximofn_photo_path = 'images/maximo-0014_resized_291x436.webp'
maximofn_photo_path = 'https://avatars.githubusercontent.com/u/53622795?v=4'

default_project_image_path = 'https://avatars.githubusercontent.com/u/53622795?v=4'