# Introducción a la terminal

## Formato del post

Para no tener que estar poniendo imágenes de la consola en cada acción que haga, he creado la siguiente función que recibe el comando de la terminal que queramos ejecutar y devuelve la salida que nos daría la terminal.

Unas veces usaré esta función, y otras usaré `!` antes de cada comando, que en notebooks quiere decir que vas a ejecutar un comando de la terminal

In [1]:
import subprocess
import os

last_directory = ''

def terminal(command, max_lines_output=None):
    global last_directory
    debug = False
    str = command.split()

    # Check if there are " or ' characters
    for i in range(len(str)):
        if debug:   print(f"i = {i}, str[i] = {str[i]}")
        if len(str[i]) > 0:
            if str[i][0] == '"' or str[i][0] == "'":
                for j in range(i+1,len(str)):
                    if debug:   print(f"\t j = {j}, str[j] = {str[j]}")
                    if str[j][-1] == '"' or str[j][-1] == "'":
                        for k in range(i+1,j+1):
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                            str[i] = str[i] + " " + str[k]
                            if debug:   print(f"\t\t k = {k}, str[i] = {str[i]}, str[k] = {str[k]}")
                        str[j:] = [""]
                        str[i] = str[i].replace('"','')
    
    # Remove empty strings
    str = [x for x in str if x != ""]
    if debug:
        print(str)
        return
    if str[0] == "cd":
        last_dir = os.getcwd()
        if len(str) == 1:
            os.chdir('/home/wallabot')
        else:
            if str[1] == "-":
                os.chdir(last_directory)
            else:
                os.chdir(str[1])
        last_directory = last_dir
    else:
        result = subprocess.run(str, stdout=subprocess.PIPE).stdout.decode('utf-8')
        if max_lines_output is not None:
            result_split = result.split('\n')
            print('\n'.join(result_split[:max_lines_output]))
            print("\t ...")
            print('\n'.join(result_split[-5:]))
        else:
            print(result)

## Primeros pasos

### Primeros comandos para moverse por la terminal

El primer comando que vamos a ver es `ls` (`list directory`) que sirve para listar todos los archivos de la carpeta en la que estemos

In [2]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
test.html
test.ipynb



El segundo comando será `cd` (`change directory`) que nos permite cambiar el directorio

In [3]:
terminal('cd /home/wallabot/Documentos/')

Si ahora volvemos a usar `ls` para ver los archivos que tenemos, vemos que cambian

In [4]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Si a `cd`, en vez de darle el directorio al que nos queremos mover, le damos el caracter `-`, volverá al anterior directorio donde estaba

In [5]:
terminal('cd -')

Los comandos normalmente pueden recibir opciones (`flags`), que se introducen con el caracter `-`, por ejemplo veamos `ls -l` que nos devuelve la lista de archivos del directorio en el que estamos, pero con más información

In [6]:
terminal('ls -l')

total 14364
-rw-rw-r-- 1 wallabot wallabot   285898 nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    78450 nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot   484213 nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 10739185 nov 28 14:47 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot   119471 oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot     2660 sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot   699225 nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot   509125 sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot   156193 nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot    53094 oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot     4096 nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot    14775 sep 18 03:29 html.ipynb
drwxrwxr-x 3 wallabot wallabot     4096

Como vemos, tenemos cuantos bytes ocupa cada archivo, pero cuando tenemos archivos que ocupan mucho esto no es muy fácil de leer, así que podemos añadir la opción `h` (`human`) que nos da información más fácil de leer

In [7]:
terminal('ls -lh')

total 15M
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot  11M nov 28 14:47 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipynb
drwxrwxr-x 3 wallabot wallabot 4,0K nov 12 01:51 introduccion_python
-rw-rw-r-- 1 wallabo

Si queremos ver los archivos ocultos podemos usar la opción `a`, que nos mosntrará todos los archivos de un directorio

In [8]:
terminal('ls -lha')

total 15M
drwxrwxr-x 6 wallabot wallabot 4,0K nov 28 14:40 .
drwxrwxr-x 5 wallabot wallabot 4,0K oct  2 03:10 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot  11M nov 28 14:47 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:

Si lo que queremos es que nos los ordene por tamaño, podemo usar la opción `S`

In [9]:
terminal('ls -lhS')

total 15M
-rw-rw-r-- 1 wallabot wallabot  11M nov 28 14:47 2022-09-12 Introduccion a la terminal.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 473K nov 13 00:44 2021-06-15-Manejo-de-datos-con-Pandas.ipynb
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
-rw-rw-r-- 1 wallabot wallabot 280K nov 12 02:07 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 wallabot wallabot  77K nov 13 00:10 2021-04-23-Calculo-matricial-con-Numpy.ipynb
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
-rw-rw-r-- 1 wallabot wallabo

Si queremos que nos muestre los archivos ordenados alfabéticamente, pero al revés, debemos usar la opción `r`

In [10]:
terminal('ls -lhr')

total 15M
-rw-rw-r-- 1 wallabot wallabot 255K nov  9 01:13 test.ipynb
-rw-rw-r-- 1 wallabot wallabot 287K nov  9 01:46 test.html
drwxrwxr-x 2 wallabot wallabot 4,0K ago 27 03:25 __pycache__
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 notebooks_translated
-rw-rw-r-- 1 wallabot wallabot 510K oct  2 04:33 movies.dat
-rw-rw-r-- 1 wallabot wallabot 436K oct  2 04:39 movies.csv
drwxrwxr-x 3 wallabot wallabot 4,0K nov 12 01:51 introduccion_python
-rw-rw-r-- 1 wallabot wallabot  15K sep 18 03:29 html.ipynb
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 14:39 html_files
-rw-rw-r-- 1 wallabot wallabot  52K oct  2 04:57 Expresiones regulares.ipynb
-rw-rw-r-- 1 wallabot wallabot 153K nov 27 04:21 Expresiones regulares.html
-rw-rw-r-- 1 wallabot wallabot 498K sep 22 16:48 Docker.ipynb
-rw-rw-r-- 1 wallabot wallabot 683K nov 27 04:16 Docker.html
-rw-rw-r-- 1 wallabot wallabot 2,6K sep 18 03:32 CSS.ipynb
-rw-rw-r-- 1 wallabot wallabot 117K oct  3 16:13 command-line-cheat-sheet.pdf
-rw-rw-r-- 1 walla

Si nos quisiéramos mover a la `home` con introducir solamente `cd` en la terminal nos llevará

In [11]:
terminal('cd')

Para obtener el directorio en el que estamos podemos usar `pwd` (`print working directory`)

In [12]:
terminal('pwd')

/home/wallabot



Podemos movernos mediante el comando `cd` mediante rutas relativas y mediante rutas absolutas. Por ejemplo, vamos a movernos a un directorio mediante una ruta absoluta

In [13]:
terminal('cd /home/wallabot/Documentos/')

In [14]:
terminal('pwd')

/home/wallabot/Documentos



In [15]:
terminal('ls')

aprendiendo-git.pdf
balena-etcher-electron-1.7.9-linux-x64
camerasIP
Documentacion
jetsonNano
kaggle
Libros
nerf
prueba.txt
pytorch
wallabot
web



Podemos movernos mediante rutas relativas si solo ponemos la dirección a partir del punto en el que nos encontramos

In [16]:
terminal('cd web')

In [17]:
terminal('pwd')

/home/wallabot/Documentos/web



También mediante rutas relativas podemos ir un directorio arriba mediante `..`

In [18]:
terminal('cd ..')

In [19]:
terminal('pwd')

/home/wallabot/Documentos



Si en vez de `..` ponemos `.` nos estamos refiriendo al directorio en el que nos encontramos ahora mismo, es decir, si ponemos `cd .` no nos moveremos, ya que le estamos diciendo a la terminal que vaya al directorio en el que estamos

In [20]:
terminal('cd .')

In [21]:
terminal('pwd')

/home/wallabot/Documentos



Vamos a movernos a una ruta en la que tenga archivos para mostrar el siguiente comando

In [22]:
terminal('cd web/portafolio/posts/')

In [23]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
__pycache__
test.html
test.ipynb



Si yo no sé qué tipo de archivo es alguno en particular, mediante el comando `file` puedo obtener una descripción

In [24]:
terminal('file 2021-02-11-Introduccion-a-Python.ipynb')

2021-02-11-Introduccion-a-Python.ipynb: UTF-8 Unicode text, with very long lines



### Manipulando archivos y directorios

Movámonos primero a la home

In [25]:
terminal('cd /home/wallabot/Documentos/')

Podemos ver toda la estructura de la carpeta en la que estamos mediante el comando `tree`

In [39]:
terminal('tree', 20)

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   │   ├── config.cpython-38.pyc
│   │   └── config.cpython-39.pyc
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── jetsonNano
│   ├── apuntes-Jetson-Nano
│   │   ├── 01 Cambiar el Swap a 4 GB.ipynb
│   │   ├── 02 Conectar por SSH a través del USB.ipynb
	 ...
        ├── upload_page.py
        └── utils.py

861 directories, 119656 files



Pero a la salida tenemos demasiadas líneas, y esto es porque `tree` es un comando que muestra todos los archivos desde la ruta en la que estamos, por lo que es un poco dificil de leer. Sin embargo, con la opción `L` podemos indicarle en cuantos niveles queremos que profundice

In [26]:
terminal('tree -L 2')

.
├── aprendiendo-git.pdf
├── balena-etcher-electron-1.7.9-linux-x64
│   └── balenaEtcher-1.7.9-x64.AppImage
├── camerasIP
│   ├── camerasIP.py
│   ├── camerasIP.sh
│   ├── config.py
│   ├── __pycache__
│   └── README.md
├── Documentacion
│   ├── Curriculum Vitae (5).pdf
│   ├── Firma Pris.PNG
│   └── Firma.png
├── jetsonNano
│   ├── apuntes-Jetson-Nano
│   ├── deepstream_apps
│   ├── deepstream_nano
│   └── Digital zoom
├── kaggle
│   └── hubmap
├── Libros
│   └── aprendiendo-git.pdf
├── nerf
│   └── instant-ngp
├── prueba.txt
├── pytorch
│   └── Curso_Pytorch
├── wallabot
│   ├── Microfono - Blue Yeti X
│   ├── placa base - Asus prime x570-p
│   └── Silla - Corsair T3 Rush
└── web
    ├── jupyter-to-html
    ├── jupyter-translator
    ├── portafolio
    └── wordpress_api_rest

25 directories, 11 files



Podemos ver que muestra que hay 25 directorios y 11 archivos, mientras que antes indicaba 51946 directorios, 507633 archivos

Si queremos crear un nuevo directorio podemos usar el comando `mkdir` (`make directory`) y un nombre

In [40]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/")

In [41]:
terminal('mkdir prueba')

In [42]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
test.html
test.ipynb



Si lo que queremos es crear un directorio con espacios en el nombre, tenemos que poner el nombre entre comillas

In [43]:
terminal('mkdir "directorio prueba"')

In [44]:
terminal('ls')

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
test.html
test.ipynb



Vamos a meternos dentro de la carpeta `prueba` que hemos creado, para seguir viendo ahí la terminal

In [45]:
terminal("cd prueba")

En caso que queramos crear un archivo, el comando que tenemos que usar es `touch`

In [46]:
terminal("touch prueba.txt")

In [47]:
terminal("ls")

prueba.txt



Si queremos copiar un archivo lo hacemos pediante el comando `cp` (`copy`)

In [48]:
terminal("cp prueba.txt prueba_copy.txt")

In [49]:
terminal("ls")

prueba_copy.txt
prueba.txt



Si lo que queremos es moverlo, lo que usamos es el comando `mv` (`move`)

In [50]:
terminal("mv prueba.txt ../prueba.txt")

In [51]:
terminal("ls")

prueba_copy.txt



In [52]:
terminal("ls ../")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
directorio prueba
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
test.html
test.ipynb



El comando `mv` también nos sirve para renombrar ficheros, ya que si lo que hacemos es moverlo en el mismo directorio, pero dándole otro nombre, al final eso es renombrar el archivo

In [53]:
terminal("mv prueba_copy.txt prueba_move.txt")

In [54]:
terminal("ls")

prueba_move.txt



Para borrar archivos o direcotrios usamos el comando `rm` (`remove`)

In [55]:
terminal("rm prueba_move.txt")

In [56]:
terminal("ls")

Si lo que queremos es eliminar un directorio con archivos dentro, debemos usar el flag `-r`.

In [57]:
terminal("cd ..")

In [64]:
terminal('rm -r "directorio prueba"')

In [65]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
prueba.txt
__pycache__
test.html
test.ipynb



Como puedes ver nunca pregunta si estamos seguros, para que pregunte hay que añadir el flag `-i` (`iteractive`)

Borramos el archivo `prueba.txt` creado

In [66]:
terminal("rm prueba.txt")

### Explorando el contenido de los archivos

Para no tener que abrir un archivo desde una interfaz gráfica tenemos varias formas. Voy a copiar un archivo de texto en esta carpeta lo primero

In [67]:
terminal("cd prueba")

In [68]:
terminal("cp ../2021-02-11-Introduccion-a-Python.ipynb .")

In [69]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb



El primer comando para poder ver dentro de un arhcivo de texto es `head`, que nos permite ver las primeras 10 líneas de un archivo, pero si se le mete el flag `-n` puedes indicar el número de líneas

In [70]:
terminal("head 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]



In [71]:
terminal("head -n 5 2021-02-11-Introduccion-a-Python.ipynb")

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {



En caso de querer ver las últimas líneas usamos `tail`

In [72]:
terminal("tail 2021-02-11-Introduccion-a-Python.ipynb")

    },
    "vscode": {
      "interpreter": {
        "hash": "d5745ab6aba164e1152437c779991855725055592b9f2bdb41a4825db7168d26"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



In [73]:
terminal("tail -n 5 2021-02-11-Introduccion-a-Python.ipynb")

    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Si queremos ver continuamente las últimas líneas de un archivo, por ejemplo, queremos estar monitorizando continuamente un archivo de LOG para ver eventos, añadimos el flag `-f`, esto hará que la terminal se quede continuamente comprobando el archivo, y cada vez que aparezca una nueva linea en el la mostrará

Por ejemplo si yo monitoreo el log de inicio de sesión en mi máquna

``` bash
$ tail -f /var/log/auth.log
Dec  1 16:27:22 wallabot gcr-prompter[1457]: Gcr: calling the PromptDone method on /org/gnome/keyring/Prompt/p2@:1.26, and ignoring reply
Dec  1 16:27:22 wallabot gnome-keyring-daemon[1178]: asked to register item /org/freedesktop/secrets/collection/login/10, but it's already registered
Dec  1 16:27:26 wallabot systemd-logind[835]: Watching system buttons on /dev/input/event28 (Logitech Wireless Mouse MX Master 3)
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: 10 second inactivity timeout, quitting
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: unregistering prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: disposing prompter
Dec  1 16:27:33 wallabot gcr-prompter[1457]: Gcr: finalizing prompter
Dec  1 16:27:34 wallabot polkitd(authority=local): Operator of unix-session:1 successfully authenticated as unix-user:wallabot to gain TEMPORARY authorization for action org.debian.apt.install-or-remove-packages for system-bus-name::1.96 [/usr/bin/python3 /usr/bin/update-manager --no-update --no-focus-on-map] (owned by unix-user:wallabot)
Dec  1 16:27:42 wallabot systemd-logind[835]: Watching system buttons on /dev/input/event30 (T9-R (AVRCP))
Dec  1 16:27:49 wallabot gnome-keyring-daemon[1178]: asked to register item /org/freedesktop/secrets/collection/login/2, but it's already registered
```

Vemos en las dos últimas líneas mi inicio de sesión cuando he encendido hoy mi ordenador

Ahora me conecto por ssh a mi propia máquina

``` bash
$ ssh localhost 
wallabot@localhost's password: 
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-53-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.


Se pueden aplicar 0 actualizaciones de forma inmediata.

Your Hardware Enablement Stack (HWE) is supported until April 2025.
*** System restart required ***
Last login: Sun May  8 02:18:09 2022 from 192.168.1.147
```

En la consola donde estaba monitorizando el inicio de sesión han aparecido dos nuevas líneas

``` bash
Dec  1 16:32:23 wallabot sshd[25647]: Accepted password for wallabot from 127.0.0.1 port 54668 ssh2
Dec  1 16:32:23 wallabot sshd[25647]: pam_unix(sshd:session): session opened for user wallabot by (uid=0)
Dec  1 16:32:23 wallabot systemd-logind[835]: New session 4 of user wallabot.
```

Y cuando cierro la sesión ssh aparecen otras dos líneas nuevas

``` bash
Dec  1 16:33:52 wallabot sshd[25647]: pam_unix(sshd:session): session closed for user wallabot
Dec  1 16:33:52 wallabot systemd-logind[835]: Session 4 logged out. Waiting for processes to exit.
Dec  1 16:33:52 wallabot systemd-logind[835]: Removed session 4.
```

Uno de los comandos más potentes para ver dentro de los archivos es `less`

In [74]:
terminal("less 2021-02-11-Introduccion-a-Python.ipynb", max_lines_output=20)

{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dsaKCKL0IxZl"
      },
      "source": [
        "# Introducción a Python"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ho_8zgIiI0We"
      },
      "source": [
        "## 1. Resumen"
      ]
    },
	 ...
  },
  "nbformat": 4,
  "nbformat_minor": 0
}



Al estar dentro de un cuaderno no se puede ver lo que ocurre realmente al usar `less` pero cuando lo usamos nos metemos en el documento, podemos movernos a través de el mediante las teclas, o con el ratón

Si queremos buscar algo dentro del docuento, escribimos el caracter `/` y lo que queramos buscar. Para cambiar entre las distintas instancias que ha encontrado pulsamos la tecla `n`, y si queremos volver hacia atrás en las búsquedas pulsamos `shift+n`

Para salir solo hay que pulsar `q`

Si lo queremos abrir con el editor por defecto del archivo tenemos que usar `xdg-open`

In [75]:
terminal("xdg-open 2021-02-11-Introducción-a-Python.ipynb")

Si lo que queremos es abrir la carpeta en la que estamos usamos `nautilus`

In [ ]:
terminal("nautilus")

Y si lo que queremos es que se abra en una ruta determinada se incluye la ruta

In [ ]:
terminal("nautilus ~")

Por último, un comando muy útil es `wc` (word count), que te muestra cuántas líneas, palabras y bits tiene un archivo

In [8]:
terminal("wc 2021-02-11-Introduccion-a-Python.ipynb")

 11678  25703 285898 2021-02-11-Introduccion-a-Python.ipynb



Como vemos, el archivo tiene 11678 líneas, 25703 palabras y ocupa 285898 bytes

### Qué es un comando

Un comando puede ser 4 cosas
 * Un programa ejecutable, estos normalmente se guardan en la ruta /usr/bin
 * Un comando de shell
 * Una función de shell
 * Un alias

Para ver a qué clase pertenece un comando usamos `type`

In [76]:
!type cd

cd is a shell builtin


In [77]:
!type mkdir

mkdir is /usr/bin/mkdir


In [78]:
!type ls

ls is /usr/bin/ls


#### ¿Qué es un alias?

Un alias es un comando que definimos nosotros, este se define mediante el comando `alias`. Por ejemplo, vamos a crear el alias `l` que lo que haga sea `ls -h`

In [80]:
!alias l='ls -l'

Cuando ejecutamos `l` nos muestra el resultado de `ls -h`

``` bash
$ l
2021-02-11-Introducción-a-Python.ipynb
```

Pero esto tiene el problema, que cuando cerremos la terminal desaparece el `alias`. Más adelante aprenderemos a crear `alias` permanentes

#### Ayuda de los comandos

Con muchos comandos de la shell, podemos obtener su ayuda mediante el comando `help`

``` bash
$ help cd
cd: cd [-L|[-P [-e]]] [dir]
    Modifica el directorio de trabajo del shell.
    
    Modifica el directorio actual a DIR.  DIR por defecto es el valor de la
    variable de shell HOME.
    
    La variable CDPATH define la ruta de búsqueda para el directorio que
    contiene DIR.  Los nombres alternativos de directorio en CDPATH se
    separan con dos puntos (:).  Un nombre de directorio nulo es igual que
    el directorio actual.  Si DIR comienza con una barra inclinada (/),
    entonces no se usa CDPATH.
    
    Si no se encuentra el directorio, y la opción del shell "cdable_vars"
    está activa, entonces se trata la palabra como un nombre de variable.
    Si esa variable tiene un valor, se utiliza su valor para DIR.
    
    Opciones:
      -L	fuerza a seguir los enlaces simbólicos: resuelve los enlaces
    		simbólicos en DIR después de procesar las instancias de ".."
      -P	usa la estructura física de directorios sin seguir los enlaces
    		simbólicos: resuelve los enlaces simbólicos en DIR antes de procesar
    		las instancias de ".."
      -e	si se da la opción -P y el directorio actual de trabajo no se
    		puede determinar con éxito, termina con un estado diferente de cero.
    
    La acción por defecto es seguir los enlaces simbólicos, como si se
    especificara "-L".
    ".." se procesa quitando la componente del nombre de la ruta inmediatamente
    anterior hasta una barra inclinada o el comienzo de DIR.
    
    Estado de Salida:
    Devuelve 0 si se cambia el directorio, y si $PWD está definido como
    correcto cuando se emplee -P; de otra forma es diferente a cero.
    ```

Otro comando es `man`, que hace referencia al manual de usuario

In [81]:
terminal("man ls", max_lines_output=20)

LS(1)                            User Commands                           LS(1)

NAME
       ls - list directory contents

SYNOPSIS
       ls [OPTION]... [FILE]...

DESCRIPTION
       List  information  about  the FILEs (the current directory by default).
       Sort entries alphabetically if none of -cftuvSUX nor --sort  is  speci‐
       fied.

       Mandatory  arguments  to  long  options are mandatory for short options
       too.

       -a, --all
              do not ignore entries starting with .

       -A, --almost-all
	 ...
       Full documentation at: <https://www.gnu.org/software/coreutils/ls>
       or available locally via: info '(coreutils) ls invocation'

GNU coreutils 8.30              September 2019                           LS(1)



Para salir pulsar `q`

Otro comando es `info`

In [82]:
terminal("info ls", max_lines_output=20)

File: coreutils.info,  Node: ls invocation,  Next: dir invocation,  Up: Directory listing

10.1 ‘ls’: List directory contents

The ‘ls’ program lists information about files (of any type, including
directories).  Options and file arguments can be intermixed arbitrarily,
as usual.

   For non-option command-line arguments that are directories, by
default ‘ls’ lists the contents of directories, not recursively, and
omitting files with names beginning with ‘.’.  For other non-option
arguments, by default ‘ls’ lists just the file name.  If no non-option
argument is specified, ‘ls’ operates on the current directory, acting as
if it had been invoked with a single argument of ‘.’.

   By default, the output is sorted alphabetically, according to the
locale settings in effect.(1)  If standard output is a terminal, the
output is in columns (sorted vertically) and control characters are
output as question marks; otherwise, the output is listed one per line
	 ...
‘--show-control-chars’
     Print

Para salir pulsar `q`

Otro comando es `whatis`

In [83]:
terminal("whatis ls")

ls (1)               - list directory contents



### Wildcards

Las wildcards son caracteres especiales que nos sirven para realizar búsquedas especiales. Por ejemplo, si quiero buscar todos los archivos que terminen en `.txt`. Vamos a crear unos cuantos archivos para verlas

In [84]:
terminal("touch file.txt dot.txt dot2.txt index.html datos1 datos123 Abc")

In [85]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html



Vamos a buscar ahora todos los archivos `.txt`

In [86]:
!ls *.txt

dot2.txt  dot.txt  file.txt


Vamos ahora a buscar todos los que empiecen por la palabra `datos`

In [87]:
!ls datos*

datos1	datos123


Pero qué pasa si en realidad lo que queremos es que nos muestre todos los archivos que empiecen por la palabra `datos` pero segido solo un números, tenemos que poner un signo de interrogación `?`

``` bash
$ ls datos?
datos1
```

Si lo que queremos es que tenga tres números, entonces tenemos que poner tres signos de interrogación `???`

``` bash
$ ls datos???
datos123
```

Si queremos que busque los archivos que empiecen por mayúsculas

``` bash 
$ ls [[:upper:]]*
Abc
```

Para los archivos que empiecen con minúsculas

``` bash
$ ls [[:lower:]]*
datos1  datos123  dot2.txt  dot.txt  file.txt  index.html
```

#### Clases

Mediante el usos de corchetes podemos crear clases, así si queremos buscar los archivos que empiecen por las letras `d` o `f` seguido de cualquier caracter

``` bash
$ ls [df]*
datos1  datos123  dot2.txt  dot.txt  file.txt
```

## Empezando a correr

### Redirecciones: como funciona la shell

Un comando funciona de la siguiente manera

![pipeline comando](https://ptgmedia.pearsoncmg.com/images/chap5_9780133927313/elementLinks/05fig02_alt.jpg)

Tiene un `standard input`, que por defecto es el texto que intorducimos por teclado, un `standard output`, que por defecto es el texto que sale por consola y un `standard error` que también es por defecto un texto que sale por consola, pero que tiene otro formato

Pero con el caracter `>` podemos modificar el `standard output` de un comando. Por ejemplo, si queremos listar con `ls` los archivos de la carpeta en la que estamos, pero no queremos que el resultado se imprima por pantalla, sino que se guarde en un archivo haríamos lo siguiente `ls > lista.txt`, esto escribe la lista en `lista.txt`, además si `lista.txt` no existe lo crea

In [88]:
!ls > lista.txt

Vemos que ha creado el archivo y vemos qué hay dentro

In [89]:
terminal("ls")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



In [90]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Vemos que dentro de `lista.txt` aparece `lista.txt`, eso es porque primero crea el archivo y luego ejecuta el comando

Hacemos lo mismo pero con la carpeta padre

In [91]:
!ls ../ > lista.txt

Si volvemos a ver dentro de `lista.txt`

In [92]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
test.html
test.ipynb



Vemos que se sobreescribe el contenido

Si lo que queremos es que se concatene el contenido debemos usar `>>`

In [93]:
!ls > lista.txt

In [94]:
!ls ../ >> lista.txt

In [95]:
terminal("cat lista.txt")

2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt
2021-02-11-Introduccion-a-Python.ipynb
2021-04-23-Calculo-matricial-con-Numpy.ipynb
2021-06-15-Manejo-de-datos-con-Pandas.ipynb
2022-09-12 Introduccion a la terminal.ipynb
command-line-cheat-sheet.pdf
CSS.ipynb
Docker.html
Docker.ipynb
Expresiones regulares.html
Expresiones regulares.ipynb
html_files
html.ipynb
introduccion_python
movies.csv
movies.dat
notebooks_translated
prueba
__pycache__
test.html
test.ipynb



Ahora si se ha concatenado la información

Esto es muy últil para crear archivos de log

#### Redirección del `standard error`

Si realizamos una operación incorrecta obtenemos un error, veamos que pasa al redireccionar un comando que da un error

In [96]:
!ls fjhdsalkfs > lista.txt

ls: no se puede acceder a 'fjhdsalkfs': No existe el archivo o el directorio


Como vemos ha dado un error, pero si ahora vemos dentro de `lista.txt`

In [97]:
terminal("cat lista.txt")

Vemos que el archivo está vacío, eso es porque no hemos redireccionado el `standard error` a `lista.txt`, sino el `standard output`. Como hemos visto en la imagen, hay dos standards de salida en un comando, el primero es el `standard output` y el segundo el `standard error`, por lo que para redireccionar el standard error hay que indicarlo mediante `2>`. Vamos ahora así

In [98]:
!ls kjhsfskjd 2> lista.txt

In [99]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Como vemos ahora si se ha redireccionado

Si queremos redireccionar los dos usamos lo siguiente

In [100]:
!ls kjhsfskjd > lista.txt 2>&1

Veamos dentro de `lista.txt`

In [101]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio



Si ahora ejecutamos un comando sin error

In [102]:
!ls . >> lista.txt 2>&1

Veamos dentro de `lista.txt` (**ojo**, ahora hemos concatenado)

In [103]:
terminal("cat lista.txt")

ls: no se puede acceder a 'kjhsfskjd': No existe el archivo o el directorio
2021-02-11-Introduccion-a-Python.ipynb
Abc
datos1
datos123
dot2.txt
dot.txt
file.txt
index.html
lista.txt



Como se puede ver, se han redirigido, tanto el `standard error`, como el `standard output` al mismo archivo

### Pipelines

Podemos crear pipelines haciendo que el `standard output` de un comando se convierta en el `standard input` de otro. Por ejemplo, vamos a hacer que la salida de `ls -lha` sea la entrada de `grep`, que lo veremos más adelante, pero es un comando para buscar.

In [104]:
!ls -lha |  grep -i "txt"

-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt


Como podemos ver lo que hemos hecho ha sido llevar la salida de `ls` a `grep` con el que hemos buscado algún archivo con `txt` en el nombre

### Operadores de control - encadenar comandos

#### Comandos de manera secuencial

Una forma de encadenar comandos de forma secuencial es separarlos mediante `;`. Esto crea distintos hilos para cada tarea

In [105]:
!ls; echo 'Hola'; cal

2021-02-11-Introduccion-a-Python.ipynb	datos123  file.txt
Abc					dot2.txt  index.html
datos1					dot.txt   lista.txt
Hola
   Noviembre 2022     
do lu ma mi ju vi sá  
       1  2  3  4  5  
 6  7  8  9 10 11 12  
13 14 15 16 17 18 19  
20 21 22 23 24 25 26  
27 28 29 30           
                      


Como podemos ver primero se ha ejecutado el comando `ls`, luego se ha impreso Hola gracias al comando `echo "Hola"` y por último se ha impreso un calendario gracias al comando `cal`

Vamos ahora a hacer otro ejemplo para ver que se ejecutan de manera secuencial

In [106]:
!echo "Before touch;"; ls -lha; touch secuential.txt; echo "After touch:"; ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:13 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:16 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-

Como se puede ver, en el primer `ls` no aparece `secuential.txt`, mientras que en el segundo sí. Eso quiere decir que los comandos se han ejecutado en orden, uno detrás de otro

#### Comandos de manera paralela

Si lo que queremos es que los comandos se ejecuten de manera paralela hay que usar el operador `&`, esto hará que se cree un nuevo proceso por cada comando

Veamos el ejemplo de antes

In [107]:
!rm secuential.txt

In [108]:
!echo "Before touch;" & ls -lha & touch secuential.txt & echo "After touch:" & ls -lha

Before touch;
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:23 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:23 secuential.txt
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:23 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:

Ahora se puede ver que no se han ejecutado secuencialmente, ya que primero se han ejecutado los `echo`s, que serán los que menos tarden, y después el resto

#### Comandos de manera condicional

##### And

Utilizando el operador `&&` un comando se ejecutará cuando el anterior se haya ejecutado satisfactoriamente

In [109]:
!rm secuential.txt

In [110]:
!echo "Before touch;" && ls -lha && touch secuential.txt && echo "After touch:" && ls -lha

Before touch;
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:24 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
After touch:
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:24 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-

Aquí podemos ver como se ha ejecutado uno detrás de otro, es decir, un comando no empieza hasta que el anterior acaba

Pero entonces, ¿cuál es la diferencia entre `;` y `&&`?

En el primero, el secuencial `;`, primero se ejecuta un comando y luego otro, pero para que se ejecute un comando da igual que el anterior se haya ejecutado satisfactoriamente

In [111]:
!rm prueba ; ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:24 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt


Como se puede ver primero se ejecuta `rm prueba`, da un error y aun así se ejecuta `ls -lha prueba`

En la manera condicional `&&`, si un comando no se ejecuta satisfactoriamente, el siguiente no se ejecuta

In [112]:
!rm prueba && ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio


Como se puede ver `ls -lha prueba` no se ejecuta ya que `rm prueba` a dado un error

##### Or

A diferencia del `&&`, el or ejecutará todos los procesos sea cual sea su resultado. Se ha de utilizar el operador `||`

In [113]:
!rm prueba || ls -lha

rm: no se puede borrar 'prueba': No existe el archivo o el directorio
total 292K
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 15:24 .
drwxrwxr-x 7 wallabot wallabot 4,0K nov 28 15:06 ..
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt


La diferencia entre este y `;` es que el `||` (or) no crea un nuevo hilo para cada comando

### Cómo se manejan los permisos

Cuando se listan los archivos de un directorio con el flag `-l` (long) aparecen unos símbolos al lado de  cada archivo

In [114]:
!mkdir subdirectorio

In [115]:
!ls -l

total 288
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 nov 28 15:28 subdirectorio


Esto nos da información de cada archivo

Primero veamos qué tipos de archivos hay
 * -: Archivo normal
 * d: Directorio
 * l: Link simbólico
 * b: Archivo de bloque especial. Son archivos que manejan la información de los bloques de datos como por ejemplo un USB

Después veremos los tipos de modo:

<table border="1">
	<header>
		<tr>
			<th scope="col" colspan="3">Dueño</th>
			<th scope="col" colspan="3">Grupo</th>
			<th scope="col" colspan="3">World</th>
		</tr>
	</header>
	<body>
		<tr>
			<th scope="row" colspan="3">rwx</th>
			<th scope="row" colspan="3">r-x</th>
			<th scope="row" colspan="3">r-x</th>
		</tr>
		<tr>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
			<th scope="row">1</th>
			<th scope="row">0</th>
			<th scope="row">1</th>
		</tr>
		<tr>
			<th scope="row" colspan="3">7</th>
			<th scope="row" colspan="3">5</th>
			<th scope="row" colspan="3">5</th>
		</tr>
	<body>
</table>

 * r: read
 * w: write
 * x: execute

Modo simbólico:
 * u: Solo para el usuario
 * g: Solo para el grupo
 * o: Solo para otros (world)
 * a: Para todos

### Modificando los permisos en la terminal

Creamos un nuevo archivo

In [116]:
terminal("cd subdirectorio")

In [117]:
!echo "hola mundo" > mitexto.txt

In [118]:
!cat mitexto.txt

hola mundo


Vamos a ver los permisos que tiene

In [119]:
!ls -l

total 4
-rw-rw-r-- 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt


Como vemos tiene permisos de lectura y escritura para mi usuario y el grupo, y solo permisos de lectura para el resto (world)

Para cambiar los permisos de un archivo usamos el comando `chmod` (change mode), donde tenemos que poner en octal, los permisos del usuario, luego los de grupo y por último los del resto.

In [120]:
!chmod 755 mitexto.txt

In [121]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt


Vemos que ahora mi usuario tiene permisos de lectura, escritura y ejecución, mientras que el grupo y el resto del mundo tiene permisos de lectura y ejecución

Vamos a quitar los permisos de lectura solo a mi usuario. Para cambiar solo los permisos de un usuario usamos el identificador simbólico, un `+` si queremos agregar permisos o un `-` si queremos quitarlos o un `=` si queremos restablecerlos y seguido del tipo de permiso

In [122]:
!chmod u-r mitexto.txt

In [123]:
!ls -l

total 4
--wxr-xr-x 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt


In [124]:
!cat mitexto.txt

cat: mitexto.txt: Permiso denegado


Como vemos, al quitar permisos de lectura para mi usuario, no podemos leer el archivo

Le volvemos a poner el permiso de lectura

In [125]:
!chmod u+r mitexto.txt

In [126]:
!ls -l

total 4
-rwxr-xr-x 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt


In [127]:
!cat mitexto.txt

hola mundo


Si queremos agregar o quitar permisos a más de un usuario lo hacemos separando cada permiso por una `,`

In [128]:
!chmod u-x,go=w mitexto.txt

In [129]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt


Como se puede ver, se le ha quitado el permiso de ejecución al usuario y se ha establecido el permiso de solo escritura para el grupo y el resto del mundo

Para saber quienes somos podemos usar el comando `whoami` (who am I)

In [130]:
!whoami

wallabot


Otra manera, que además da más información, es el comando `id`

In [131]:
!id

uid=1000(wallabot) gid=1000(wallabot) grupos=1000(wallabot),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),998(docker)


Este comando nos dice que nuestro id de usuario es el 1000, el id de grupo es el 1000 y que pertenecemos a los grupos wallabot, adm, cdrom, sudo, dip, plugdev, lpadmin, lxd, sambashare y docker

Si queremos cambiar de usuario usamos el comando `su` (switch user). Para según que usuario hay que usar `sudo` (superuser do)

``` bash
$ sudo su root
root@wallabot:/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio#
```

Como vemos cambia el propt y ahora indica que somos el usuario root

Vamos a la carpeta home

```bash
$ cd
root@wallabot:~# 
```

Pero en Linux hay una carpeta home por cada usuario, esto lo podemos ver si ejecutamos el comando `pwd`

```bash
$ pwd
/root
```

Voy a crear un archivo en la carpeta donde antes he creado el archivo *mitexto.txt*

```bash
$ touch /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
```

Vuelvo a cambiarme a mi usuario

```bash
$ su wallabot
wallabot@wallabot:/root$
```

Y me voy al directorio donde están los archivos que he creado

In [134]:
!cd /home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio

Vemos los archivos que hay y sus permisos

In [135]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt
-rw-r--r-- 1 root     root      0 nov 28 15:33 rootfile.txt


Como vemos el usuario y el grupo del archivo *rootfile.txt* es el usuario `root`

Si yo ahora que soy el usuario *wallabot* intento borrar el archivo `rootfile.txt`

In [136]:
!rm rootfile.txt

rm: ¿borrar el fichero regular vacío 'rootfile.txt'  protegido contra escritura? (s/n) ^C


Como vemos, nos pregunta si lo queremos borrar, ya que pertenece a otro usuario

### Modificar la contraseña de un usuario

Si quiero modificar la contraseña del usuario que tengo actualmente activo uso el comando `passwd` (password)

Primero compruebo qué usuario soy

```bash
$ whoami
wallabot
```

Y ahora probamos a cambiar la contraseña

```bash
$ passwd
Cambiando la contraseña de wallabot.
Contraseña actual de : 
Nueva contraseña: 
Vuelva a escribir la nueva contraseña
```

Como vemos pide la actual contraseña para poder cambiarla

### Links simbólicos

Podemos crear links simbólicos a una ruta determinada mediante el comando `ln` (link) seguido del flag `-s` (symbolic), el directorio y el nombre del link

In [137]:
!ln -s /home/wallabot/Documentos/web web

Si ahora listamos los archivos

In [138]:
!ls -l

total 4
-rw--w--w- 1 wallabot wallabot 11 nov 28 15:29 mitexto.txt
-rw-r--r-- 1 root     root      0 nov 28 15:33 rootfile.txt
lrwxrwxrwx 1 wallabot wallabot 29 nov 28 15:34 web -> /home/wallabot/Documentos/web


Vemos el link simbólico `web` que apunta a # ln: `/home/wallabot/Documentos/web:` no se permiten enlaces fuertes para directorios

Yo ahora me puedo ir a `web`

In [139]:
terminal("cd web")

In [140]:
!pwd

/home/wallabot/Documentos/web


### Configurar las variables de entorno

Con el comando `printenv` podemos ver todas las variables de entorno

In [141]:
!printenv

GJS_DEBUG_TOPICS=JS ERROR;JS LOG
VSCODE_CWD=/home/wallabot
LESSOPEN=| /usr/bin/lesspipe %s
CONDA_PROMPT_MODIFIER=(base) 
PYTHONIOENCODING=utf-8
USER=wallabot
VSCODE_NLS_CONFIG={"locale":"es","availableLanguages":{"*":"es"},"_languagePackId":"b07c40c9acb9e1d7b3ca14b06f814803.es","_translationsConfigFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/tcf.json","_cacheRoot":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es","_resolvedLanguagePackCoreLocation":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/6261075646f055b99068d3688932416f2346dd3b","_corruptedFile":"/home/wallabot/.config/Code/clp/b07c40c9acb9e1d7b3ca14b06f814803.es/corrupted.info","_languagePackSupport":true}
VSCODE_HANDLES_UNCAUGHT_ERRORS=true
MPLBACKEND=module://ipykernel.pylab.backend_inline
SSH_AGENT_PID=1344
XDG_SESSION_TYPE=x11
SHLVL=0
HOME=/home/wallabot
CHROME_DESKTOP=code-url-handler.desktop
CONDA_SHLVL=1
DESKTOP_SESSION=ubuntu
GIO_LAUNCHED_DESKTOP_FI

Para ver una variable de entorno en concreto podemos hacerlo mediante el comando `echo` seguido del símbolo `$` y el nombre de la variable

In [142]:
!echo $HOME

/home/wallabot


#### Modificar una variable de entorno para una sesión de terminal

Podemos modificar una variable de entorno para la sesión activa de terminal, por ejemplo, vamos a agregar una nueva ruta a la variable `PATH`. Primero vemos qué hay en ella

```bash
$ echo $PATH
/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Ahora añadimos un nuevo direcotorio

```bash
$ PATH=$PATH:"subdirectorio"
```

Volvemos a ver qué hay dentro de `PATH`

```bash
$ $ echo $PATH
/home/wallabot/anaconda3/bin:/home/wallabot/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:subdirectorio
```

Vemos que se ha añadido el directorio `subdirectorio`.

El problema de este método es que cuando abramos una nueva terminal no se mantendrá este cambio en `PATH`

#### Modificar una variable de entorno para todas las sesiones de terminal

Nos vamos a la carpeta home

In [143]:
terminal("cd /home/wallabot")

Aquí en el home listamos todos los archivos con el flag `-a` (all)

In [144]:
!ls -a

.		.eclipse		       .pki
..		Escritorio		       Plantillas
.afirma		.gitconfig		       .platformio
anaconda3	.gnupg			       .profile
.audacity-data	Imágenes		       .psensor
.bash_history	.ipython		       Público
.bash_logout	.java			       .python_history
.bashrc		.jupyter		       snap
.cache		.lesshst		       .ssh
.conda		Lightworks		       .sudo_as_admin_successful
.config		.Lightworks.thereCanBeOnlyOne  .thunderbird
.cortex-debug	.local			       Vídeos
.cyberghost	logiops			       .vnc
.dbus		.MCTranscodingSDK	       .vscode
Descargas	.mozilla		       .wget-hsts
.docker		Música
Documentos	.nv


Vemos que hay una archivo que se llama `.bashrc`, este archivo es el archivo que tiene la configuración de nuestro bash

In [145]:
terminal("cat .bashrc", max_lines_output=3)

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
	 ...
fi
unset __conda_setup
# <<< conda initialize <<<




Este archivo es el que configura la terminal cada vez que se abre una nueva, por lo que si en el editamos la variable `PATH`, este cambio se mantendrá para todas las ventanas nuevas de terminal que abramos

Para modificar la variable `PATH` dentro del archivo de configuración tenemos que agregar la siguiente linea al archivo

```
PATH=$PATH:"subdirectorio"
```

Ya vimos cómo crear alias de comandos, pero también pasaba que se perdían cada vez que cerrábamos una sesión de terminal, para que esto no pase, los añadimos tambien al archivo de configuración `.bashrc`. Por ejemplo, en mi caso he añadido las siguientes línea

```
alias ll='ls -l'
alias la='ls -a'
alias lh='ls -h'
alias lha='ls -lha'
```

### Comandos de búsqueda

#### Búsqueda de binarios con `which`

El primer comando de busqueda que vamos a ver es `which` que nos permite encontrar la ruta de los binarios

In [146]:
!which python

/home/wallabot/anaconda3/bin/python


Sin embargo, si buscamos algo que no esté en alguna de las rutas de PATH, `which` no será capaz de decirnos la ruta

In [147]:
!which cd

#### Búsqueda de archivos con `find`

Para buscar un archivo con find tenemos que indicarle desde qué ruta queremos buscar el archivo, seguido del flag `-name` y el nombre del archivo que queremos buscar

In [151]:
!find ~ -name "2021-02-11-Introduccion-a-Python.ipynb"

/home/wallabot/Documentos/web/portafolio/posts/prueba/2021-02-11-Introduccion-a-Python.ipynb
/home/wallabot/Documentos/web/portafolio/posts/2021-02-11-Introduccion-a-Python.ipynb


Como vemos está en su directorio más la copia que he creado en este notebook y la he guardado en la carpeta `prueba`

Una cosa muy poderosa de `find` es que podemos usar `wildcards`, por ejemplo si quiero buscar todos los archivos de texto de mi carpeta `Documentos`

In [152]:
terminal("find ~/Documentos/ -name *.txt")

In [154]:
!find ~/Documentos/web/ -name *.txt

/home/wallabot/Documentos/web/portafolio/posts/prueba/lista.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/dot2.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/secuential.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/mitexto.txt
/home/wallabot/Documentos/web/portafolio/posts/prueba/file.txt
/home/wallabot/Documentos/web/wordpress_api_rest/page.txt


Podemos especificar el tipo de archivo con el flag `-type`. Solo admite dos tipos `f` para archivos y `d` para directorios

In [157]:
!find ~/Documentos/nerf -name image*

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [161]:
!find ~/Documentos/nerf -name image* -type d

/home/wallabot/Documentos/nerf/instant-ngp/configs/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/benchmarks/image
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/cutlass/media/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/data/images
/home/wallabot/Documentos/nerf/instant-ngp/dependencies/dlss/NVIDIAImageScaling/samples/media/images
/home/wallabot/Documentos/nerf/instant-ngp/data/nerf/fox/images
/home/wallabot/Documentos/nerf/instant-ngp/data/image


In [160]:
!find ~/Documentos/nerf -name image* -type f

/home/wallabot/Documentos/nerf/instant-ngp/dependencies/tiny-cuda-nn/dependencies/fmt/doc/bootstrap/mixins/image.less


Si queremos filtrar por el tamaño del archivo podemos usar el flag `-size`, por ejemplo, si queremos buscar todos los archivos de más de 200 MB

In [162]:
!find ~/Documentos/ -type f -size +200M

/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_final_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/efficientnet-b7-dcc49843.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/14_resnet152_early_stopping.pth
/home/wallabot/Documentos/kaggle/hubmap/models/12_efficientnet-b7_best_model.pth
/home/wallabot/Documentos/kaggle/hubmap/models/13_efficientnet-b7_best_model.pth


Si queremos realizar operaciones tras la búsqueda usamos el flag `-exec`

Por ejemplo voy a buscar todas las carpetas con el nombre `subdirectorio`

In [163]:
!find ~/ -name subdirectorio -type d

/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio


Puedo hacer que se borren con el flag `-exec`

In [164]:
!find ~/ -name subdirectorio -type d -exec rm -r {} \;

rm: ¿borrar el fichero regular vacío '/home/wallabot/Documentos/web/portafolio/posts/prueba/subdirectorio/rootfile.txt'  protegido contra escritura? (s/n) ^C


In [165]:
!find ~/ -name subdirectorio -type d

### Comando de búsqueda `grep`

`grep` es un comando de búsqueda muy potente, por eso le dedicamos un apartado a el solo. El comando `grep` utiliza las expresiones regulares por lo que si quieres aprender de ellas te dejo un enlace a un [post](https://maximofn.com/expresiones-regulares) donde las explico

Vamos a empezar a ver la potencia de este comando, vamos a buscar todas las veces que aparece el texto `MaximoFN` dentro del archivo `2021-02-11-Introduccion-a-Python.ipynb`

In [168]:
terminal("cd /home/wallabot/Documentos/web/portafolio/posts/prueba")

In [169]:
!grep MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
            "MaximoFN\n"
            "MaximoFN\n"
              "b'MaximoFN'"
        "byte = b\"MaximoFN\"\n",
              "b'MaximoFN

Sin embargo si hacemos la misma búsqueda para el texto `maximofn`

In [170]:
!grep maximofn 2021-02-11-Introduccion-a-Python.ipynb

No aparece ningún resultado, esto es porque `grep` es `case sensitive` es decir busca el texto tal cual se lo has introducido, diferenciando mayúsculas y minúsculas. Si no queremos esto, tenemos que introducir el flag `-i`

In [171]:
!grep -i MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

        "a = 'MaximoFN'\n",
              "'MaximoFN'"
        "string = \"MaximoFN\"\n",
              "'MaximoFN'"
        "string = 'MaximoFN'\n",
              "'MaximoFN'"
            "Este es el blog de \"MaximoFN\"\n"
        "print(\"Este es el blog de \\\"MaximoFN\\\"\")"
            "Este es el blog de 'MaximoFN'\n"
        "print('Este es el blog de \\'MaximoFN\\'')"
            "Este es el blog de \\MaximoFN\\\n"
        "print('Este es el blog de \\\\MaximoFN\\\\')"
            "MaximoFN\n"
        "print('Este es el blog de \\nMaximoFN')"
            "Este es el blog de MaximoFN\n"
        "print('Esto no se imprimirá \\rEste es el blog de MaximoFN')"
            "Este es el blog de \tMaximoFN\n"
        "print('Este es el blog de \\tMaximoFN')"
            "Este es el blog deMaximoFN\n"
        "print('Este es el blog de \\bMaximoFN')"
            "MaximoFN\n"
            "MaximoFN\n"
              "b'MaximoFN'"
        "byte = b\"MaximoFN\"\n",
              "b'MaximoFN

Si lo que queremos es que nos devuelva el número de veces que aparece introducimos el flag `-c`

In [172]:
!grep -c MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Si nos da igual si aparece con mayúscula o minúscula podemos volver a agregar el flag `-i`, pero no hace falta meterlo separado del flag `-c`, se pueden introducir juntos

In [173]:
!grep -ci MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

105


Si ahora queremos todas las veces en las que **no** aparece la palabra `MáximoFN` instroducimos el flag `-v`

In [174]:
!grep -cv MaximoFN 2021-02-11-Introduccion-a-Python.ipynb

11573


## Utilidades de la terminal

### Utilidades de red

El primer comando va a ser `ifconfig` que nos muestra información de nuestras interfaces de red

In [175]:
!ifconfig

br-470e52ae2708: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:16:03:64:fa  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:6a:26:9c:1b  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5

Como vemos tenemos la información de todas las interfaces de red de mi ordenador, pero si quiero saber solo la de una, se especifica añadiendo su numbre

In [176]:
!ifconfig enp6s0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.144  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7dc2:6944:3fbe:c18e  prefixlen 64  scopeid 0x20<link>
        ether 24:4b:fe:5c:f6:59  txqueuelen 1000  (Ethernet)
        RX packets 740088  bytes 564669048 (564.6 MB)
        RX errors 0  dropped 2297  overruns 0  frame 0
        TX packets 773267  bytes 677643097 (677.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



Otro comando útil es `ping`, que nos puede servir para ver si tenemos conexión con una determinada `IP`. Por ejemplo, la `IP` de google es `142.250.200.78`, por lo que le hacemos `ping` a ver si nos contesta. El comando `ping` en linux hace `ping`s sin parar, por lo que nunca termina hasta que no lo paramos, para que no pase eso añadimos el flag `-c` y el número de intentos

In [179]:
!ping 142.250.200.68 -c 4

PING 142.250.200.68 (142.250.200.68) 56(84) bytes of data.
64 bytes from 142.250.200.68: icmp_seq=1 ttl=117 time=3.22 ms
64 bytes from 142.250.200.68: icmp_seq=2 ttl=117 time=3.66 ms
64 bytes from 142.250.200.68: icmp_seq=3 ttl=117 time=2.96 ms
64 bytes from 142.250.200.68: icmp_seq=4 ttl=117 time=3.20 ms

--- 142.250.200.68 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 2.960/3.259/3.656/0.250 ms


Lo mismo hubiese pasado si lo hubiésemos hecho directamente sobre `google.com`

In [178]:
!ping www.google.com -c 4

PING www.google.com (142.250.200.68) 56(84) bytes of data.
64 bytes from mad07s24-in-f4.1e100.net (142.250.200.68): icmp_seq=1 ttl=117 time=3.46 ms
64 bytes from mad07s24-in-f4.1e100.net (142.250.200.68): icmp_seq=2 ttl=117 time=2.92 ms
64 bytes from mad07s24-in-f4.1e100.net (142.250.200.68): icmp_seq=3 ttl=117 time=2.94 ms
64 bytes from mad07s24-in-f4.1e100.net (142.250.200.68): icmp_seq=4 ttl=117 time=2.99 ms

--- www.google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 2.916/3.076/3.463/0.224 ms


Podemos obtener un archivo de texto de una dirección dada mediante el comando `curl`, por ejemplo, nos podemos descargar el html de google

In [180]:
!curl https://www.google.com

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="kRRv1Jmvk_EyPXDf3lZ9LQ">(function(){window.google={kEI:'v8yEY5CQDIrg0PEP_NyGkAs',kEXPI:'0,1359409,6058,207,2414,2390,2316,383,246,5,5367,1123753,1197792,380699,16114,28684,22430,1362,12318,2817,14764,4998,13228,3847,10622,22742,5080,1595,1277,2742,149,1103,840,1983,4314,3514,606,2023,2297,14670,3227,2845,9,29072,4696,1851,2614,13142,3,346,230,6460,148,13975,4,1528,2304,7039,4887,15422,7422,7355,13660,4437,16786,5818,2539,4094,4052,3,3541,1,11942,30218,2,14016,25739,5679,1021,2380,22668,6073,4568,6256,23421,1252,5835,14967,4333,7484,25076

Tambien podemos hacer un pipeline para guardarlo en un archivo

In [182]:
!curl https://www.google.com > google.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15949    0 15949    0     0  56556      0 --:--:-- --:--:-- --:--:-- 56556


Ahora podemos ver si se ha guardado bien

In [183]:
!cat google.html

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es"><head><meta content="Google.es permite acceder a la informaci�n mundial en castellano, catal�n, gallego, euskara e ingl�s." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="fFiK5W11HEiG9GsXWX28Wg">(function(){window.google={kEI:'0cyEY9avD4zh0PEPy7GEgA4',kEXPI:'0,1359409,1709,4350,206,4804,2316,383,246,5,5367,1123753,1197730,317329,63432,16114,28684,22430,1362,12316,17583,4998,13228,3847,10622,22741,5081,1593,1279,2742,149,1103,840,1983,4314,3514,606,2025,2295,14670,3227,2845,7,24990,8780,1851,2614,13142,3,346,230,6459,149,13975,4,1528,2304,7039,27731,7357,13658,4437,16786,5800,2557,4094,17,4035,3,3541,1,14263,27891,2,14022,7646,18093,6699,2380,28742,4568,6256,23421,1252,5835,14967,4333,5016,2468,5627,5779,1

Otro comando parecido es `wget`, sin embargo, a diferencia de `curl`, wget descarga el archivo directamente

In [184]:
!wget https://www.google.com

--2022-11-28 15:59:41--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 172.217.168.164, 2a00:1450:4003:803::2004
Conectando con www.google.com (www.google.com)[172.217.168.164]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “index.html.1”

index.html.1            [ <=>                ]  15,54K  --.-KB/s    en 0,009s  

2022-11-28 15:59:41 (1,62 MB/s) - “index.html.1” guardado [15912]



In [185]:
!ls -l

total 316
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  15949 nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  15912 nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt


Vemos que lo ha guardado como `index.html`, que es como google lo tiene nombrado

Si queremos que se guarde con un nombre específico podemos usar el flag `-O`

In [186]:
!wget https://www.google.com -O google2.html

--2022-11-28 15:59:50--  https://www.google.com/
Resolviendo www.google.com (www.google.com)... 172.217.168.164, 2a00:1450:4003:803::2004
Conectando con www.google.com (www.google.com)[172.217.168.164]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Guardando como: “google2.html”

google2.html            [ <=>                ]  15,59K  --.-KB/s    en 0,01s   

2022-11-28 15:59:50 (1,55 MB/s) - “google2.html” guardado [15964]



In [187]:
!ls -l

total 332
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  15964 nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  15949 nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  15912 nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt


Un comando muy útil es ver la ruta hasta un destino, para ello usamos `traceroute`, por ejemplo vamos a ver todos los sitios por los que tengo que pasar para conectarme a google

In [188]:
!traceroute www.google.com

traceroute to www.google.com (172.217.168.164), 64 hops max
  1   192.168.1.1  0,491ms  0,151ms  0,141ms 
  2   188.127.176.1  7,852ms  4,517ms  9,176ms 
  3   10.15.0.77  3,340ms  3,113ms  2,930ms 
  4   10.15.246.6  3,282ms  2,995ms  2,917ms 
  5   *  *  * 
  6   72.14.195.182  3,817ms  3,102ms  2,825ms 
  7   *  *  * 
  8   142.250.232.26  57,435ms  5,071ms  4,894ms 
  9   74.125.253.201  4,098ms  4,095ms  4,061ms 
 10   172.217.168.164  2,810ms  2,941ms  3,077ms 


El último comando de utilidad des `netstats`, este comando nos da el estado de nuestra red, además con el flag `-i` nos devuelve nuestras interfaces de red

In [189]:
!netstat -i

Tabla de la interfaz del núcleo
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
br-470e5  1500        0      0      0 0             0      0      0      0 BMU
docker0   1500        0      0      0 0             0      0      0      0 BMU
enp6s0    1500   741277      0   2327 0        774584      0      0      0 BMRU
lo       65536    13658      0      0 0         13658      0      0      0 LRU
wlp5s0    1500        0      0      0 0             0      0      0      0 BMU


### Comprimiendo archivos

Antes de comprimir y descomprimir vamos a ver qué vamos a comprimir, primero imprimimos nuestra ruta y listamos los archivos

In [192]:
!pwd; ls -l

/home/wallabot/Documentos/web/portafolio/posts/prueba
total 332
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  15964 nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  15949 nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  15912 nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt


Vamos a crear una nueva carpeta y a copiar todo lo que está dentro de la actual carpeta en ella

In [193]:
!mkdir tocompress; cp * tocompress; ls -l

cp: -r not specified; omitting directory 'tocompress'
total 336
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  15964 nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  15949 nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  15912 nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 nov 28 16:02 tocompress


Como vemos se ha compiado todo menos la propia carpeta `tocompress` ya que no hemos puesto el flag `-r` en el comando `cp`. Pero lo que ha pasado es lo que queríamos

#### Comrpimir con `tar`

El primero comando que vamos a usar para comprimir es `tar` al que vamos a añadir el flag `-c` de compress, `-v` de verbose, para que nos vaya sacando qué está haciendo y el flag `-f` de file, y a continuación el nombre que queremos que tenga el archivo comprimido y el nombre del archivo que queremos comprimir

In [194]:
!tar -cvf tocompress.tar tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [195]:
!ls -l

total 676
-rw-rw-r-- 1 wallabot wallabot 285898 nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  15964 nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  15949 nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  15912 nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot    182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot      0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot   4096 nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 348160 nov 28 16:02 tocompress.tar


Vemos que ha creado el archivo `tocompress.tar`

Ahora vamos a repetir el proceso, pero añadiendo el flag `-z`, esto lo que hace es comprimir en el formato `gzip`, que es un algoritmo de compresión más eficiente

In [196]:
!tar -cvzf tocompress.tar.gz tocompress

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [197]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K nov 28 16:02 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K nov 28 16:03 tocompress.tar.gz


Como se puede ver el archivo `tocompress.tar` ocupa `340 kB`, mientras que el archivo `tocompress.tar.gz` ocupa solo `52 kB`

Ahora vamos a descomprimir los archivos, para descomprimir, se usa el mismo comando, solo que cambiando el flag `-c` por el flag `-x`

Primero borramos la carpeta original

In [198]:
!rm -r tocompress

Descomprimimos

In [199]:
!tar -xvf tocompress.tar

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [200]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K nov 28 16:02 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K nov 28 16:03 tocompress.tar.gz


Hacemos lo mismo con el `gzip`

In [201]:
!rm -r tocompress

In [202]:
!tar -xvzf tocompress.tar.gz

tocompress/
tocompress/lista.txt
tocompress/dot.txt
tocompress/google.html
tocompress/index.html
tocompress/Abc
tocompress/google2.html
tocompress/dot2.txt
tocompress/secuential.txt
tocompress/index.html.1
tocompress/file.txt
tocompress/datos1
tocompress/2021-02-11-Introduccion-a-Python.ipynb
tocompress/datos123


In [203]:
!ls -lh

total 728K
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K nov 28 16:02 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K nov 28 16:03 tocompress.tar.gz


#### Comprimir con `zip`

Otro comando para comprimir el `zip`, para comprimir solo hay que añadirle el flag `-r` (recursive), el nombre que queremos que tenga el archivo comprimido y el archivo que queremos comprimir

In [204]:
!zip -r tocompress.zip tocompress

  adding: tocompress/ (stored 0%)
  adding: tocompress/lista.txt (deflated 23%)
  adding: tocompress/dot.txt (stored 0%)
  adding: tocompress/google.html (deflated 56%)
  adding: tocompress/index.html (stored 0%)
  adding: tocompress/Abc (stored 0%)
  adding: tocompress/google2.html (deflated 56%)
  adding: tocompress/dot2.txt (stored 0%)
  adding: tocompress/secuential.txt (stored 0%)
  adding: tocompress/index.html.1 (deflated 56%)
  adding: tocompress/file.txt (stored 0%)
  adding: tocompress/datos1 (stored 0%)
  adding: tocompress/2021-02-11-Introduccion-a-Python.ipynb (deflated 85%)
  adding: tocompress/datos123 (stored 0%)


In [205]:
!ls -lh

total 796K
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K nov 28 16:02 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K nov 28 16:03 tocompress.tar.gz
-r

Para descomprimir se usa el comando `unzip` seguido del nombre del archivo que quiero descomprimir. Primero borramos la carpeta `tocompress`

In [206]:
!rm -r tocompress

In [207]:
!unzip tocompress.zip

Archive:  tocompress.zip
   creating: tocompress/
  inflating: tocompress/lista.txt    
 extracting: tocompress/dot.txt      
  inflating: tocompress/google.html  
 extracting: tocompress/index.html   
 extracting: tocompress/Abc          
  inflating: tocompress/google2.html  
 extracting: tocompress/dot2.txt     
 extracting: tocompress/secuential.txt  
  inflating: tocompress/index.html.1  
 extracting: tocompress/file.txt     
 extracting: tocompress/datos1       
  inflating: tocompress/2021-02-11-Introduccion-a-Python.ipynb  
 extracting: tocompress/datos123     


In [208]:
!ls -lh

total 796K
-rw-rw-r-- 1 wallabot wallabot 280K nov 28 15:06 2021-02-11-Introduccion-a-Python.ipynb
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 Abc
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos1
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 datos123
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot2.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 dot.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 file.txt
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google2.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 google.html
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:12 index.html
-rw-rw-r-- 1 wallabot wallabot  16K nov 28 15:59 index.html.1
-rw-rw-r-- 1 wallabot wallabot  182 nov 28 15:15 lista.txt
-rw-rw-r-- 1 wallabot wallabot    0 nov 28 15:24 secuential.txt
drwxrwxr-x 2 wallabot wallabot 4,0K nov 28 16:02 tocompress
-rw-rw-r-- 1 wallabot wallabot 340K nov 28 16:02 tocompress.tar
-rw-rw-r-- 1 wallabot wallabot  52K nov 28 16:03 tocompress.tar.gz
-r

### Procesos en background y foreground

#### Pausar un proceso y llevarlo al background con `CTRL+z`

Cuando corremos un proceso en la terminal, este puede que no pare de ejecutarse y queramos seguir usando la terminal, para solucionar esto podemos llevarnos el proceso al background presionando `CTRL+z`

Por ejemplo, me puedo hacer un ping a mi mismo, sin especificar el número de intentos, por lo que esto se estará ejecutando hasta que pare el proceso presionando `CTRL+C`

``` bash
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.036 ms
^C
--- localhost ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5127ms
rtt min/avg/max/mdev = 0.024/0.027/0.036/0.004 ms
```

Sin embargo, si lo que queremos es parar un momento el proceso para poder seguir usando la terminal, hay que introducir `CTRL+Z`

``` bash
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.020 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.017 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.021 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.055 ms
^Z
[1]+  Detenido                ping localhost
```

Como se indica, el proceso ha sido detenido, no se está ejecutando mientras lo he llevado al background

#### Ver los procesos en background

Para ver qué procesos están en el background tenemos dos comandos, por un lado podemos usar `jobs`

``` bash
$ jobs
[1]+  Detenido                ping localhost
```

Este comando nos da el proceso y el número de job, este número será el que deberemos usar para llevar el proceso al foreground

Otro comando que podemos usar es `ps` (processes)

``` bash
$ ps
    PID TTY          TIME CMD
  16232 pts/3    00:00:00 bash
  17070 pts/3    00:00:00 ping
  18376 pts/3    00:00:00 ps
```

Este comando no solo nos da la información de los procesos que corren en background, sino de todos los procesos que están corriendo en la terminal

Es importante recalcar, que si abrimos una nueva terminal y usamos cualquiera de estos comandos no nos va a dar la información del ping, ya que lo ejecutamos en otra terminal

``` bash
$ jobs
$ ps
    PID TTY          TIME CMD
  18993 pts/2    00:00:00 bash
  19290 pts/2    00:00:00 ps
```

Como vemos `jobs` no devuelve nada porque en esta terminal no hay ningún proceso en el background y `ps` solo nos devuelve la información de bash (la propia terminal) y el comando ps lanzado

#### Llevar un proceso del background al foreground

Para llevar un proceso al foreground hay que usar el comando `fg`, si se quiere traer el último que se ha llevado al background solo con poner `fg` vale, si no hay que indicarle el número de job

Vamos a volver a ver los procesos que teníamos en el background

``` bash
$ jobs
[1]+  Detenido                ping localhost
```

Nos podemos llevar este proceso al foreground solo escribiendo `fg` o indicándole el número de job mediante `fg %1`

``` bash
$ fg %1
ping localhost
64 bytes from localhost (127.0.0.1): icmp_seq=7 ttl=64 time=0.032 ms
64 bytes from localhost (127.0.0.1): icmp_seq=8 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=9 ttl=64 time=0.045 ms
64 bytes from localhost (127.0.0.1): icmp_seq=10 ttl=64 time=0.035 ms
64 bytes from localhost (127.0.0.1): icmp_seq=11 ttl=64 time=0.031 ms
```

#### Correr un proceso directamente en el background

Vamos a volver a lanzar ahora el navegador firefox escribiendo `firefox` en la terminal y pulsar `CTRL+Z` para llevarlo al background

``` bash
$ firefox
[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:16:17Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update
^Z
[1]+  Detenido                firefox
```

Como vemos, pone que el proceso ha sido detenido, por lo que si ahora queremos navegar por firefox no podemos, ya que está detenido.

Para poder lanzar firefox y que esté en background para que no nos bloquee la terminal hay que escribir un `&` al final del comando

``` bash
$ firefox &
[1] 23663
$ [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
[2022-11-29T06:19:40Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update

$
```

Ahora nos lanzamos firefox, nos dice su número de job y se queda en el background ejecutándose

De hecho, si ahora miramos los procesos, podemos ver el estado de firefox es *Ejecutando*

``` bash
$ jobs
[1]+  Ejecutando              firefox &
```

#### Terminar un proceso que está en background

Como tenemos firefox corriendo en background, si queremos que termine tenemos que usar `kill` y el número de job del proceso. Vamos a usar `jobs` para ver el número de job de firefox

``` bash
$ jobs
[1]+  Ejecutando              firefox &
```

Su número de trabajo es el 1, por lo que ponemos ese número para terminar el proceso

``` bash
$ kill %1
```

No nos responde nada, pero si volvemos a usar `jobs` para ver los procesos en el background

``` bash
$ jobs
[1]+  Terminado               firefox
```

Vemos que nos dice que firefox ha terminado, si volvemos a ejecutar `jobs` ya no aparecerá nada

``` bash
$ jobs
```

### Procesos en background independientes de la terminal

Hasta ahora hemos visto cómo ejecutar procesos en background dependientes de la terminal, esto quiere decir, que is mandamos al background un procesos y cerramos la terminal, este mandará un mensaje de fin a todos los procesos que están en su background y terminarán

Pero hay veces que nos interesa que el proceso se quede en background, poder cerrar la terminal, abrir otra y recuperar ese proceso, para ello usaremos `tmux`, que es un multiplexor de terminal.

Es posible que te venga instalada, por lo que para instalarla tienes que introducir lo siguiente

``` bash
sudo apt install tmux
```

Una vez instalada podemos crear una nueva sesión de `tmux` mediante el `tmux new -s <name>`

``` bash
tmux new -s session1
```

Esto nos abrirá una nueva terminal, que en realidad es una sesión de `tmux`

Dentro de ella podemos lanzar un proceso, por ejemplo un `ping` a nosotros mismos

``` bash
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.019 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.031 ms
```

Podemos cerrar esa terminal

Si abrimos una nueva, podemos ver todas las sesiones de `tmux` abiertas con el comando `tmux ls`

In [6]:
!tmux ls

session1: 1 windows (created Tue Nov 29 08:15:22 2022)


Y podemos entrar en una sesión mediante el comando `tmux`, seguido de `a` (attach), `-t` (tag) y el nombre de la sesión

```
$ tmux a -t session1
64 bytes from localhost (127.0.0.1): icmp_seq=146 ttl=64 time=0.025 ms
64 bytes from localhost (127.0.0.1): icmp_seq=147 ttl=64 time=0.022 ms
64 bytes from localhost (127.0.0.1): icmp_seq=148 ttl=64 time=0.026 ms
64 bytes from localhost (127.0.0.1): icmp_seq=149 ttl=64 time=0.013 ms
64 bytes from localhost (127.0.0.1): icmp_seq=150 ttl=64 time=0.027 ms
64 bytes from localhost (127.0.0.1): icmp_seq=151 ttl=64 time=0.019 ms
```

Como vemos hemos recuperado el `ping` de antes

Cuando estamos dentro de una sesión podemos salir de ella (matándola) escribiendo `CTRL+D` o escribiendo `exit`

### Manejo de procesos

Para manejar los procesos de nuestro sistema tenemos varias opciones

#### `ps`

Como hemos visto antes `ps` nos da los procesos que están corriendo en nuestra terminal. Por ejemplo ejecutamos un proceso en el background y vemos los procesos con `ps`

``` bash
$ firefox &
[1] 50555
```

Vemos ahora los procesos

``` bash
$ ps
    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  50555 pts/3    00:00:02 firefox
  50613 pts/3    00:00:00 Socket Process
  50635 pts/3    00:00:00 Privileged Cont
  50683 pts/3    00:00:00 WebExtensions
  50741 pts/3    00:00:00 Web Content
  50743 pts/3    00:00:00 Web Content
  50748 pts/3    00:00:00 Web Content
  50840 pts/3    00:00:00 ps
```

Una vez sepamos su PID podemos matar el proceso

``` bash
$ kill 50555
```

Vemos ahora los procesos

``` bash
$ ps
    PID TTY          TIME CMD
  36660 pts/3    00:00:00 bash
  51132 pts/3    00:00:00 ps
```

Pero como hemos dicho, lo malo de ps es que solo muestra los procesos de su terminal

#### `top`

Con `top` podemos ver todos los procesos del sistema operativo. Nos enseñará la información con `less`, por lo que al igual que se ha explicado antes, cuando se quiera parar `top`, introduciendo `q` parará

``` bash
$ top

top - 09:31:32 up  3:21,  1 user,  load average: 2,42, 2,79, 2,48
Tareas: 382 total,   1 ejecutar,  381 hibernar,    0 detener,    0 zombie
%Cpu(s): 14,2 usuario,  1,5 sist,  0,0 adecuado, 84,3 inact,  0,0 en espera,  0,
MiB Mem :  32006,4 total,  20281,8 libre,   6229,0 usado,   5495,6 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24979,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 137,5   1,2 282:24.59 python   
  44161 wallabot  20   0   30,2g 217208 100148 S  12,5   0,7   0:40.92 spotify  
     76 root      20   0       0      0      0 S   6,2   0,0   0:00.12 ksoftir+ 
   1105 root     -51   0       0      0      0 S   6,2   0,0   2:54.29 irq/125+ 
  43990 wallabot  20   0 3998836 246260 145800 S   6,2   0,8   0:53.69 spotify  
  44101 wallabot  20   0 1995108 130316  89848 S   6,2   0,4   0:08.34 spotify  
  51510 wallabot  20   0   14876   4088   3288 R   6,2   0,0   0:00.01 top      
      1 root      20   0  169736  13188   8380 S   0,0   0,0   0:01.51 systemd  
      2 root      20   0       0      0      0 S   0,0   0,0   0:00.00 kthreadd 
      3 root       0 -20       0      0      0 I   0,0   0,0   0:00.00 rcu_gp   
      4 root       0 -20       0      0      0 I   0,0   0,0   0:00.00 rcu_par+ 
      5 root       0 -20       0      0      0 I   0,0   0,0   0:00.00 netns    
      7 root       0 -20       0      0      0 I   0,0   0,0   0:00.00 kworker+ 
      9 root       0 -20       0      0      0 I   0,0   0,0   0:00.03 kworker+ 
     10 root       0 -20       0      0      0 I   0,0   0,0   0:00.00 mm_perc+ 
     11 root      20   0       0      0      0 S   0,0   0,0   0:00.00 rcu_tas+ 
     12 root      20   0       0      0      0 S   0,0   0,0   0:00.00 rcu_tas+
```

Como se puede ver, el `PID` 44161 es spotify que lo estoy usando ahora para reproducir música, pero con `ps` no lo habíamos visto

Al igual que antes, si queremos matar un proceso debemos introducir `kill` y su `PID`

Lo bueno de top es que nos da muchas más utilidades, si pulsamos `h` nos mostrará una ayuda

``` bash
Help for Interactive Commands - procps-ng 3.3.16
Window 1:Def: Cumulative mode Apagado.  System: Delay 3,0 secs; Secure mode Apag

  Z,B,E,e   Global: 'Z' colors; 'B' bold; 'E'/'e' summary/task memory scale
  l,t,m     Toggle Summary: 'l' load avg; 't' task/cpu stats; 'm' memory info
  0,1,2,3,I Toggle: '0' zeros; '1/2/3' cpus or numa node views; 'I' Irix mode
  f,F,X     Fields: 'f'/'F' add/remove/order/sort; 'X' increase fixed-width

  L,&,<,> . Locate: 'L'/'&' find/again; Move sort column: '<'/'>' left/right
  R,H,J,C . Toggle: 'R' Sort; 'H' Threads; 'J' Num justify; 'C' Coordinates
  c,i,S,j . Toggle: 'c' Cmd name/line; 'i' Idle; 'S' Time; 'j' Str justify
  x,y     . Toggle highlights: 'x' sort field; 'y' running tasks
  z,b     . Toggle: 'z' color/mono; 'b' bold/reverse (only if 'x' or 'y')
  u,U,o,O . Filter by: 'u'/'U' effective/any user; 'o'/'O' other criteria
  n,#,^O  . Set: 'n'/'#' max tasks displayed; Show: Ctrl+'O' other filter(s)
  V,v     . Toggle: 'V' forest view; 'v' hide/show forest view children

  k,r Gestiona tareas: «k» detener; «r» reiniciar
  d o s Establece intervalo de actualización
  W,Y       Write configuration file 'W'; Inspect other output 'Y'
  q         Quit
          ( commands shown with '.' require a visible task display window ) 
Press 'h' or '?' for help with Windows,
Type 'q' or <Esc> to continue
```

Para salir pulsar `ESC` o `q`

Como se muestra en la ayuda, si se introduce `u` podemos filtrar por usuario, introducimos mi usuario (wallabot) y puedo ver solo mis procesos

``` bash
top - 09:35:57 up  3:25,  1 user,  load average: 1,02, 2,27, 2,39
Tareas: 378 total,   1 ejecutar,  377 hibernar,    0 detener,    0 zombie
%Cpu(s): 13,4 usuario,  0,4 sist,  0,0 adecuado, 86,1 inact,  0,1 en espera,  0,
MiB Mem :  32006,4 total,  20288,0 libre,   6212,0 usado,   5506,4 búfer/caché
MiB Intercambio:   2048,0 total,   2048,0 libre,      0,0 usado.  24989,1 dispon

    PID USUARIO   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     HORA+ ORDEN    
  10192 wallabot  20   0 3347636 388848  84140 S 148,2   1,2 288:46.50 python   
  43990 wallabot  20   0 3998836 246552 146092 S   2,7   0,8   0:59.55 spotify  
   1384 wallabot  20   0 4909848 453700 133164 S   1,7   1,4  11:14.02 gnome-s+ 
   1119 wallabot   9 -11 3093876  24504  17836 S   1,3   0,1   0:48.99 pulseau+ 
  32462 wallabot  20   0 1134,0g 643412 128632 S   1,3   2,0   7:39.91 chrome   
  44161 wallabot  20   0   30,2g 217112 100488 S   1,3   0,7   0:44.87 spotify  
  10135 wallabot  20   0  826220  58164  41648 S   1,0   0,2   0:14.56 gnome-t+ 
   6635 wallabot  20   0   33,0g 647936 436252 S   0,3   2,0   4:01.80 chrome   
   6679 wallabot  20   0   32,4g 125564  94016 S   0,3   0,4   0:52.19 chrome   
   8010 wallabot  20   0 1130,9g 232800 116092 S   0,3   0,7   0:13.70 chrome   
  44101 wallabot  20   0 1995108 130444  89916 S   0,3   0,4   0:09.19 spotify  
   1113 wallabot  20   0   19880  10528   8096 S   0,0   0,0   0:00.38 systemd  
   1114 wallabot  20   0  169792   3636     12 S   0,0   0,0   0:00.00 (sd-pam) 
   1121 wallabot  39  19  591436  37256  16676 S   0,0   0,1   0:03.19 tracker+ 
   1124 wallabot  20   0  390740   8688   7416 S   0,0   0,0   0:00.45 gnome-k+ 
   1128 wallabot  20   0  166804   6596   5956 S   0,0   0,0   0:00.00 gdm-x-s+ 
   1134 wallabot  20   0    9152   6144   3796 S   0,0   0,0   0:01.81 dbus-da+
```

Otra forma de ver esto poder filtrar por usuario sería hacerse un pipeline y usando `grep`

``` bash
$ top | grep wallabot
   1440 wallabot  20   0 4684708 505432 118024 S   6,7   1,5   2:05.92 gnome-s+ 
  25326 wallabot  20   0 1133,0g 527912 123732 S   1,7   1,6   1:31.73 chrome   
   1440 wallabot  20   0 4684708 505476 118024 S   1,3   1,5   2:05.96 gnome-s+ 
   6199 wallabot  20   0 1131,0g 266068 116164 S   0,3   0,8   0:15.23 chrome   
  17606 wallabot  20   0  818228  52096  39488 S   0,3   0,2   0:02.59 gnome-t+ 
  34284 wallabot  20   0   14876   4376   3308 R   0,3   0,0   0:00.02 top
```

#### `htop`

Es parecido a `top` pero más potente

Probablemente no lo tengas instalado, así que para instalarlo introduce el comando

``` bash
sudo apt install htop
```

o

``` bash
sudo snap install htop
```

#### `glances`

Es parecido a `top` pero más potente

Probablemente no lo tengas instalado, así que para instalarlo introduce el comando

``` bash
sudo apt install glances
```

### Gestión de interfaces

En Ubuntu, por defecto arrancamos en un interfaz gráfica, pero podemos abrir otras interfaces, que no serán gráficas, introduciendo `CTRL`+`ALT`+`F<num>` donde el número puede ir desde el 1 hasta el 6. Solo la 2 tendrá la interfaz gráfica y la 1 será el inicio de sesión

Al manejar varias interfaces podemos no saber en cual nos encontramos, así que introduciendo el comando `tty` nos dirá en cual estamos

In [1]:
!tty

/dev/pts/0


## Fricadas

### Cowsay

Hay un comando llamado `cowsay` al que le pasas como parámetro un texto y te dibuja una vaca diciendo ese texto

Es posible que no lo tengas instalado, por lo que para instalarlo tienes que introducir el comando

``` bash
sudo apt install cowsay
```

In [12]:
terminal("cowsay MaximoFN")

 __________
< MaximoFN >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||



Si le añades el flag `-f dragon` quien lo dice es un dragón

In [15]:
terminal("cowsay -f dragon MaximoFN")

 __________
< MaximoFN >
 ----------
      \                    / \  //\
       \    |\___/|      /   \//  \\
            /0  0  \__  /    //  | \ \    
           /     /  \/_/    //   |  \  \  
           @_^_@'/   \/_   //    |   \   \ 
           //_^_/     \/_ //     |    \    \
        ( //) |        \///      |     \     \
      ( / /) _|_ /   )  //       |      \     _\
    ( // /) '/,_ _ _/  ( ; -.    |    _ _\.-~        .-~~~^-.
  (( / / )) ,-{        _      `-.|.-~-.           .~         `.
 (( // / ))  '/\      /                 ~-. _ .-~      .-~^-.  \
 (( /// ))      `.   {            }                   /      \  \
  (( / ))     .----~-.\        \-'                 .~         \  `. \^-.
             ///.----..>        \             _ -~             `.  ^-`  ^-_
               ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                  /.-~



In [14]:
terminal("cowsay -f dragon-and-cow MaximoFN")

 __________
< MaximoFN >
 ----------
                       \                    ^    /^
                        \                  / \  // \
                         \   |\___/|      /   \//  .\
                          \  /O  O  \__  /    //  | \ \           *----*
                            /     /  \/_/    //   |  \  \          \   |
                            @___@`    \/_   //    |   \   \         \/\ \
                           0/0/|       \/_ //     |    \    \         \  \
                       0/0/0/0/|        \///      |     \     \       |  |
                    0/0/0/0/0/_|_ /   (  //       |      \     _\     |  /
                 0/0/0/0/0/0/`/,_ _ _/  ) ; -.    |    _ _\.-~       /   /
                             ,-}        _      *-.|.-~-.           .~    ~
            \     \__/        `/\      /                 ~-. _ .-~      /
             \____(oo)           *.   }            {                   /
             (    (--)          .----~-.\        \-`          